/* test-codificacion.c generated by valac 0.34.8, the Vala compiler
 * generated from test-codificacion.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "test.h"
#include "codificacion.h"
#include <stdlib.h>
#include <string.h>


#define CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION (cubo_genetico_test_test_codificacion_get_type ())
#define CUBO_GENETICO_TEST_TEST_CODIFICACION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION, CuboGeneticoTestTestCodificacion))
#define CUBO_GENETICO_TEST_TEST_CODIFICACION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION, CuboGeneticoTestTestCodificacionClass))
#define CUBO_GENETICO_TEST_IS_TEST_CODIFICACION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION))
#define CUBO_GENETICO_TEST_IS_TEST_CODIFICACION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION))
#define CUBO_GENETICO_TEST_TEST_CODIFICACION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION, CuboGeneticoTestTestCodificacionClass))

typedef struct _CuboGeneticoTestTestCodificacion CuboGeneticoTestTestCodificacion;
typedef struct _CuboGeneticoTestTestCodificacionClass CuboGeneticoTestTestCodificacionClass;
typedef struct _CuboGeneticoTestTestCodificacionPrivate CuboGeneticoTestTestCodificacionPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _CuboGeneticoTestTestCodificacion {
	CuboGeneticoTestTestCase parent_instance;
	CuboGeneticoTestTestCodificacionPrivate * priv;
};

struct _CuboGeneticoTestTestCodificacionClass {
	CuboGeneticoTestTestCaseClass parent_class;
};

struct _CuboGeneticoTestTestCodificacionPrivate {
	CuboGeneticoCodificacionFenoGeno* c;
};


static gpointer cubo_genetico_test_test_codificacion_parent_class = NULL;

GType cubo_genetico_test_test_codificacion_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_TEST_TEST_CODIFICACION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION, CuboGeneticoTestTestCodificacionPrivate))
enum  {
	CUBO_GENETICO_TEST_TEST_CODIFICACION_DUMMY_PROPERTY
};
CuboGeneticoTestTestCodificacion* cubo_genetico_test_test_codificacion_new (void);
CuboGeneticoTestTestCodificacion* cubo_genetico_test_test_codificacion_construct (GType object_type);
void cubo_genetico_test_test_codificacion_test_coDecoR (CuboGeneticoTestTestCodificacion* self);
static void _cubo_genetico_test_test_codificacion_test_coDecoR_cubo_genetico_test_test_case_test_method (gpointer self);
void cubo_genetico_test_test_codificacion_test_coDeco (CuboGeneticoTestTestCodificacion* self);
static void _cubo_genetico_test_test_codificacion_test_coDeco_cubo_genetico_test_test_case_test_method (gpointer self);
static void cubo_genetico_test_test_codificacion_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void _cubo_genetico_test_test_codificacion_test_coDecoR_cubo_genetico_test_test_case_test_method (gpointer self) {
	cubo_genetico_test_test_codificacion_test_coDecoR ((CuboGeneticoTestTestCodificacion*) self);
}


static void _cubo_genetico_test_test_codificacion_test_coDeco_cubo_genetico_test_test_case_test_method (gpointer self) {
	cubo_genetico_test_test_codificacion_test_coDeco ((CuboGeneticoTestTestCodificacion*) self);
}


CuboGeneticoTestTestCodificacion* cubo_genetico_test_test_codificacion_construct (GType object_type) {
	CuboGeneticoTestTestCodificacion * self = NULL;
	CuboGeneticoCodificacionFenoGeno* _tmp0_ = NULL;
	self = (CuboGeneticoTestTestCodificacion*) cubo_genetico_test_test_case_construct (object_type, "TestCodificacion");
	cubo_genetico_test_test_case_add_test ((CuboGeneticoTestTestCase*) self, "test_coDecoR", _cubo_genetico_test_test_codificacion_test_coDecoR_cubo_genetico_test_test_case_test_method, g_object_ref (self), g_object_unref);
	cubo_genetico_test_test_case_add_test ((CuboGeneticoTestTestCase*) self, "test_coDecoR", _cubo_genetico_test_test_codificacion_test_coDeco_cubo_genetico_test_test_case_test_method, g_object_ref (self), g_object_unref);
	_tmp0_ = cubo_genetico_codificacion_feno_geno_new (9);
	_g_object_unref0 (self->priv->c);
	self->priv->c = _tmp0_;
	return self;
}


CuboGeneticoTestTestCodificacion* cubo_genetico_test_test_codificacion_new (void) {
	return cubo_genetico_test_test_codificacion_construct (CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION);
}


void cubo_genetico_test_test_codificacion_test_coDecoR (CuboGeneticoTestTestCodificacion* self) {
	gint* g = NULL;
	CuboGeneticoCodificacionFenoGeno* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint* _tmp2_ = NULL;
	gint g_length1 = 0;
	gint _g_size_ = 0;
	gchar** f = NULL;
	CuboGeneticoCodificacionFenoGeno* _tmp3_ = NULL;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	gint _tmp5_ = 0;
	gchar** _tmp6_ = NULL;
	gint f_length1 = 0;
	gint _f_size_ = 0;
	gint* gprima = NULL;
	CuboGeneticoCodificacionFenoGeno* _tmp7_ = NULL;
	gchar** _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	gint _tmp9_ = 0;
	gint* _tmp10_ = NULL;
	gint gprima_length1 = 0;
	gint _gprima_size_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->c;
	_tmp2_ = cubo_genetico_codificacion_feno_geno_genoAleatNuev (_tmp0_, 10, &_tmp1_);
	g = _tmp2_;
	g_length1 = _tmp1_;
	_g_size_ = g_length1;
	_tmp3_ = self->priv->c;
	_tmp4_ = g;
	_tmp4__length1 = g_length1;
	_tmp6_ = cubo_genetico_codificacion_feno_geno_decodifica (_tmp3_, _tmp4_, _tmp4__length1, &_tmp5_);
	f = _tmp6_;
	f_length1 = _tmp5_;
	_f_size_ = f_length1;
	_tmp7_ = self->priv->c;
	_tmp8_ = f;
	_tmp8__length1 = f_length1;
	_tmp10_ = cubo_genetico_codificacion_feno_geno_codifica (_tmp7_, _tmp8_, _tmp8__length1, &_tmp9_);
	gprima = _tmp10_;
	gprima_length1 = _tmp9_;
	_gprima_size_ = gprima_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp11_ = FALSE;
			_tmp11_ = TRUE;
			while (TRUE) {
				gint _tmp13_ = 0;
				gint* _tmp14_ = NULL;
				gint _tmp14__length1 = 0;
				gint* _tmp15_ = NULL;
				gint _tmp15__length1 = 0;
				gint _tmp16_ = 0;
				gint _tmp17_ = 0;
				gint* _tmp18_ = NULL;
				gint _tmp18__length1 = 0;
				gint _tmp19_ = 0;
				gint _tmp20_ = 0;
				if (!_tmp11_) {
					gint _tmp12_ = 0;
					_tmp12_ = i;
					i = _tmp12_ + 1;
				}
				_tmp11_ = FALSE;
				_tmp13_ = i;
				_tmp14_ = g;
				_tmp14__length1 = g_length1;
				if (!(_tmp13_ < _tmp14__length1)) {
					break;
				}
				_tmp15_ = gprima;
				_tmp15__length1 = gprima_length1;
				_tmp16_ = i;
				_tmp17_ = _tmp15_[_tmp16_];
				_tmp18_ = g;
				_tmp18__length1 = g_length1;
				_tmp19_ = i;
				_tmp20_ = _tmp18_[_tmp19_];
				_vala_assert (_tmp17_ == _tmp20_, "gprima[i]==g[i]");
			}
		}
	}
	gprima = (g_free (gprima), NULL);
	f = (_vala_array_free (f, f_length1, (GDestroyNotify) g_free), NULL);
	g = (g_free (g), NULL);
}


void cubo_genetico_test_test_codificacion_test_coDeco (CuboGeneticoTestTestCodificacion* self) {
	gint* pr1 = NULL;
	gint* _tmp0_ = NULL;
	gint pr1_length1 = 0;
	gint _pr1_size_ = 0;
	gchar** pr2 = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar** _tmp9_ = NULL;
	gint pr2_length1 = 0;
	gint _pr2_size_ = 0;
	gchar** f = NULL;
	CuboGeneticoCodificacionFenoGeno* _tmp10_ = NULL;
	gint* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	gint _tmp12_ = 0;
	gchar** _tmp13_ = NULL;
	gint f_length1 = 0;
	gint _f_size_ = 0;
	gint* g = NULL;
	CuboGeneticoCodificacionFenoGeno* _tmp24_ = NULL;
	gchar** _tmp25_ = NULL;
	gint _tmp25__length1 = 0;
	gint _tmp26_ = 0;
	gint* _tmp27_ = NULL;
	gint g_length1 = 0;
	gint _g_size_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_new0 (gint, 8);
	_tmp0_[0] = 1;
	_tmp0_[1] = 5;
	_tmp0_[2] = 2;
	_tmp0_[3] = 5;
	_tmp0_[4] = 1;
	_tmp0_[5] = 5;
	_tmp0_[6] = 5;
	_tmp0_[7] = 2;
	pr1 = _tmp0_;
	pr1_length1 = 8;
	_pr1_size_ = pr1_length1;
	_tmp1_ = g_strdup ("R");
	_tmp2_ = g_strdup ("U");
	_tmp3_ = g_strdup ("R'");
	_tmp4_ = g_strdup ("U");
	_tmp5_ = g_strdup ("R");
	_tmp6_ = g_strdup ("U");
	_tmp7_ = g_strdup ("U");
	_tmp8_ = g_strdup ("R'");
	_tmp9_ = g_new0 (gchar*, 8 + 1);
	_tmp9_[0] = _tmp1_;
	_tmp9_[1] = _tmp2_;
	_tmp9_[2] = _tmp3_;
	_tmp9_[3] = _tmp4_;
	_tmp9_[4] = _tmp5_;
	_tmp9_[5] = _tmp6_;
	_tmp9_[6] = _tmp7_;
	_tmp9_[7] = _tmp8_;
	pr2 = _tmp9_;
	pr2_length1 = 8;
	_pr2_size_ = pr2_length1;
	_tmp10_ = self->priv->c;
	_tmp11_ = pr1;
	_tmp11__length1 = pr1_length1;
	_tmp13_ = cubo_genetico_codificacion_feno_geno_decodifica (_tmp10_, _tmp11_, _tmp11__length1, &_tmp12_);
	f = _tmp13_;
	f_length1 = _tmp12_;
	_f_size_ = f_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp14_ = FALSE;
			_tmp14_ = TRUE;
			while (TRUE) {
				gint _tmp16_ = 0;
				gint* _tmp17_ = NULL;
				gint _tmp17__length1 = 0;
				gchar** _tmp18_ = NULL;
				gint _tmp18__length1 = 0;
				gint _tmp19_ = 0;
				const gchar* _tmp20_ = NULL;
				gchar** _tmp21_ = NULL;
				gint _tmp21__length1 = 0;
				gint _tmp22_ = 0;
				const gchar* _tmp23_ = NULL;
				if (!_tmp14_) {
					gint _tmp15_ = 0;
					_tmp15_ = i;
					i = _tmp15_ + 1;
				}
				_tmp14_ = FALSE;
				_tmp16_ = i;
				_tmp17_ = pr1;
				_tmp17__length1 = pr1_length1;
				if (!(_tmp16_ < _tmp17__length1)) {
					break;
				}
				_tmp18_ = f;
				_tmp18__length1 = f_length1;
				_tmp19_ = i;
				_tmp20_ = _tmp18_[_tmp19_];
				_tmp21_ = pr2;
				_tmp21__length1 = pr2_length1;
				_tmp22_ = i;
				_tmp23_ = _tmp21_[_tmp22_];
				_vala_assert (g_strcmp0 (_tmp20_, _tmp23_) == 0, "f[i]==pr2[i]");
			}
		}
	}
	_tmp24_ = self->priv->c;
	_tmp25_ = pr2;
	_tmp25__length1 = pr2_length1;
	_tmp27_ = cubo_genetico_codificacion_feno_geno_codifica (_tmp24_, _tmp25_, _tmp25__length1, &_tmp26_);
	g = _tmp27_;
	g_length1 = _tmp26_;
	_g_size_ = g_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp28_ = FALSE;
			_tmp28_ = TRUE;
			while (TRUE) {
				gint _tmp30_ = 0;
				gchar** _tmp31_ = NULL;
				gint _tmp31__length1 = 0;
				gint* _tmp32_ = NULL;
				gint _tmp32__length1 = 0;
				gint _tmp33_ = 0;
				gint _tmp34_ = 0;
				gint* _tmp35_ = NULL;
				gint _tmp35__length1 = 0;
				gint _tmp36_ = 0;
				gint _tmp37_ = 0;
				if (!_tmp28_) {
					gint _tmp29_ = 0;
					_tmp29_ = i;
					i = _tmp29_ + 1;
				}
				_tmp28_ = FALSE;
				_tmp30_ = i;
				_tmp31_ = pr2;
				_tmp31__length1 = pr2_length1;
				if (!(_tmp30_ < _tmp31__length1)) {
					break;
				}
				_tmp32_ = g;
				_tmp32__length1 = g_length1;
				_tmp33_ = i;
				_tmp34_ = _tmp32_[_tmp33_];
				_tmp35_ = pr1;
				_tmp35__length1 = pr1_length1;
				_tmp36_ = i;
				_tmp37_ = _tmp35_[_tmp36_];
				_vala_assert (_tmp34_ == _tmp37_, "g[i]==pr1[i]");
			}
		}
	}
	g = (g_free (g), NULL);
	f = (_vala_array_free (f, f_length1, (GDestroyNotify) g_free), NULL);
	pr2 = (_vala_array_free (pr2, pr2_length1, (GDestroyNotify) g_free), NULL);
	pr1 = (g_free (pr1), NULL);
}


static void cubo_genetico_test_test_codificacion_class_init (CuboGeneticoTestTestCodificacionClass * klass) {
	cubo_genetico_test_test_codificacion_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoTestTestCodificacionPrivate));
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_test_test_codificacion_finalize;
}


static void cubo_genetico_test_test_codificacion_instance_init (CuboGeneticoTestTestCodificacion * self) {
	self->priv = CUBO_GENETICO_TEST_TEST_CODIFICACION_GET_PRIVATE (self);
}


static void cubo_genetico_test_test_codificacion_finalize (GObject* obj) {
	CuboGeneticoTestTestCodificacion * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION, CuboGeneticoTestTestCodificacion);
	_g_object_unref0 (self->priv->c);
	G_OBJECT_CLASS (cubo_genetico_test_test_codificacion_parent_class)->finalize (obj);
}


/**
     * Test cases for {@link Cubo3x3}.
     */
GType cubo_genetico_test_test_codificacion_get_type (void) {
	static volatile gsize cubo_genetico_test_test_codificacion_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_test_test_codificacion_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoTestTestCodificacionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_test_test_codificacion_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoTestTestCodificacion), 0, (GInstanceInitFunc) cubo_genetico_test_test_codificacion_instance_init, NULL };
		GType cubo_genetico_test_test_codificacion_type_id;
		cubo_genetico_test_test_codificacion_type_id = g_type_register_static (CUBO_GENETICO_TEST_TYPE_TEST_CASE, "CuboGeneticoTestTestCodificacion", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_test_test_codificacion_type_id__volatile, cubo_genetico_test_test_codificacion_type_id);
	}
	return cubo_genetico_test_test_codificacion_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



