/* test-cubogenetico-main.c generated by valac 0.34.8, the Vala compiler
 * generated from test-cubogenetico-main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include "test.h"
#include <gobject/gvaluecollector.h>


#define CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN (cubo_genetico_test_test_cubo_genetico_main_get_type ())
#define CUBO_GENETICO_TEST_TEST_CUBO_GENETICO_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN, CuboGeneticoTestTestCuboGeneticoMain))
#define CUBO_GENETICO_TEST_TEST_CUBO_GENETICO_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN, CuboGeneticoTestTestCuboGeneticoMainClass))
#define CUBO_GENETICO_TEST_IS_TEST_CUBO_GENETICO_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN))
#define CUBO_GENETICO_TEST_IS_TEST_CUBO_GENETICO_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN))
#define CUBO_GENETICO_TEST_TEST_CUBO_GENETICO_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN, CuboGeneticoTestTestCuboGeneticoMainClass))

typedef struct _CuboGeneticoTestTestCuboGeneticoMain CuboGeneticoTestTestCuboGeneticoMain;
typedef struct _CuboGeneticoTestTestCuboGeneticoMainClass CuboGeneticoTestTestCuboGeneticoMainClass;
typedef struct _CuboGeneticoTestTestCuboGeneticoMainPrivate CuboGeneticoTestTestCuboGeneticoMainPrivate;

#define CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3 (cubo_genetico_test_test_cubo3x3_get_type ())
#define CUBO_GENETICO_TEST_TEST_CUBO3X3(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3, CuboGeneticoTestTestCubo3x3))
#define CUBO_GENETICO_TEST_TEST_CUBO3X3_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3, CuboGeneticoTestTestCubo3x3Class))
#define CUBO_GENETICO_TEST_IS_TEST_CUBO3X3(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3))
#define CUBO_GENETICO_TEST_IS_TEST_CUBO3X3_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3))
#define CUBO_GENETICO_TEST_TEST_CUBO3X3_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3, CuboGeneticoTestTestCubo3x3Class))

typedef struct _CuboGeneticoTestTestCubo3x3 CuboGeneticoTestTestCubo3x3;
typedef struct _CuboGeneticoTestTestCubo3x3Class CuboGeneticoTestTestCubo3x3Class;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION (cubo_genetico_test_test_codificacion_get_type ())
#define CUBO_GENETICO_TEST_TEST_CODIFICACION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION, CuboGeneticoTestTestCodificacion))
#define CUBO_GENETICO_TEST_TEST_CODIFICACION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION, CuboGeneticoTestTestCodificacionClass))
#define CUBO_GENETICO_TEST_IS_TEST_CODIFICACION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION))
#define CUBO_GENETICO_TEST_IS_TEST_CODIFICACION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION))
#define CUBO_GENETICO_TEST_TEST_CODIFICACION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CODIFICACION, CuboGeneticoTestTestCodificacionClass))

typedef struct _CuboGeneticoTestTestCodificacion CuboGeneticoTestTestCodificacion;
typedef struct _CuboGeneticoTestTestCodificacionClass CuboGeneticoTestTestCodificacionClass;
typedef struct _CuboGeneticoTestParamSpecTestCuboGeneticoMain CuboGeneticoTestParamSpecTestCuboGeneticoMain;

struct _CuboGeneticoTestTestCuboGeneticoMain {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CuboGeneticoTestTestCuboGeneticoMainPrivate * priv;
};

struct _CuboGeneticoTestTestCuboGeneticoMainClass {
	GTypeClass parent_class;
	void (*finalize) (CuboGeneticoTestTestCuboGeneticoMain *self);
};

struct _CuboGeneticoTestParamSpecTestCuboGeneticoMain {
	GParamSpec parent_instance;
};


static gpointer cubo_genetico_test_test_cubo_genetico_main_parent_class = NULL;

gpointer cubo_genetico_test_test_cubo_genetico_main_ref (gpointer instance);
void cubo_genetico_test_test_cubo_genetico_main_unref (gpointer instance);
GParamSpec* cubo_genetico_test_param_spec_test_cubo_genetico_main (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_test_value_set_test_cubo_genetico_main (GValue* value, gpointer v_object);
void cubo_genetico_test_value_take_test_cubo_genetico_main (GValue* value, gpointer v_object);
gpointer cubo_genetico_test_value_get_test_cubo_genetico_main (const GValue* value);
GType cubo_genetico_test_test_cubo_genetico_main_get_type (void) G_GNUC_CONST;
enum  {
	CUBO_GENETICO_TEST_TEST_CUBO_GENETICO_MAIN_DUMMY_PROPERTY
};
gint cubo_genetico_test_test_cubo_genetico_main_main (gchar** args, int args_length1);
CuboGeneticoTestTestCubo3x3* cubo_genetico_test_test_cubo3x3_new (void);
CuboGeneticoTestTestCubo3x3* cubo_genetico_test_test_cubo3x3_construct (GType object_type);
GType cubo_genetico_test_test_cubo3x3_get_type (void) G_GNUC_CONST;
CuboGeneticoTestTestCodificacion* cubo_genetico_test_test_codificacion_new (void);
CuboGeneticoTestTestCodificacion* cubo_genetico_test_test_codificacion_construct (GType object_type);
GType cubo_genetico_test_test_codificacion_get_type (void) G_GNUC_CONST;
CuboGeneticoTestTestCuboGeneticoMain* cubo_genetico_test_test_cubo_genetico_main_new (void);
CuboGeneticoTestTestCuboGeneticoMain* cubo_genetico_test_test_cubo_genetico_main_construct (GType object_type);
static void cubo_genetico_test_test_cubo_genetico_main_finalize (CuboGeneticoTestTestCuboGeneticoMain* obj);


gint cubo_genetico_test_test_cubo_genetico_main_main (gchar** args, int args_length1) {
	gint result = 0;
	GTestSuite* _tmp0_ = NULL;
	CuboGeneticoTestTestCubo3x3* _tmp1_ = NULL;
	CuboGeneticoTestTestCubo3x3* _tmp2_ = NULL;
	GTestSuite* _tmp3_ = NULL;
	GTestSuite* _tmp4_ = NULL;
	CuboGeneticoTestTestCodificacion* _tmp5_ = NULL;
	CuboGeneticoTestTestCodificacion* _tmp6_ = NULL;
	GTestSuite* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	g_test_init (&args_length1, &args, NULL);
	_tmp0_ = g_test_get_root ();
	_tmp1_ = cubo_genetico_test_test_cubo3x3_new ();
	_tmp2_ = _tmp1_;
	_tmp3_ = cubo_genetico_test_test_case_get_suite ((CuboGeneticoTestTestCase*) _tmp2_);
	g_test_suite_add_suite (_tmp0_, _tmp3_);
	_g_object_unref0 (_tmp2_);
	_tmp4_ = g_test_get_root ();
	_tmp5_ = cubo_genetico_test_test_codificacion_new ();
	_tmp6_ = _tmp5_;
	_tmp7_ = cubo_genetico_test_test_case_get_suite ((CuboGeneticoTestTestCase*) _tmp6_);
	g_test_suite_add_suite (_tmp4_, _tmp7_);
	_g_object_unref0 (_tmp6_);
	_tmp8_ = g_test_run ();
	result = _tmp8_;
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return cubo_genetico_test_test_cubo_genetico_main_main (argv, argc);
}


CuboGeneticoTestTestCuboGeneticoMain* cubo_genetico_test_test_cubo_genetico_main_construct (GType object_type) {
	CuboGeneticoTestTestCuboGeneticoMain* self = NULL;
	self = (CuboGeneticoTestTestCuboGeneticoMain*) g_type_create_instance (object_type);
	return self;
}


CuboGeneticoTestTestCuboGeneticoMain* cubo_genetico_test_test_cubo_genetico_main_new (void) {
	return cubo_genetico_test_test_cubo_genetico_main_construct (CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN);
}


static void cubo_genetico_test_value_test_cubo_genetico_main_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void cubo_genetico_test_value_test_cubo_genetico_main_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		cubo_genetico_test_test_cubo_genetico_main_unref (value->data[0].v_pointer);
	}
}


static void cubo_genetico_test_value_test_cubo_genetico_main_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = cubo_genetico_test_test_cubo_genetico_main_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer cubo_genetico_test_value_test_cubo_genetico_main_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* cubo_genetico_test_value_test_cubo_genetico_main_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		CuboGeneticoTestTestCuboGeneticoMain* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = cubo_genetico_test_test_cubo_genetico_main_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* cubo_genetico_test_value_test_cubo_genetico_main_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	CuboGeneticoTestTestCuboGeneticoMain** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = cubo_genetico_test_test_cubo_genetico_main_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* cubo_genetico_test_param_spec_test_cubo_genetico_main (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	CuboGeneticoTestParamSpecTestCuboGeneticoMain* spec;
	g_return_val_if_fail (g_type_is_a (object_type, CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer cubo_genetico_test_value_get_test_cubo_genetico_main (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN), NULL);
	return value->data[0].v_pointer;
}


void cubo_genetico_test_value_set_test_cubo_genetico_main (GValue* value, gpointer v_object) {
	CuboGeneticoTestTestCuboGeneticoMain* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		cubo_genetico_test_test_cubo_genetico_main_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_test_test_cubo_genetico_main_unref (old);
	}
}


void cubo_genetico_test_value_take_test_cubo_genetico_main (GValue* value, gpointer v_object) {
	CuboGeneticoTestTestCuboGeneticoMain* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_test_test_cubo_genetico_main_unref (old);
	}
}


static void cubo_genetico_test_test_cubo_genetico_main_class_init (CuboGeneticoTestTestCuboGeneticoMainClass * klass) {
	cubo_genetico_test_test_cubo_genetico_main_parent_class = g_type_class_peek_parent (klass);
	((CuboGeneticoTestTestCuboGeneticoMainClass *) klass)->finalize = cubo_genetico_test_test_cubo_genetico_main_finalize;
}


static void cubo_genetico_test_test_cubo_genetico_main_instance_init (CuboGeneticoTestTestCuboGeneticoMain * self) {
	self->ref_count = 1;
}


static void cubo_genetico_test_test_cubo_genetico_main_finalize (CuboGeneticoTestTestCuboGeneticoMain* obj) {
	CuboGeneticoTestTestCuboGeneticoMain * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TEST_TYPE_TEST_CUBO_GENETICO_MAIN, CuboGeneticoTestTestCuboGeneticoMain);
	g_signal_handlers_destroy (self);
}


GType cubo_genetico_test_test_cubo_genetico_main_get_type (void) {
	static volatile gsize cubo_genetico_test_test_cubo_genetico_main_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_test_test_cubo_genetico_main_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { cubo_genetico_test_value_test_cubo_genetico_main_init, cubo_genetico_test_value_test_cubo_genetico_main_free_value, cubo_genetico_test_value_test_cubo_genetico_main_copy_value, cubo_genetico_test_value_test_cubo_genetico_main_peek_pointer, "p", cubo_genetico_test_value_test_cubo_genetico_main_collect_value, "p", cubo_genetico_test_value_test_cubo_genetico_main_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoTestTestCuboGeneticoMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_test_test_cubo_genetico_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoTestTestCuboGeneticoMain), 0, (GInstanceInitFunc) cubo_genetico_test_test_cubo_genetico_main_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType cubo_genetico_test_test_cubo_genetico_main_type_id;
		cubo_genetico_test_test_cubo_genetico_main_type_id = g_type_register_fundamental (g_type_fundamental_next (), "CuboGeneticoTestTestCuboGeneticoMain", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&cubo_genetico_test_test_cubo_genetico_main_type_id__volatile, cubo_genetico_test_test_cubo_genetico_main_type_id);
	}
	return cubo_genetico_test_test_cubo_genetico_main_type_id__volatile;
}


gpointer cubo_genetico_test_test_cubo_genetico_main_ref (gpointer instance) {
	CuboGeneticoTestTestCuboGeneticoMain* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void cubo_genetico_test_test_cubo_genetico_main_unref (gpointer instance) {
	CuboGeneticoTestTestCuboGeneticoMain* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		CUBO_GENETICO_TEST_TEST_CUBO_GENETICO_MAIN_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



