/* test-cubo3x3.c generated by valac 0.34.8, the Vala compiler
 * generated from test-cubo3x3.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "test.h"
#include "cubo.h"


#define CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3 (cubo_genetico_test_test_cubo3x3_get_type ())
#define CUBO_GENETICO_TEST_TEST_CUBO3X3(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3, CuboGeneticoTestTestCubo3x3))
#define CUBO_GENETICO_TEST_TEST_CUBO3X3_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3, CuboGeneticoTestTestCubo3x3Class))
#define CUBO_GENETICO_TEST_IS_TEST_CUBO3X3(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3))
#define CUBO_GENETICO_TEST_IS_TEST_CUBO3X3_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3))
#define CUBO_GENETICO_TEST_TEST_CUBO3X3_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3, CuboGeneticoTestTestCubo3x3Class))

typedef struct _CuboGeneticoTestTestCubo3x3 CuboGeneticoTestTestCubo3x3;
typedef struct _CuboGeneticoTestTestCubo3x3Class CuboGeneticoTestTestCubo3x3Class;
typedef struct _CuboGeneticoTestTestCubo3x3Private CuboGeneticoTestTestCubo3x3Private;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _CuboGeneticoTestTestCubo3x3 {
	CuboGeneticoTestTestCase parent_instance;
	CuboGeneticoTestTestCubo3x3Private * priv;
};

struct _CuboGeneticoTestTestCubo3x3Class {
	CuboGeneticoTestTestCaseClass parent_class;
};

struct _CuboGeneticoTestTestCubo3x3Private {
	gint* cu;
	gint cu_length1;
	gint cu_length2;
};


static gpointer cubo_genetico_test_test_cubo3x3_parent_class = NULL;

GType cubo_genetico_test_test_cubo3x3_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_TEST_TEST_CUBO3X3_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3, CuboGeneticoTestTestCubo3x3Private))
enum  {
	CUBO_GENETICO_TEST_TEST_CUBO3X3_DUMMY_PROPERTY
};
CuboGeneticoTestTestCubo3x3* cubo_genetico_test_test_cubo3x3_new (void);
CuboGeneticoTestTestCubo3x3* cubo_genetico_test_test_cubo3x3_construct (GType object_type);
void cubo_genetico_test_test_cubo3x3_test_rrpuup (CuboGeneticoTestTestCubo3x3* self);
static void _cubo_genetico_test_test_cubo3x3_test_rrpuup_cubo_genetico_test_test_case_test_method (gpointer self);
void cubo_genetico_test_test_cubo3x3_test_llpddp (CuboGeneticoTestTestCubo3x3* self);
static void _cubo_genetico_test_test_cubo3x3_test_llpddp_cubo_genetico_test_test_case_test_method (gpointer self);
static void cubo_genetico_test_test_cubo3x3_finalize (GObject* obj);


static void _cubo_genetico_test_test_cubo3x3_test_rrpuup_cubo_genetico_test_test_case_test_method (gpointer self) {
	cubo_genetico_test_test_cubo3x3_test_rrpuup ((CuboGeneticoTestTestCubo3x3*) self);
}


static void _cubo_genetico_test_test_cubo3x3_test_llpddp_cubo_genetico_test_test_case_test_method (gpointer self) {
	cubo_genetico_test_test_cubo3x3_test_llpddp ((CuboGeneticoTestTestCubo3x3*) self);
}


CuboGeneticoTestTestCubo3x3* cubo_genetico_test_test_cubo3x3_construct (GType object_type) {
	CuboGeneticoTestTestCubo3x3 * self = NULL;
	gint* _tmp0_ = NULL;
	self = (CuboGeneticoTestTestCubo3x3*) cubo_genetico_test_test_case_construct (object_type, "TestCubo3x3");
	cubo_genetico_test_test_case_add_test ((CuboGeneticoTestTestCase*) self, "test_rrpuup", _cubo_genetico_test_test_cubo3x3_test_rrpuup_cubo_genetico_test_test_case_test_method, g_object_ref (self), g_object_unref);
	cubo_genetico_test_test_case_add_test ((CuboGeneticoTestTestCase*) self, "test_llpddp", _cubo_genetico_test_test_cubo3x3_test_llpddp_cubo_genetico_test_test_case_test_method, g_object_ref (self), g_object_unref);
	_tmp0_ = g_new0 (gint, 6 * 9);
	self->priv->cu = (g_free (self->priv->cu), NULL);
	self->priv->cu = _tmp0_;
	self->priv->cu_length1 = 6;
	self->priv->cu_length2 = 9;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp1_ = FALSE;
			_tmp1_ = TRUE;
			while (TRUE) {
				gint _tmp3_ = 0;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp1_ = FALSE;
				_tmp3_ = i;
				if (!(_tmp3_ < 6)) {
					break;
				}
				{
					gint j = 0;
					j = 0;
					{
						gboolean _tmp4_ = FALSE;
						_tmp4_ = TRUE;
						while (TRUE) {
							gint _tmp6_ = 0;
							gint _tmp7_ = 0;
							if (!_tmp4_) {
								gint _tmp5_ = 0;
								_tmp5_ = j;
								j = _tmp5_ + 1;
							}
							_tmp4_ = FALSE;
							_tmp6_ = j;
							if (!(_tmp6_ < 9)) {
								break;
							}
							_tmp7_ = i;
							if (_tmp7_ < 3) {
								gint _tmp8_ = 0;
								_tmp8_ = j;
								if (_tmp8_ < 3) {
									gint* _tmp9_ = NULL;
									gint _tmp9__length1 = 0;
									gint _tmp9__length2 = 0;
									gint _tmp10_ = 0;
									gint _tmp11_ = 0;
									gint _tmp12_ = 0;
									_tmp9_ = self->priv->cu;
									_tmp9__length1 = self->priv->cu_length1;
									_tmp9__length2 = self->priv->cu_length2;
									_tmp10_ = i;
									_tmp11_ = j;
									_tmp9_[(_tmp10_ * _tmp9__length2) + _tmp11_] = 0;
									_tmp12_ = _tmp9_[(_tmp10_ * _tmp9__length2) + _tmp11_];
								} else {
									gint _tmp13_ = 0;
									_tmp13_ = j;
									if (_tmp13_ < 6) {
										gint* _tmp14_ = NULL;
										gint _tmp14__length1 = 0;
										gint _tmp14__length2 = 0;
										gint _tmp15_ = 0;
										gint _tmp16_ = 0;
										gint _tmp17_ = 0;
										_tmp14_ = self->priv->cu;
										_tmp14__length1 = self->priv->cu_length1;
										_tmp14__length2 = self->priv->cu_length2;
										_tmp15_ = i;
										_tmp16_ = j;
										_tmp14_[(_tmp15_ * _tmp14__length2) + _tmp16_] = 1;
										_tmp17_ = _tmp14_[(_tmp15_ * _tmp14__length2) + _tmp16_];
									} else {
										gint _tmp18_ = 0;
										_tmp18_ = j;
										if (_tmp18_ < 9) {
											gint* _tmp19_ = NULL;
											gint _tmp19__length1 = 0;
											gint _tmp19__length2 = 0;
											gint _tmp20_ = 0;
											gint _tmp21_ = 0;
											gint _tmp22_ = 0;
											_tmp19_ = self->priv->cu;
											_tmp19__length1 = self->priv->cu_length1;
											_tmp19__length2 = self->priv->cu_length2;
											_tmp20_ = i;
											_tmp21_ = j;
											_tmp19_[(_tmp20_ * _tmp19__length2) + _tmp21_] = 2;
											_tmp22_ = _tmp19_[(_tmp20_ * _tmp19__length2) + _tmp21_];
										}
									}
								}
							} else {
								gint _tmp23_ = 0;
								_tmp23_ = i;
								if (_tmp23_ < 6) {
									gint _tmp24_ = 0;
									_tmp24_ = j;
									if (_tmp24_ < 3) {
										gint* _tmp25_ = NULL;
										gint _tmp25__length1 = 0;
										gint _tmp25__length2 = 0;
										gint _tmp26_ = 0;
										gint _tmp27_ = 0;
										gint _tmp28_ = 0;
										_tmp25_ = self->priv->cu;
										_tmp25__length1 = self->priv->cu_length1;
										_tmp25__length2 = self->priv->cu_length2;
										_tmp26_ = i;
										_tmp27_ = j;
										_tmp25_[(_tmp26_ * _tmp25__length2) + _tmp27_] = 3;
										_tmp28_ = _tmp25_[(_tmp26_ * _tmp25__length2) + _tmp27_];
									} else {
										gint _tmp29_ = 0;
										_tmp29_ = j;
										if (_tmp29_ < 6) {
											gint* _tmp30_ = NULL;
											gint _tmp30__length1 = 0;
											gint _tmp30__length2 = 0;
											gint _tmp31_ = 0;
											gint _tmp32_ = 0;
											gint _tmp33_ = 0;
											_tmp30_ = self->priv->cu;
											_tmp30__length1 = self->priv->cu_length1;
											_tmp30__length2 = self->priv->cu_length2;
											_tmp31_ = i;
											_tmp32_ = j;
											_tmp30_[(_tmp31_ * _tmp30__length2) + _tmp32_] = 4;
											_tmp33_ = _tmp30_[(_tmp31_ * _tmp30__length2) + _tmp32_];
										} else {
											gint _tmp34_ = 0;
											_tmp34_ = j;
											if (_tmp34_ < 9) {
												gint* _tmp35_ = NULL;
												gint _tmp35__length1 = 0;
												gint _tmp35__length2 = 0;
												gint _tmp36_ = 0;
												gint _tmp37_ = 0;
												gint _tmp38_ = 0;
												_tmp35_ = self->priv->cu;
												_tmp35__length1 = self->priv->cu_length1;
												_tmp35__length2 = self->priv->cu_length2;
												_tmp36_ = i;
												_tmp37_ = j;
												_tmp35_[(_tmp36_ * _tmp35__length2) + _tmp37_] = 5;
												_tmp38_ = _tmp35_[(_tmp36_ * _tmp35__length2) + _tmp37_];
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	return self;
}


CuboGeneticoTestTestCubo3x3* cubo_genetico_test_test_cubo3x3_new (void) {
	return cubo_genetico_test_test_cubo3x3_construct (CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3);
}


void cubo_genetico_test_test_cubo3x3_test_rrpuup (CuboGeneticoTestTestCubo3x3* self) {
	CuboGeneticoCuboCubo3x3* c = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp0__length2 = 0;
	CuboGeneticoCuboCubo3x3* _tmp1_ = NULL;
	gint* g = NULL;
	gint* _tmp2_ = NULL;
	gint g_length1 = 0;
	gint _g_size_ = 0;
	CuboGeneticoCuboCubo3x3* _tmp3_ = NULL;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	gint* act = NULL;
	CuboGeneticoCuboCubo3x3* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint* _tmp8_ = NULL;
	gint act_length1 = 0;
	gint act_length2 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->cu;
	_tmp0__length1 = self->priv->cu_length1;
	_tmp0__length2 = self->priv->cu_length2;
	_tmp1_ = cubo_genetico_cubo_cubo3x3_new (_tmp0_, _tmp0__length1, _tmp0__length2);
	c = _tmp1_;
	_tmp2_ = g_new0 (gint, 24);
	_tmp2_[0] = 1;
	_tmp2_[1] = 5;
	_tmp2_[2] = 2;
	_tmp2_[3] = 6;
	_tmp2_[4] = 1;
	_tmp2_[5] = 5;
	_tmp2_[6] = 2;
	_tmp2_[7] = 6;
	_tmp2_[8] = 1;
	_tmp2_[9] = 5;
	_tmp2_[10] = 2;
	_tmp2_[11] = 6;
	_tmp2_[12] = 1;
	_tmp2_[13] = 5;
	_tmp2_[14] = 2;
	_tmp2_[15] = 6;
	_tmp2_[16] = 1;
	_tmp2_[17] = 5;
	_tmp2_[18] = 2;
	_tmp2_[19] = 6;
	_tmp2_[20] = 1;
	_tmp2_[21] = 5;
	_tmp2_[22] = 2;
	_tmp2_[23] = 6;
	g = _tmp2_;
	g_length1 = 24;
	_g_size_ = g_length1;
	_tmp3_ = c;
	_tmp4_ = g;
	_tmp4__length1 = g_length1;
	cubo_genetico_cubo_cubo3x3_giraCaras (_tmp3_, _tmp4_, _tmp4__length1);
	_tmp5_ = c;
	_tmp8_ = cubo_genetico_cubo_cubo3x3_getActual (_tmp5_, &_tmp6_, &_tmp7_);
	act = _tmp8_;
	act_length1 = _tmp6_;
	act_length2 = _tmp7_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp9_ = FALSE;
			_tmp9_ = TRUE;
			while (TRUE) {
				gint _tmp11_ = 0;
				if (!_tmp9_) {
					gint _tmp10_ = 0;
					_tmp10_ = i;
					i = _tmp10_ + 1;
				}
				_tmp9_ = FALSE;
				_tmp11_ = i;
				if (!(_tmp11_ < 6)) {
					break;
				}
				{
					gint j = 0;
					j = 0;
					{
						gboolean _tmp12_ = FALSE;
						_tmp12_ = TRUE;
						while (TRUE) {
							gint _tmp14_ = 0;
							gint* _tmp15_ = NULL;
							gint _tmp15__length1 = 0;
							gint _tmp15__length2 = 0;
							gint _tmp16_ = 0;
							gint _tmp17_ = 0;
							gint _tmp18_ = 0;
							gint* _tmp19_ = NULL;
							gint _tmp19__length1 = 0;
							gint _tmp19__length2 = 0;
							gint _tmp20_ = 0;
							gint _tmp21_ = 0;
							gint _tmp22_ = 0;
							if (!_tmp12_) {
								gint _tmp13_ = 0;
								_tmp13_ = j;
								j = _tmp13_ + 1;
							}
							_tmp12_ = FALSE;
							_tmp14_ = j;
							if (!(_tmp14_ < 9)) {
								break;
							}
							_tmp15_ = act;
							_tmp15__length1 = act_length1;
							_tmp15__length2 = act_length2;
							_tmp16_ = i;
							_tmp17_ = j;
							_tmp18_ = _tmp15_[(_tmp16_ * _tmp15__length2) + _tmp17_];
							_tmp19_ = self->priv->cu;
							_tmp19__length1 = self->priv->cu_length1;
							_tmp19__length2 = self->priv->cu_length2;
							_tmp20_ = i;
							_tmp21_ = j;
							_tmp22_ = _tmp19_[(_tmp20_ * _tmp19__length2) + _tmp21_];
							_vala_assert (_tmp18_ == _tmp22_, "act[i,j]==this.cu[i,j]");
						}
					}
				}
			}
		}
	}
	act = (g_free (act), NULL);
	g = (g_free (g), NULL);
	_g_object_unref0 (c);
}


void cubo_genetico_test_test_cubo3x3_test_llpddp (CuboGeneticoTestTestCubo3x3* self) {
	CuboGeneticoCuboCubo3x3* c = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint _tmp0__length2 = 0;
	CuboGeneticoCuboCubo3x3* _tmp1_ = NULL;
	gint* g = NULL;
	gint* _tmp2_ = NULL;
	gint g_length1 = 0;
	gint _g_size_ = 0;
	CuboGeneticoCuboCubo3x3* _tmp3_ = NULL;
	gint* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	gint* act = NULL;
	CuboGeneticoCuboCubo3x3* _tmp5_ = NULL;
	gint _tmp6_ = 0;
	gint _tmp7_ = 0;
	gint* _tmp8_ = NULL;
	gint act_length1 = 0;
	gint act_length2 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->cu;
	_tmp0__length1 = self->priv->cu_length1;
	_tmp0__length2 = self->priv->cu_length2;
	_tmp1_ = cubo_genetico_cubo_cubo3x3_new (_tmp0_, _tmp0__length1, _tmp0__length2);
	c = _tmp1_;
	_tmp2_ = g_new0 (gint, 24);
	_tmp2_[0] = 3;
	_tmp2_[1] = 7;
	_tmp2_[2] = 4;
	_tmp2_[3] = 8;
	_tmp2_[4] = 3;
	_tmp2_[5] = 7;
	_tmp2_[6] = 4;
	_tmp2_[7] = 8;
	_tmp2_[8] = 3;
	_tmp2_[9] = 7;
	_tmp2_[10] = 4;
	_tmp2_[11] = 8;
	_tmp2_[12] = 3;
	_tmp2_[13] = 7;
	_tmp2_[14] = 4;
	_tmp2_[15] = 8;
	_tmp2_[16] = 3;
	_tmp2_[17] = 7;
	_tmp2_[18] = 4;
	_tmp2_[19] = 8;
	_tmp2_[20] = 3;
	_tmp2_[21] = 7;
	_tmp2_[22] = 4;
	_tmp2_[23] = 8;
	g = _tmp2_;
	g_length1 = 24;
	_g_size_ = g_length1;
	_tmp3_ = c;
	_tmp4_ = g;
	_tmp4__length1 = g_length1;
	cubo_genetico_cubo_cubo3x3_giraCaras (_tmp3_, _tmp4_, _tmp4__length1);
	_tmp5_ = c;
	_tmp8_ = cubo_genetico_cubo_cubo3x3_getActual (_tmp5_, &_tmp6_, &_tmp7_);
	act = _tmp8_;
	act_length1 = _tmp6_;
	act_length2 = _tmp7_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp9_ = FALSE;
			_tmp9_ = TRUE;
			while (TRUE) {
				gint _tmp11_ = 0;
				if (!_tmp9_) {
					gint _tmp10_ = 0;
					_tmp10_ = i;
					i = _tmp10_ + 1;
				}
				_tmp9_ = FALSE;
				_tmp11_ = i;
				if (!(_tmp11_ < 6)) {
					break;
				}
				{
					gint j = 0;
					j = 0;
					{
						gboolean _tmp12_ = FALSE;
						_tmp12_ = TRUE;
						while (TRUE) {
							gint _tmp14_ = 0;
							gint* _tmp15_ = NULL;
							gint _tmp15__length1 = 0;
							gint _tmp15__length2 = 0;
							gint _tmp16_ = 0;
							gint _tmp17_ = 0;
							gint _tmp18_ = 0;
							gint* _tmp19_ = NULL;
							gint _tmp19__length1 = 0;
							gint _tmp19__length2 = 0;
							gint _tmp20_ = 0;
							gint _tmp21_ = 0;
							gint _tmp22_ = 0;
							if (!_tmp12_) {
								gint _tmp13_ = 0;
								_tmp13_ = j;
								j = _tmp13_ + 1;
							}
							_tmp12_ = FALSE;
							_tmp14_ = j;
							if (!(_tmp14_ < 9)) {
								break;
							}
							_tmp15_ = act;
							_tmp15__length1 = act_length1;
							_tmp15__length2 = act_length2;
							_tmp16_ = i;
							_tmp17_ = j;
							_tmp18_ = _tmp15_[(_tmp16_ * _tmp15__length2) + _tmp17_];
							_tmp19_ = self->priv->cu;
							_tmp19__length1 = self->priv->cu_length1;
							_tmp19__length2 = self->priv->cu_length2;
							_tmp20_ = i;
							_tmp21_ = j;
							_tmp22_ = _tmp19_[(_tmp20_ * _tmp19__length2) + _tmp21_];
							_vala_assert (_tmp18_ == _tmp22_, "act[i,j]==this.cu[i,j]");
						}
					}
				}
			}
		}
	}
	act = (g_free (act), NULL);
	g = (g_free (g), NULL);
	_g_object_unref0 (c);
}


static void cubo_genetico_test_test_cubo3x3_class_init (CuboGeneticoTestTestCubo3x3Class * klass) {
	cubo_genetico_test_test_cubo3x3_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoTestTestCubo3x3Private));
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_test_test_cubo3x3_finalize;
}


static void cubo_genetico_test_test_cubo3x3_instance_init (CuboGeneticoTestTestCubo3x3 * self) {
	self->priv = CUBO_GENETICO_TEST_TEST_CUBO3X3_GET_PRIVATE (self);
}


static void cubo_genetico_test_test_cubo3x3_finalize (GObject* obj) {
	CuboGeneticoTestTestCubo3x3 * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TEST_TYPE_TEST_CUBO3X3, CuboGeneticoTestTestCubo3x3);
	self->priv->cu = (g_free (self->priv->cu), NULL);
	G_OBJECT_CLASS (cubo_genetico_test_test_cubo3x3_parent_class)->finalize (obj);
}


/**
     * Test cases for {@link Cubo3x3}.
     */
GType cubo_genetico_test_test_cubo3x3_get_type (void) {
	static volatile gsize cubo_genetico_test_test_cubo3x3_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_test_test_cubo3x3_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoTestTestCubo3x3Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_test_test_cubo3x3_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoTestTestCubo3x3), 0, (GInstanceInitFunc) cubo_genetico_test_test_cubo3x3_instance_init, NULL };
		GType cubo_genetico_test_test_cubo3x3_type_id;
		cubo_genetico_test_test_cubo3x3_type_id = g_type_register_static (CUBO_GENETICO_TEST_TYPE_TEST_CASE, "CuboGeneticoTestTestCubo3x3", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_test_test_cubo3x3_type_id__volatile, cubo_genetico_test_test_cubo3x3_type_id);
	}
	return cubo_genetico_test_test_cubo3x3_type_id__volatile;
}



