/* codificacion.h generated by valac 0.34.8, the Vala compiler, do not modify */


#ifndef __LIB_CODIFICACION_CODIFICACION_H__
#define __LIB_CODIFICACION_CODIFICACION_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define CUBO_GENETICO_CODIFICACION_TYPE_FENO_GENO (cubo_genetico_codificacion_feno_geno_get_type ())
#define CUBO_GENETICO_CODIFICACION_FENO_GENO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_CODIFICACION_TYPE_FENO_GENO, CuboGeneticoCodificacionFenoGeno))
#define CUBO_GENETICO_CODIFICACION_FENO_GENO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_CODIFICACION_TYPE_FENO_GENO, CuboGeneticoCodificacionFenoGenoClass))
#define CUBO_GENETICO_CODIFICACION_IS_FENO_GENO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_CODIFICACION_TYPE_FENO_GENO))
#define CUBO_GENETICO_CODIFICACION_IS_FENO_GENO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_CODIFICACION_TYPE_FENO_GENO))
#define CUBO_GENETICO_CODIFICACION_FENO_GENO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_CODIFICACION_TYPE_FENO_GENO, CuboGeneticoCodificacionFenoGenoClass))

typedef struct _CuboGeneticoCodificacionFenoGeno CuboGeneticoCodificacionFenoGeno;
typedef struct _CuboGeneticoCodificacionFenoGenoClass CuboGeneticoCodificacionFenoGenoClass;
typedef struct _CuboGeneticoCodificacionFenoGenoPrivate CuboGeneticoCodificacionFenoGenoPrivate;

struct _CuboGeneticoCodificacionFenoGeno {
	GObject parent_instance;
	CuboGeneticoCodificacionFenoGenoPrivate * priv;
};

struct _CuboGeneticoCodificacionFenoGenoClass {
	GObjectClass parent_class;
};


GType cubo_genetico_codificacion_feno_geno_get_type (void) G_GNUC_CONST;
CuboGeneticoCodificacionFenoGeno* cubo_genetico_codificacion_feno_geno_new (gint semilla);
CuboGeneticoCodificacionFenoGeno* cubo_genetico_codificacion_feno_geno_construct (GType object_type, gint semilla);
gint* cubo_genetico_codificacion_feno_geno_codifica (CuboGeneticoCodificacionFenoGeno* self, gchar** feno, int feno_length1, int* result_length1);
gchar** cubo_genetico_codificacion_feno_geno_decodifica (CuboGeneticoCodificacionFenoGeno* self, gint* geno, int geno_length1, int* result_length1);
gint* cubo_genetico_codificacion_feno_geno_genoAleatNuev (CuboGeneticoCodificacionFenoGeno* self, gint n, int* result_length1);


G_END_DECLS

#endif
