/* cubo.vapi generated by valac 0.34.8, do not modify. */

namespace CuboGenetico {
	namespace Cubo {
		[CCode (cheader_filename = "cubo.h")]
		public class Cubo3x3 : GLib.Object {
			public Cubo3x3 (int[,] cubo);
			public void b ();
			public void bprima ();
			public void d ();
			public void dibuja ();
			public void dprima ();
			public void f ();
			public void fprima ();
			public void l ();
			public void lprima ();
			public void r ();
			public void rprima ();
			public void to_string ();
			public void u ();
			public void uprima ();
		}
	}
}
