/* test.vapi generated by valac 0.34.8, do not modify. */

namespace Aumbrales {
	namespace Test {
		[CCode (cheader_filename = "test.h")]
		public abstract class TestCase : GLib.Object {
			public delegate void TestMethod ();
			public TestCase (string name);
			public void add_test (string name, owned Aumbrales.Test.TestCase.TestMethod test);
			public GLib.TestSuite get_suite ();
			public virtual void set_up ();
			public virtual void tear_down ();
		}
	}
}
