/* Corrector.c generated by valac 0.34.8, the Vala compiler
 * generated from Corrector.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "agenetico.h"


#define CUBO_GENETICO_TYPE_CORRECTOR (cubo_genetico_corrector_get_type ())
#define CUBO_GENETICO_CORRECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_CORRECTOR, CuboGeneticoCorrector))
#define CUBO_GENETICO_CORRECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_CORRECTOR, CuboGeneticoCorrectorClass))
#define CUBO_GENETICO_IS_CORRECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_CORRECTOR))
#define CUBO_GENETICO_IS_CORRECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_CORRECTOR))
#define CUBO_GENETICO_CORRECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_CORRECTOR, CuboGeneticoCorrectorClass))

typedef struct _CuboGeneticoCorrector CuboGeneticoCorrector;
typedef struct _CuboGeneticoCorrectorClass CuboGeneticoCorrectorClass;
typedef struct _CuboGeneticoCorrectorPrivate CuboGeneticoCorrectorPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))
#define _cubo_genetico_agenetico_genotipo_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_agenetico_genotipo_unref (var), NULL)))

struct _CuboGeneticoCorrector {
	GObject parent_instance;
	CuboGeneticoCorrectorPrivate * priv;
};

struct _CuboGeneticoCorrectorClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoCorrectorPrivate {
	GRand* rand;
};


static gpointer cubo_genetico_corrector_parent_class = NULL;

GType cubo_genetico_corrector_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_CORRECTOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_CORRECTOR, CuboGeneticoCorrectorPrivate))
enum  {
	CUBO_GENETICO_CORRECTOR_DUMMY_PROPERTY
};
CuboGeneticoCorrector* cubo_genetico_corrector_new (gint semilla);
CuboGeneticoCorrector* cubo_genetico_corrector_construct (GType object_type, gint semilla);
CuboGeneticoAGeneticoGenotipo* cubo_genetico_corrector_reparaG (CuboGeneticoCorrector* self, CuboGeneticoAGeneticoGenotipo* gene);
static gboolean cubo_genetico_corrector_sonInv (CuboGeneticoCorrector* self, gint x, gint y);
static void cubo_genetico_corrector_finalize (GObject* obj);


CuboGeneticoCorrector* cubo_genetico_corrector_construct (GType object_type, gint semilla) {
	CuboGeneticoCorrector * self = NULL;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	self = (CuboGeneticoCorrector*) g_object_new (object_type, NULL);
	_tmp0_ = g_rand_new ();
	_g_rand_free0 (self->priv->rand);
	self->priv->rand = _tmp0_;
	_tmp1_ = self->priv->rand;
	_tmp2_ = semilla;
	g_rand_set_seed (_tmp1_, (guint32) _tmp2_);
	return self;
}


CuboGeneticoCorrector* cubo_genetico_corrector_new (gint semilla) {
	return cubo_genetico_corrector_construct (CUBO_GENETICO_TYPE_CORRECTOR, semilla);
}


CuboGeneticoAGeneticoGenotipo* cubo_genetico_corrector_reparaG (CuboGeneticoCorrector* self, CuboGeneticoAGeneticoGenotipo* gene) {
	CuboGeneticoAGeneticoGenotipo* result = NULL;
	gint len = 0;
	CuboGeneticoAGeneticoGenotipo* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	CuboGeneticoAGeneticoGenotipo* ngene = NULL;
	gint _tmp3_ = 0;
	CuboGeneticoAGeneticoGenotipo* _tmp4_ = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp37_ = NULL;
	gint* _tmp38_ = NULL;
	gint _tmp38__length1 = 0;
	gint* _tmp39_ = NULL;
	gint _tmp39__length1 = 0;
	gint _tmp40_ = 0;
	CuboGeneticoAGeneticoGenotipo* _tmp41_ = NULL;
	gint* _tmp42_ = NULL;
	gint _tmp42__length1 = 0;
	gint* _tmp43_ = NULL;
	gint _tmp43__length1 = 0;
	gint _tmp44_ = 0;
	gint _tmp45_ = 0;
	gint _tmp46_ = 0;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (gene != NULL, NULL);
	_tmp0_ = gene;
	_tmp1_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp0_, &_tmp1__length1);
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	len = _tmp2__length1;
	_tmp3_ = len;
	_tmp4_ = cubo_genetico_agenetico_genotipo_new (_tmp3_);
	ngene = _tmp4_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp5_ = FALSE;
			_tmp5_ = TRUE;
			while (TRUE) {
				gint _tmp7_ = 0;
				gint _tmp8_ = 0;
				CuboGeneticoAGeneticoGenotipo* _tmp9_ = NULL;
				gint* _tmp10_ = NULL;
				gint _tmp10__length1 = 0;
				gint* _tmp11_ = NULL;
				gint _tmp11__length1 = 0;
				gint _tmp12_ = 0;
				gint _tmp13_ = 0;
				CuboGeneticoAGeneticoGenotipo* _tmp14_ = NULL;
				gint* _tmp15_ = NULL;
				gint _tmp15__length1 = 0;
				gint* _tmp16_ = NULL;
				gint _tmp16__length1 = 0;
				gint _tmp17_ = 0;
				gint _tmp18_ = 0;
				gboolean _tmp19_ = FALSE;
				if (!_tmp5_) {
					gint _tmp6_ = 0;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp5_ = FALSE;
				_tmp7_ = i;
				_tmp8_ = len;
				if (!(_tmp7_ < (_tmp8_ - 1))) {
					break;
				}
				_tmp9_ = gene;
				_tmp10_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp9_, &_tmp10__length1);
				_tmp11_ = _tmp10_;
				_tmp11__length1 = _tmp10__length1;
				_tmp12_ = i;
				_tmp13_ = _tmp11_[_tmp12_];
				_tmp14_ = gene;
				_tmp15_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp14_, &_tmp15__length1);
				_tmp16_ = _tmp15_;
				_tmp16__length1 = _tmp15__length1;
				_tmp17_ = i;
				_tmp18_ = _tmp16_[_tmp17_ + 1];
				_tmp19_ = cubo_genetico_corrector_sonInv (self, _tmp13_, _tmp18_);
				if (_tmp19_) {
					CuboGeneticoAGeneticoGenotipo* _tmp20_ = NULL;
					gint* _tmp21_ = NULL;
					gint _tmp21__length1 = 0;
					gint* _tmp22_ = NULL;
					gint _tmp22__length1 = 0;
					gint _tmp23_ = 0;
					GRand* _tmp24_ = NULL;
					gint32 _tmp25_ = 0;
					gint _tmp26_ = 0;
					_tmp20_ = ngene;
					_tmp21_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp20_, &_tmp21__length1);
					_tmp22_ = _tmp21_;
					_tmp22__length1 = _tmp21__length1;
					_tmp23_ = i;
					_tmp24_ = self->priv->rand;
					_tmp25_ = g_rand_int_range (_tmp24_, (gint32) 1, (gint32) 13);
					_tmp22_[_tmp23_] = (gint) _tmp25_;
					_tmp26_ = _tmp22_[_tmp23_];
				} else {
					CuboGeneticoAGeneticoGenotipo* _tmp27_ = NULL;
					gint* _tmp28_ = NULL;
					gint _tmp28__length1 = 0;
					gint* _tmp29_ = NULL;
					gint _tmp29__length1 = 0;
					gint _tmp30_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp31_ = NULL;
					gint* _tmp32_ = NULL;
					gint _tmp32__length1 = 0;
					gint* _tmp33_ = NULL;
					gint _tmp33__length1 = 0;
					gint _tmp34_ = 0;
					gint _tmp35_ = 0;
					gint _tmp36_ = 0;
					_tmp27_ = ngene;
					_tmp28_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp27_, &_tmp28__length1);
					_tmp29_ = _tmp28_;
					_tmp29__length1 = _tmp28__length1;
					_tmp30_ = i;
					_tmp31_ = gene;
					_tmp32_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp31_, &_tmp32__length1);
					_tmp33_ = _tmp32_;
					_tmp33__length1 = _tmp32__length1;
					_tmp34_ = i;
					_tmp35_ = _tmp33_[_tmp34_];
					_tmp29_[_tmp30_] = _tmp35_;
					_tmp36_ = _tmp29_[_tmp30_];
				}
			}
		}
	}
	_tmp37_ = ngene;
	_tmp38_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp37_, &_tmp38__length1);
	_tmp39_ = _tmp38_;
	_tmp39__length1 = _tmp38__length1;
	_tmp40_ = len;
	_tmp41_ = gene;
	_tmp42_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp41_, &_tmp42__length1);
	_tmp43_ = _tmp42_;
	_tmp43__length1 = _tmp42__length1;
	_tmp44_ = len;
	_tmp45_ = _tmp43_[_tmp44_ - 1];
	_tmp39_[_tmp40_ - 1] = _tmp45_;
	_tmp46_ = _tmp39_[_tmp40_ - 1];
	result = ngene;
	return result;
}


static gboolean cubo_genetico_corrector_sonInv (CuboGeneticoCorrector* self, gint x, gint y) {
	gboolean result = FALSE;
	gboolean inv = FALSE;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	inv = FALSE;
	_tmp2_ = x;
	if (_tmp2_ == 1) {
		gint _tmp3_ = 0;
		_tmp3_ = y;
		_tmp1_ = _tmp3_ == 2;
	} else {
		_tmp1_ = FALSE;
	}
	if (_tmp1_) {
		_tmp0_ = TRUE;
	} else {
		gboolean _tmp4_ = FALSE;
		gint _tmp5_ = 0;
		_tmp5_ = x;
		if (_tmp5_ == 2) {
			gint _tmp6_ = 0;
			_tmp6_ = y;
			_tmp4_ = _tmp6_ == 1;
		} else {
			_tmp4_ = FALSE;
		}
		_tmp0_ = _tmp4_;
	}
	if (_tmp0_) {
		inv = TRUE;
	} else {
		gboolean _tmp7_ = FALSE;
		gboolean _tmp8_ = FALSE;
		gint _tmp9_ = 0;
		_tmp9_ = x;
		if (_tmp9_ == 3) {
			gint _tmp10_ = 0;
			_tmp10_ = y;
			_tmp8_ = _tmp10_ == 4;
		} else {
			_tmp8_ = FALSE;
		}
		if (_tmp8_) {
			_tmp7_ = TRUE;
		} else {
			gboolean _tmp11_ = FALSE;
			gint _tmp12_ = 0;
			_tmp12_ = x;
			if (_tmp12_ == 4) {
				gint _tmp13_ = 0;
				_tmp13_ = y;
				_tmp11_ = _tmp13_ == 3;
			} else {
				_tmp11_ = FALSE;
			}
			_tmp7_ = _tmp11_;
		}
		if (_tmp7_) {
			inv = TRUE;
		} else {
			gboolean _tmp14_ = FALSE;
			gboolean _tmp15_ = FALSE;
			gint _tmp16_ = 0;
			_tmp16_ = x;
			if (_tmp16_ == 5) {
				gint _tmp17_ = 0;
				_tmp17_ = y;
				_tmp15_ = _tmp17_ == 6;
			} else {
				_tmp15_ = FALSE;
			}
			if (_tmp15_) {
				_tmp14_ = TRUE;
			} else {
				gboolean _tmp18_ = FALSE;
				gint _tmp19_ = 0;
				_tmp19_ = x;
				if (_tmp19_ == 6) {
					gint _tmp20_ = 0;
					_tmp20_ = y;
					_tmp18_ = _tmp20_ == 5;
				} else {
					_tmp18_ = FALSE;
				}
				_tmp14_ = _tmp18_;
			}
			if (_tmp14_) {
				inv = TRUE;
			} else {
				gboolean _tmp21_ = FALSE;
				gboolean _tmp22_ = FALSE;
				gint _tmp23_ = 0;
				_tmp23_ = x;
				if (_tmp23_ == 7) {
					gint _tmp24_ = 0;
					_tmp24_ = y;
					_tmp22_ = _tmp24_ == 8;
				} else {
					_tmp22_ = FALSE;
				}
				if (_tmp22_) {
					_tmp21_ = TRUE;
				} else {
					gboolean _tmp25_ = FALSE;
					gint _tmp26_ = 0;
					_tmp26_ = x;
					if (_tmp26_ == 8) {
						gint _tmp27_ = 0;
						_tmp27_ = y;
						_tmp25_ = _tmp27_ == 7;
					} else {
						_tmp25_ = FALSE;
					}
					_tmp21_ = _tmp25_;
				}
				if (_tmp21_) {
					inv = TRUE;
				} else {
					gboolean _tmp28_ = FALSE;
					gboolean _tmp29_ = FALSE;
					gint _tmp30_ = 0;
					_tmp30_ = x;
					if (_tmp30_ == 9) {
						gint _tmp31_ = 0;
						_tmp31_ = y;
						_tmp29_ = _tmp31_ == 10;
					} else {
						_tmp29_ = FALSE;
					}
					if (_tmp29_) {
						_tmp28_ = TRUE;
					} else {
						gboolean _tmp32_ = FALSE;
						gint _tmp33_ = 0;
						_tmp33_ = x;
						if (_tmp33_ == 10) {
							gint _tmp34_ = 0;
							_tmp34_ = y;
							_tmp32_ = _tmp34_ == 9;
						} else {
							_tmp32_ = FALSE;
						}
						_tmp28_ = _tmp32_;
					}
					if (_tmp28_) {
						inv = TRUE;
					} else {
						gboolean _tmp35_ = FALSE;
						gboolean _tmp36_ = FALSE;
						gint _tmp37_ = 0;
						_tmp37_ = x;
						if (_tmp37_ == 11) {
							gint _tmp38_ = 0;
							_tmp38_ = y;
							_tmp36_ = _tmp38_ == 12;
						} else {
							_tmp36_ = FALSE;
						}
						if (_tmp36_) {
							_tmp35_ = TRUE;
						} else {
							gboolean _tmp39_ = FALSE;
							gint _tmp40_ = 0;
							_tmp40_ = x;
							if (_tmp40_ == 12) {
								gint _tmp41_ = 0;
								_tmp41_ = y;
								_tmp39_ = _tmp41_ == 11;
							} else {
								_tmp39_ = FALSE;
							}
							_tmp35_ = _tmp39_;
						}
						if (_tmp35_) {
							inv = TRUE;
						}
					}
				}
			}
		}
	}
	result = inv;
	return result;
}


static void cubo_genetico_corrector_class_init (CuboGeneticoCorrectorClass * klass) {
	cubo_genetico_corrector_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoCorrectorPrivate));
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_corrector_finalize;
}


static void cubo_genetico_corrector_instance_init (CuboGeneticoCorrector * self) {
	self->priv = CUBO_GENETICO_CORRECTOR_GET_PRIVATE (self);
}


static void cubo_genetico_corrector_finalize (GObject* obj) {
	CuboGeneticoCorrector * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_CORRECTOR, CuboGeneticoCorrector);
	_g_rand_free0 (self->priv->rand);
	G_OBJECT_CLASS (cubo_genetico_corrector_parent_class)->finalize (obj);
}


GType cubo_genetico_corrector_get_type (void) {
	static volatile gsize cubo_genetico_corrector_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_corrector_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoCorrectorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_corrector_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoCorrector), 0, (GInstanceInitFunc) cubo_genetico_corrector_instance_init, NULL };
		GType cubo_genetico_corrector_type_id;
		cubo_genetico_corrector_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoCorrector", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_corrector_type_id__volatile, cubo_genetico_corrector_type_id);
	}
	return cubo_genetico_corrector_type_id__volatile;
}



