/* CruzaUP.c generated by valac 0.34.8, the Vala compiler
 * generated from CruzaUP.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>


#define CUBO_GENETICO_TYPE_CRUZA_UP (cubo_genetico_cruza_up_get_type ())
#define CUBO_GENETICO_CRUZA_UP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUP))
#define CUBO_GENETICO_CRUZA_UP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUPClass))
#define CUBO_GENETICO_IS_CRUZA_UP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_CRUZA_UP))
#define CUBO_GENETICO_IS_CRUZA_UP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_CRUZA_UP))
#define CUBO_GENETICO_CRUZA_UP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUPClass))

typedef struct _CuboGeneticoCruzaUP CuboGeneticoCruzaUP;
typedef struct _CuboGeneticoCruzaUPClass CuboGeneticoCruzaUPClass;
typedef struct _CuboGeneticoCruzaUPPrivate CuboGeneticoCruzaUPPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))

struct _CuboGeneticoCruzaUP {
	GObject parent_instance;
	CuboGeneticoCruzaUPPrivate * priv;
};

struct _CuboGeneticoCruzaUPClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoCruzaUPPrivate {
	gdouble prob;
	GRand* rand;
};


static gpointer cubo_genetico_cruza_up_parent_class = NULL;

GType cubo_genetico_cruza_up_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_CRUZA_UP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUPPrivate))
enum  {
	CUBO_GENETICO_CRUZA_UP_DUMMY_PROPERTY
};
CuboGeneticoCruzaUP* cubo_genetico_cruza_up_new (gint semilla, gdouble prob);
CuboGeneticoCruzaUP* cubo_genetico_cruza_up_construct (GType object_type, gint semilla, gdouble prob);
static void cubo_genetico_cruza_up_finalize (GObject* obj);


CuboGeneticoCruzaUP* cubo_genetico_cruza_up_construct (GType object_type, gint semilla, gdouble prob) {
	CuboGeneticoCruzaUP * self = NULL;
	gdouble _tmp0_ = 0.0;
	GRand* _tmp1_ = NULL;
	GRand* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	self = (CuboGeneticoCruzaUP*) g_object_new (object_type, NULL);
	_tmp0_ = prob;
	self->priv->prob = _tmp0_;
	_tmp1_ = g_rand_new ();
	_g_rand_free0 (self->priv->rand);
	self->priv->rand = _tmp1_;
	_tmp2_ = self->priv->rand;
	_tmp3_ = semilla;
	g_rand_set_seed (_tmp2_, (guint32) _tmp3_);
	return self;
}


CuboGeneticoCruzaUP* cubo_genetico_cruza_up_new (gint semilla, gdouble prob) {
	return cubo_genetico_cruza_up_construct (CUBO_GENETICO_TYPE_CRUZA_UP, semilla, prob);
}


static void cubo_genetico_cruza_up_class_init (CuboGeneticoCruzaUPClass * klass) {
	cubo_genetico_cruza_up_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoCruzaUPPrivate));
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_cruza_up_finalize;
}


static void cubo_genetico_cruza_up_instance_init (CuboGeneticoCruzaUP * self) {
	self->priv = CUBO_GENETICO_CRUZA_UP_GET_PRIVATE (self);
}


static void cubo_genetico_cruza_up_finalize (GObject* obj) {
	CuboGeneticoCruzaUP * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUP);
	_g_rand_free0 (self->priv->rand);
	G_OBJECT_CLASS (cubo_genetico_cruza_up_parent_class)->finalize (obj);
}


GType cubo_genetico_cruza_up_get_type (void) {
	static volatile gsize cubo_genetico_cruza_up_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_cruza_up_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoCruzaUPClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_cruza_up_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoCruzaUP), 0, (GInstanceInitFunc) cubo_genetico_cruza_up_instance_init, NULL };
		GType cubo_genetico_cruza_up_type_id;
		cubo_genetico_cruza_up_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoCruzaUP", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_cruza_up_type_id__volatile, cubo_genetico_cruza_up_type_id);
	}
	return cubo_genetico_cruza_up_type_id__volatile;
}



