/* CruzaUP.c generated by valac 0.34.8, the Vala compiler
 * generated from CruzaUP.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include "agenetico.h"


#define CUBO_GENETICO_TYPE_CRUZA_UP (cubo_genetico_cruza_up_get_type ())
#define CUBO_GENETICO_CRUZA_UP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUP))
#define CUBO_GENETICO_CRUZA_UP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUPClass))
#define CUBO_GENETICO_IS_CRUZA_UP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_CRUZA_UP))
#define CUBO_GENETICO_IS_CRUZA_UP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_CRUZA_UP))
#define CUBO_GENETICO_CRUZA_UP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUPClass))

typedef struct _CuboGeneticoCruzaUP CuboGeneticoCruzaUP;
typedef struct _CuboGeneticoCruzaUPClass CuboGeneticoCruzaUPClass;
typedef struct _CuboGeneticoCruzaUPPrivate CuboGeneticoCruzaUPPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))
#define _cubo_genetico_agenetico_genotipo_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_agenetico_genotipo_unref (var), NULL)))
#define __g_list_free__cubo_genetico_agenetico_genotipo_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (var), NULL)))

struct _CuboGeneticoCruzaUP {
	GObject parent_instance;
	CuboGeneticoCruzaUPPrivate * priv;
};

struct _CuboGeneticoCruzaUPClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoCruzaUPPrivate {
	gdouble prob;
	GRand* rand;
};


static gpointer cubo_genetico_cruza_up_parent_class = NULL;

GType cubo_genetico_cruza_up_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_CRUZA_UP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUPPrivate))
enum  {
	CUBO_GENETICO_CRUZA_UP_DUMMY_PROPERTY
};
CuboGeneticoCruzaUP* cubo_genetico_cruza_up_new (gint semilla, gdouble prob);
CuboGeneticoCruzaUP* cubo_genetico_cruza_up_construct (GType object_type, gint semilla, gdouble prob);
GList* cubo_genetico_cruza_up_cruza (CuboGeneticoCruzaUP* self, GList* padres);
static void _cubo_genetico_agenetico_genotipo_unref0_ (gpointer var);
static void _g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (GList* self);
static void cubo_genetico_cruza_up_finalize (GObject* obj);


CuboGeneticoCruzaUP* cubo_genetico_cruza_up_construct (GType object_type, gint semilla, gdouble prob) {
	CuboGeneticoCruzaUP * self = NULL;
	gdouble _tmp0_ = 0.0;
	GRand* _tmp1_ = NULL;
	GRand* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	self = (CuboGeneticoCruzaUP*) g_object_new (object_type, NULL);
	_tmp0_ = prob;
	self->priv->prob = _tmp0_;
	_tmp1_ = g_rand_new ();
	_g_rand_free0 (self->priv->rand);
	self->priv->rand = _tmp1_;
	_tmp2_ = self->priv->rand;
	_tmp3_ = semilla;
	g_rand_set_seed (_tmp2_, (guint32) _tmp3_);
	return self;
}


CuboGeneticoCruzaUP* cubo_genetico_cruza_up_new (gint semilla, gdouble prob) {
	return cubo_genetico_cruza_up_construct (CUBO_GENETICO_TYPE_CRUZA_UP, semilla, prob);
}


static gpointer _cubo_genetico_agenetico_genotipo_ref0 (gpointer self) {
	return self ? cubo_genetico_agenetico_genotipo_ref (self) : NULL;
}


static void _cubo_genetico_agenetico_genotipo_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (cubo_genetico_agenetico_genotipo_unref (var), NULL));
}


static void _g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _cubo_genetico_agenetico_genotipo_unref0_, NULL);
	g_list_free (self);
}


GList* cubo_genetico_cruza_up_cruza (CuboGeneticoCruzaUP* self, GList* padres) {
	GList* result = NULL;
	CuboGeneticoAGeneticoGenotipo* p1 = NULL;
	GList* _tmp0_ = NULL;
	gconstpointer _tmp1_ = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp2_ = NULL;
	CuboGeneticoAGeneticoGenotipo* p2 = NULL;
	GList* _tmp3_ = NULL;
	gconstpointer _tmp4_ = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp5_ = NULL;
	CuboGeneticoAGeneticoGenotipo* hijo1 = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp6_ = NULL;
	gint* _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	gint* _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	CuboGeneticoAGeneticoGenotipo* _tmp9_ = NULL;
	CuboGeneticoAGeneticoGenotipo* hijo2 = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp10_ = NULL;
	gint* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	gint* _tmp12_ = NULL;
	gint _tmp12__length1 = 0;
	CuboGeneticoAGeneticoGenotipo* _tmp13_ = NULL;
	GRand* _tmp14_ = NULL;
	gdouble _tmp15_ = 0.0;
	gdouble _tmp16_ = 0.0;
	GList* l = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp119_ = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp120_ = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp121_ = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp122_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = padres;
	_tmp1_ = g_list_nth_data (_tmp0_, (guint) 0);
	_tmp2_ = _cubo_genetico_agenetico_genotipo_ref0 ((CuboGeneticoAGeneticoGenotipo*) _tmp1_);
	p1 = _tmp2_;
	_tmp3_ = padres;
	_tmp4_ = g_list_nth_data (_tmp3_, (guint) 1);
	_tmp5_ = _cubo_genetico_agenetico_genotipo_ref0 ((CuboGeneticoAGeneticoGenotipo*) _tmp4_);
	p2 = _tmp5_;
	_tmp6_ = p1;
	_tmp7_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp6_, &_tmp7__length1);
	_tmp8_ = _tmp7_;
	_tmp8__length1 = _tmp7__length1;
	_tmp9_ = cubo_genetico_agenetico_genotipo_new (_tmp8__length1);
	hijo1 = _tmp9_;
	_tmp10_ = p2;
	_tmp11_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp10_, &_tmp11__length1);
	_tmp12_ = _tmp11_;
	_tmp12__length1 = _tmp11__length1;
	_tmp13_ = cubo_genetico_agenetico_genotipo_new (_tmp12__length1);
	hijo2 = _tmp13_;
	_tmp14_ = self->priv->rand;
	_tmp15_ = g_rand_double (_tmp14_);
	_tmp16_ = self->priv->prob;
	if (_tmp15_ < _tmp16_) {
		gint punto = 0;
		CuboGeneticoAGeneticoGenotipo* _tmp17_ = NULL;
		gint* _tmp18_ = NULL;
		gint _tmp18__length1 = 0;
		gint* _tmp19_ = NULL;
		gint _tmp19__length1 = 0;
		CuboGeneticoAGeneticoGenotipo* _tmp20_ = NULL;
		gint* _tmp21_ = NULL;
		gint _tmp21__length1 = 0;
		gint* _tmp22_ = NULL;
		gint _tmp22__length1 = 0;
		punto = 0;
		_tmp17_ = p1;
		_tmp18_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp17_, &_tmp18__length1);
		_tmp19_ = _tmp18_;
		_tmp19__length1 = _tmp18__length1;
		_tmp20_ = p2;
		_tmp21_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp20_, &_tmp21__length1);
		_tmp22_ = _tmp21_;
		_tmp22__length1 = _tmp21__length1;
		if (_tmp19__length1 < _tmp22__length1) {
			CuboGeneticoAGeneticoGenotipo* _tmp23_ = NULL;
			gint* _tmp24_ = NULL;
			gint _tmp24__length1 = 0;
			gint* _tmp25_ = NULL;
			gint _tmp25__length1 = 0;
			_tmp23_ = p1;
			_tmp24_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp23_, &_tmp24__length1);
			_tmp25_ = _tmp24_;
			_tmp25__length1 = _tmp24__length1;
			punto = _tmp25__length1 / 2;
		} else {
			CuboGeneticoAGeneticoGenotipo* _tmp26_ = NULL;
			gint* _tmp27_ = NULL;
			gint _tmp27__length1 = 0;
			gint* _tmp28_ = NULL;
			gint _tmp28__length1 = 0;
			_tmp26_ = p2;
			_tmp27_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp26_, &_tmp27__length1);
			_tmp28_ = _tmp27_;
			_tmp28__length1 = _tmp27__length1;
			punto = _tmp28__length1 / 2;
		}
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp29_ = FALSE;
				_tmp29_ = TRUE;
				while (TRUE) {
					gint _tmp31_ = 0;
					gint _tmp32_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp33_ = NULL;
					gint* _tmp34_ = NULL;
					gint _tmp34__length1 = 0;
					gint* _tmp35_ = NULL;
					gint _tmp35__length1 = 0;
					gint _tmp36_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp37_ = NULL;
					gint* _tmp38_ = NULL;
					gint _tmp38__length1 = 0;
					gint* _tmp39_ = NULL;
					gint _tmp39__length1 = 0;
					gint _tmp40_ = 0;
					gint _tmp41_ = 0;
					gint _tmp42_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp43_ = NULL;
					gint* _tmp44_ = NULL;
					gint _tmp44__length1 = 0;
					gint* _tmp45_ = NULL;
					gint _tmp45__length1 = 0;
					gint _tmp46_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp47_ = NULL;
					gint* _tmp48_ = NULL;
					gint _tmp48__length1 = 0;
					gint* _tmp49_ = NULL;
					gint _tmp49__length1 = 0;
					gint _tmp50_ = 0;
					gint _tmp51_ = 0;
					gint _tmp52_ = 0;
					if (!_tmp29_) {
						gint _tmp30_ = 0;
						_tmp30_ = i;
						i = _tmp30_ + 1;
					}
					_tmp29_ = FALSE;
					_tmp31_ = i;
					_tmp32_ = punto;
					if (!(_tmp31_ < _tmp32_)) {
						break;
					}
					_tmp33_ = hijo1;
					_tmp34_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp33_, &_tmp34__length1);
					_tmp35_ = _tmp34_;
					_tmp35__length1 = _tmp34__length1;
					_tmp36_ = i;
					_tmp37_ = p2;
					_tmp38_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp37_, &_tmp38__length1);
					_tmp39_ = _tmp38_;
					_tmp39__length1 = _tmp38__length1;
					_tmp40_ = i;
					_tmp41_ = _tmp39_[_tmp40_];
					_tmp35_[_tmp36_] = _tmp41_;
					_tmp42_ = _tmp35_[_tmp36_];
					_tmp43_ = hijo2;
					_tmp44_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp43_, &_tmp44__length1);
					_tmp45_ = _tmp44_;
					_tmp45__length1 = _tmp44__length1;
					_tmp46_ = i;
					_tmp47_ = p1;
					_tmp48_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp47_, &_tmp48__length1);
					_tmp49_ = _tmp48_;
					_tmp49__length1 = _tmp48__length1;
					_tmp50_ = i;
					_tmp51_ = _tmp49_[_tmp50_];
					_tmp45_[_tmp46_] = _tmp51_;
					_tmp52_ = _tmp45_[_tmp46_];
				}
			}
		}
		{
			gint i = 0;
			gint _tmp53_ = 0;
			_tmp53_ = punto;
			i = _tmp53_;
			{
				gboolean _tmp54_ = FALSE;
				_tmp54_ = TRUE;
				while (TRUE) {
					gint _tmp56_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp57_ = NULL;
					gint* _tmp58_ = NULL;
					gint _tmp58__length1 = 0;
					gint* _tmp59_ = NULL;
					gint _tmp59__length1 = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp60_ = NULL;
					gint* _tmp61_ = NULL;
					gint _tmp61__length1 = 0;
					gint* _tmp62_ = NULL;
					gint _tmp62__length1 = 0;
					gint _tmp63_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp64_ = NULL;
					gint* _tmp65_ = NULL;
					gint _tmp65__length1 = 0;
					gint* _tmp66_ = NULL;
					gint _tmp66__length1 = 0;
					gint _tmp67_ = 0;
					gint _tmp68_ = 0;
					gint _tmp69_ = 0;
					if (!_tmp54_) {
						gint _tmp55_ = 0;
						_tmp55_ = i;
						i = _tmp55_ + 1;
					}
					_tmp54_ = FALSE;
					_tmp56_ = i;
					_tmp57_ = p1;
					_tmp58_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp57_, &_tmp58__length1);
					_tmp59_ = _tmp58_;
					_tmp59__length1 = _tmp58__length1;
					if (!(_tmp56_ < _tmp59__length1)) {
						break;
					}
					_tmp60_ = hijo1;
					_tmp61_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp60_, &_tmp61__length1);
					_tmp62_ = _tmp61_;
					_tmp62__length1 = _tmp61__length1;
					_tmp63_ = i;
					_tmp64_ = p1;
					_tmp65_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp64_, &_tmp65__length1);
					_tmp66_ = _tmp65_;
					_tmp66__length1 = _tmp65__length1;
					_tmp67_ = i;
					_tmp68_ = _tmp66_[_tmp67_];
					_tmp62_[_tmp63_] = _tmp68_;
					_tmp69_ = _tmp62_[_tmp63_];
				}
			}
		}
		{
			gint i = 0;
			gint _tmp70_ = 0;
			_tmp70_ = punto;
			i = _tmp70_;
			{
				gboolean _tmp71_ = FALSE;
				_tmp71_ = TRUE;
				while (TRUE) {
					gint _tmp73_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp74_ = NULL;
					gint* _tmp75_ = NULL;
					gint _tmp75__length1 = 0;
					gint* _tmp76_ = NULL;
					gint _tmp76__length1 = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp77_ = NULL;
					gint* _tmp78_ = NULL;
					gint _tmp78__length1 = 0;
					gint* _tmp79_ = NULL;
					gint _tmp79__length1 = 0;
					gint _tmp80_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp81_ = NULL;
					gint* _tmp82_ = NULL;
					gint _tmp82__length1 = 0;
					gint* _tmp83_ = NULL;
					gint _tmp83__length1 = 0;
					gint _tmp84_ = 0;
					gint _tmp85_ = 0;
					gint _tmp86_ = 0;
					if (!_tmp71_) {
						gint _tmp72_ = 0;
						_tmp72_ = i;
						i = _tmp72_ + 1;
					}
					_tmp71_ = FALSE;
					_tmp73_ = i;
					_tmp74_ = p2;
					_tmp75_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp74_, &_tmp75__length1);
					_tmp76_ = _tmp75_;
					_tmp76__length1 = _tmp75__length1;
					if (!(_tmp73_ < _tmp76__length1)) {
						break;
					}
					_tmp77_ = hijo2;
					_tmp78_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp77_, &_tmp78__length1);
					_tmp79_ = _tmp78_;
					_tmp79__length1 = _tmp78__length1;
					_tmp80_ = i;
					_tmp81_ = p2;
					_tmp82_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp81_, &_tmp82__length1);
					_tmp83_ = _tmp82_;
					_tmp83__length1 = _tmp82__length1;
					_tmp84_ = i;
					_tmp85_ = _tmp83_[_tmp84_];
					_tmp79_[_tmp80_] = _tmp85_;
					_tmp86_ = _tmp79_[_tmp80_];
				}
			}
		}
	} else {
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp87_ = FALSE;
				_tmp87_ = TRUE;
				while (TRUE) {
					gint _tmp89_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp90_ = NULL;
					gint* _tmp91_ = NULL;
					gint _tmp91__length1 = 0;
					gint* _tmp92_ = NULL;
					gint _tmp92__length1 = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp93_ = NULL;
					gint* _tmp94_ = NULL;
					gint _tmp94__length1 = 0;
					gint* _tmp95_ = NULL;
					gint _tmp95__length1 = 0;
					gint _tmp96_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp97_ = NULL;
					gint* _tmp98_ = NULL;
					gint _tmp98__length1 = 0;
					gint* _tmp99_ = NULL;
					gint _tmp99__length1 = 0;
					gint _tmp100_ = 0;
					gint _tmp101_ = 0;
					gint _tmp102_ = 0;
					if (!_tmp87_) {
						gint _tmp88_ = 0;
						_tmp88_ = i;
						i = _tmp88_ + 1;
					}
					_tmp87_ = FALSE;
					_tmp89_ = i;
					_tmp90_ = p1;
					_tmp91_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp90_, &_tmp91__length1);
					_tmp92_ = _tmp91_;
					_tmp92__length1 = _tmp91__length1;
					if (!(_tmp89_ < _tmp92__length1)) {
						break;
					}
					_tmp93_ = hijo1;
					_tmp94_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp93_, &_tmp94__length1);
					_tmp95_ = _tmp94_;
					_tmp95__length1 = _tmp94__length1;
					_tmp96_ = i;
					_tmp97_ = p1;
					_tmp98_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp97_, &_tmp98__length1);
					_tmp99_ = _tmp98_;
					_tmp99__length1 = _tmp98__length1;
					_tmp100_ = i;
					_tmp101_ = _tmp99_[_tmp100_];
					_tmp95_[_tmp96_] = _tmp101_;
					_tmp102_ = _tmp95_[_tmp96_];
				}
			}
		}
		{
			gint i = 0;
			i = 0;
			{
				gboolean _tmp103_ = FALSE;
				_tmp103_ = TRUE;
				while (TRUE) {
					gint _tmp105_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp106_ = NULL;
					gint* _tmp107_ = NULL;
					gint _tmp107__length1 = 0;
					gint* _tmp108_ = NULL;
					gint _tmp108__length1 = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp109_ = NULL;
					gint* _tmp110_ = NULL;
					gint _tmp110__length1 = 0;
					gint* _tmp111_ = NULL;
					gint _tmp111__length1 = 0;
					gint _tmp112_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp113_ = NULL;
					gint* _tmp114_ = NULL;
					gint _tmp114__length1 = 0;
					gint* _tmp115_ = NULL;
					gint _tmp115__length1 = 0;
					gint _tmp116_ = 0;
					gint _tmp117_ = 0;
					gint _tmp118_ = 0;
					if (!_tmp103_) {
						gint _tmp104_ = 0;
						_tmp104_ = i;
						i = _tmp104_ + 1;
					}
					_tmp103_ = FALSE;
					_tmp105_ = i;
					_tmp106_ = p2;
					_tmp107_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp106_, &_tmp107__length1);
					_tmp108_ = _tmp107_;
					_tmp108__length1 = _tmp107__length1;
					if (!(_tmp105_ < _tmp108__length1)) {
						break;
					}
					_tmp109_ = hijo2;
					_tmp110_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp109_, &_tmp110__length1);
					_tmp111_ = _tmp110_;
					_tmp111__length1 = _tmp110__length1;
					_tmp112_ = i;
					_tmp113_ = p2;
					_tmp114_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp113_, &_tmp114__length1);
					_tmp115_ = _tmp114_;
					_tmp115__length1 = _tmp114__length1;
					_tmp116_ = i;
					_tmp117_ = _tmp115_[_tmp116_];
					_tmp111_[_tmp112_] = _tmp117_;
					_tmp118_ = _tmp111_[_tmp112_];
				}
			}
		}
	}
	l = NULL;
	_tmp119_ = hijo1;
	_tmp120_ = _cubo_genetico_agenetico_genotipo_ref0 (_tmp119_);
	l = g_list_append (l, _tmp120_);
	_tmp121_ = hijo2;
	_tmp122_ = _cubo_genetico_agenetico_genotipo_ref0 (_tmp121_);
	l = g_list_append (l, _tmp122_);
	result = l;
	_cubo_genetico_agenetico_genotipo_unref0 (hijo2);
	_cubo_genetico_agenetico_genotipo_unref0 (hijo1);
	_cubo_genetico_agenetico_genotipo_unref0 (p2);
	_cubo_genetico_agenetico_genotipo_unref0 (p1);
	return result;
}


static void cubo_genetico_cruza_up_class_init (CuboGeneticoCruzaUPClass * klass) {
	cubo_genetico_cruza_up_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoCruzaUPPrivate));
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_cruza_up_finalize;
}


static void cubo_genetico_cruza_up_instance_init (CuboGeneticoCruzaUP * self) {
	self->priv = CUBO_GENETICO_CRUZA_UP_GET_PRIVATE (self);
}


static void cubo_genetico_cruza_up_finalize (GObject* obj) {
	CuboGeneticoCruzaUP * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUP);
	_g_rand_free0 (self->priv->rand);
	G_OBJECT_CLASS (cubo_genetico_cruza_up_parent_class)->finalize (obj);
}


GType cubo_genetico_cruza_up_get_type (void) {
	static volatile gsize cubo_genetico_cruza_up_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_cruza_up_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoCruzaUPClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_cruza_up_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoCruzaUP), 0, (GInstanceInitFunc) cubo_genetico_cruza_up_instance_init, NULL };
		GType cubo_genetico_cruza_up_type_id;
		cubo_genetico_cruza_up_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoCruzaUP", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_cruza_up_type_id__volatile, cubo_genetico_cruza_up_type_id);
	}
	return cubo_genetico_cruza_up_type_id__volatile;
}



