/* CuboGenetico.c generated by valac 0.34.8, the Vala compiler
 * generated from CuboGenetico.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "agenetico.h"
#include <float.h>
#include <math.h>


#define CUBO_GENETICO_TYPE_CUBO_GENETICO (cubo_genetico_cubo_genetico_get_type ())
#define CUBO_GENETICO_CUBO_GENETICO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGenetico))
#define CUBO_GENETICO_CUBO_GENETICO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGeneticoClass))
#define CUBO_GENETICO_IS_CUBO_GENETICO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_CUBO_GENETICO))
#define CUBO_GENETICO_IS_CUBO_GENETICO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_CUBO_GENETICO))
#define CUBO_GENETICO_CUBO_GENETICO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGeneticoClass))

typedef struct _CuboGeneticoCuboGenetico CuboGeneticoCuboGenetico;
typedef struct _CuboGeneticoCuboGeneticoClass CuboGeneticoCuboGeneticoClass;
typedef struct _CuboGeneticoCuboGeneticoPrivate CuboGeneticoCuboGeneticoPrivate;

#define CUBO_GENETICO_TYPE_CRIADOR (cubo_genetico_criador_get_type ())
#define CUBO_GENETICO_CRIADOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_CRIADOR, CuboGeneticoCriador))
#define CUBO_GENETICO_CRIADOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_CRIADOR, CuboGeneticoCriadorClass))
#define CUBO_GENETICO_IS_CRIADOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_CRIADOR))
#define CUBO_GENETICO_IS_CRIADOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_CRIADOR))
#define CUBO_GENETICO_CRIADOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_CRIADOR, CuboGeneticoCriadorClass))

typedef struct _CuboGeneticoCriador CuboGeneticoCriador;
typedef struct _CuboGeneticoCriadorClass CuboGeneticoCriadorClass;

#define CUBO_GENETICO_TYPE_STORNEO (cubo_genetico_storneo_get_type ())
#define CUBO_GENETICO_STORNEO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_STORNEO, CuboGeneticoSTorneo))
#define CUBO_GENETICO_STORNEO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_STORNEO, CuboGeneticoSTorneoClass))
#define CUBO_GENETICO_IS_STORNEO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_STORNEO))
#define CUBO_GENETICO_IS_STORNEO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_STORNEO))
#define CUBO_GENETICO_STORNEO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_STORNEO, CuboGeneticoSTorneoClass))

typedef struct _CuboGeneticoSTorneo CuboGeneticoSTorneo;
typedef struct _CuboGeneticoSTorneoClass CuboGeneticoSTorneoClass;

#define CUBO_GENETICO_TYPE_CRUZA_UP (cubo_genetico_cruza_up_get_type ())
#define CUBO_GENETICO_CRUZA_UP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUP))
#define CUBO_GENETICO_CRUZA_UP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUPClass))
#define CUBO_GENETICO_IS_CRUZA_UP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_CRUZA_UP))
#define CUBO_GENETICO_IS_CRUZA_UP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_CRUZA_UP))
#define CUBO_GENETICO_CRUZA_UP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_CRUZA_UP, CuboGeneticoCruzaUPClass))

typedef struct _CuboGeneticoCruzaUP CuboGeneticoCruzaUP;
typedef struct _CuboGeneticoCruzaUPClass CuboGeneticoCruzaUPClass;

#define CUBO_GENETICO_TYPE_MUTACION (cubo_genetico_mutacion_get_type ())
#define CUBO_GENETICO_MUTACION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_MUTACION, CuboGeneticoMutacion))
#define CUBO_GENETICO_MUTACION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_MUTACION, CuboGeneticoMutacionClass))
#define CUBO_GENETICO_IS_MUTACION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_MUTACION))
#define CUBO_GENETICO_IS_MUTACION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_MUTACION))
#define CUBO_GENETICO_MUTACION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_MUTACION, CuboGeneticoMutacionClass))

typedef struct _CuboGeneticoMutacion CuboGeneticoMutacion;
typedef struct _CuboGeneticoMutacionClass CuboGeneticoMutacionClass;

#define CUBO_GENETICO_TYPE_INDIVIDUO (cubo_genetico_individuo_get_type ())
#define CUBO_GENETICO_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuo))
#define CUBO_GENETICO_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuoClass))
#define CUBO_GENETICO_IS_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_IS_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_INDIVIDUO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuoClass))

typedef struct _CuboGeneticoIndividuo CuboGeneticoIndividuo;
typedef struct _CuboGeneticoIndividuoClass CuboGeneticoIndividuoClass;
#define _cubo_genetico_criador_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_criador_unref (var), NULL)))
#define _cubo_genetico_storneo_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_storneo_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define CUBO_GENETICO_TYPE_FFITNESS (cubo_genetico_ffitness_get_type ())
#define CUBO_GENETICO_FFITNESS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_FFITNESS, CuboGeneticoFFitness))
#define CUBO_GENETICO_FFITNESS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_FFITNESS, CuboGeneticoFFitnessClass))
#define CUBO_GENETICO_IS_FFITNESS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_FFITNESS))
#define CUBO_GENETICO_IS_FFITNESS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_FFITNESS))
#define CUBO_GENETICO_FFITNESS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_FFITNESS, CuboGeneticoFFitnessClass))

typedef struct _CuboGeneticoFFitness CuboGeneticoFFitness;
typedef struct _CuboGeneticoFFitnessClass CuboGeneticoFFitnessClass;

#define CUBO_GENETICO_TYPE_FENO_GENO (cubo_genetico_feno_geno_get_type ())
#define CUBO_GENETICO_FENO_GENO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_FENO_GENO, CuboGeneticoFenoGeno))
#define CUBO_GENETICO_FENO_GENO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_FENO_GENO, CuboGeneticoFenoGenoClass))
#define CUBO_GENETICO_IS_FENO_GENO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_FENO_GENO))
#define CUBO_GENETICO_IS_FENO_GENO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_FENO_GENO))
#define CUBO_GENETICO_FENO_GENO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_FENO_GENO, CuboGeneticoFenoGenoClass))

typedef struct _CuboGeneticoFenoGeno CuboGeneticoFenoGeno;
typedef struct _CuboGeneticoFenoGenoClass CuboGeneticoFenoGenoClass;

#define CUBO_GENETICO_TYPE_CORRECTOR (cubo_genetico_corrector_get_type ())
#define CUBO_GENETICO_CORRECTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_CORRECTOR, CuboGeneticoCorrector))
#define CUBO_GENETICO_CORRECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_CORRECTOR, CuboGeneticoCorrectorClass))
#define CUBO_GENETICO_IS_CORRECTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_CORRECTOR))
#define CUBO_GENETICO_IS_CORRECTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_CORRECTOR))
#define CUBO_GENETICO_CORRECTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_CORRECTOR, CuboGeneticoCorrectorClass))

typedef struct _CuboGeneticoCorrector CuboGeneticoCorrector;
typedef struct _CuboGeneticoCorrectorClass CuboGeneticoCorrectorClass;

#define CUBO_GENETICO_TYPE_POBLACION (cubo_genetico_poblacion_get_type ())
#define CUBO_GENETICO_POBLACION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacion))
#define CUBO_GENETICO_POBLACION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacionClass))
#define CUBO_GENETICO_IS_POBLACION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_POBLACION))
#define CUBO_GENETICO_IS_POBLACION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_POBLACION))
#define CUBO_GENETICO_POBLACION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacionClass))

typedef struct _CuboGeneticoPoblacion CuboGeneticoPoblacion;
typedef struct _CuboGeneticoPoblacionClass CuboGeneticoPoblacionClass;
#define _cubo_genetico_agenetico_genotipo_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_agenetico_genotipo_unref (var), NULL)))
#define __g_list_free__cubo_genetico_agenetico_genotipo_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (var), NULL)))
#define _cubo_genetico_poblacion_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_poblacion_unref (var), NULL)))

struct _CuboGeneticoCuboGenetico {
	GObject parent_instance;
	CuboGeneticoCuboGeneticoPrivate * priv;
};

struct _CuboGeneticoCuboGeneticoClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoCuboGeneticoPrivate {
	CuboGeneticoCriador* criador;
	CuboGeneticoSTorneo* sr;
	CuboGeneticoCruzaUP* cruza;
	CuboGeneticoMutacion* mutacion;
	gint tamp;
	CuboGeneticoIndividuo* mejorg;
};


static gpointer cubo_genetico_cubo_genetico_parent_class = NULL;

GType cubo_genetico_cubo_genetico_get_type (void) G_GNUC_CONST;
gpointer cubo_genetico_criador_ref (gpointer instance);
void cubo_genetico_criador_unref (gpointer instance);
GParamSpec* cubo_genetico_param_spec_criador (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_value_set_criador (GValue* value, gpointer v_object);
void cubo_genetico_value_take_criador (GValue* value, gpointer v_object);
gpointer cubo_genetico_value_get_criador (const GValue* value);
GType cubo_genetico_criador_get_type (void) G_GNUC_CONST;
gpointer cubo_genetico_storneo_ref (gpointer instance);
void cubo_genetico_storneo_unref (gpointer instance);
GParamSpec* cubo_genetico_param_spec_storneo (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_value_set_storneo (GValue* value, gpointer v_object);
void cubo_genetico_value_take_storneo (GValue* value, gpointer v_object);
gpointer cubo_genetico_value_get_storneo (const GValue* value);
GType cubo_genetico_storneo_get_type (void) G_GNUC_CONST;
GType cubo_genetico_cruza_up_get_type (void) G_GNUC_CONST;
GType cubo_genetico_mutacion_get_type (void) G_GNUC_CONST;
GType cubo_genetico_individuo_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_CUBO_GENETICO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGeneticoPrivate))
enum  {
	CUBO_GENETICO_CUBO_GENETICO_DUMMY_PROPERTY,
	CUBO_GENETICO_CUBO_GENETICO_MEJOR
};
GType cubo_genetico_ffitness_get_type (void) G_GNUC_CONST;
GType cubo_genetico_feno_geno_get_type (void) G_GNUC_CONST;
GType cubo_genetico_corrector_get_type (void) G_GNUC_CONST;
CuboGeneticoCuboGenetico* cubo_genetico_cubo_genetico_new (CuboGeneticoFFitness* ffitness, CuboGeneticoFenoGeno* fenogeno, CuboGeneticoCorrector* corrector, CuboGeneticoSTorneo* sr, CuboGeneticoCruzaUP* cruza, CuboGeneticoMutacion* mutacion, gint semilla, gint tamp);
CuboGeneticoCuboGenetico* cubo_genetico_cubo_genetico_construct (GType object_type, CuboGeneticoFFitness* ffitness, CuboGeneticoFenoGeno* fenogeno, CuboGeneticoCorrector* corrector, CuboGeneticoSTorneo* sr, CuboGeneticoCruzaUP* cruza, CuboGeneticoMutacion* mutacion, gint semilla, gint tamp);
CuboGeneticoCriador* cubo_genetico_criador_new (CuboGeneticoFenoGeno* fenogeno, CuboGeneticoFFitness* fitness, CuboGeneticoCorrector* corrector, gint semilla);
CuboGeneticoCriador* cubo_genetico_criador_construct (GType object_type, CuboGeneticoFenoGeno* fenogeno, CuboGeneticoFFitness* fitness, CuboGeneticoCorrector* corrector, gint semilla);
gpointer cubo_genetico_poblacion_ref (gpointer instance);
void cubo_genetico_poblacion_unref (gpointer instance);
GParamSpec* cubo_genetico_param_spec_poblacion (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_value_set_poblacion (GValue* value, gpointer v_object);
void cubo_genetico_value_take_poblacion (GValue* value, gpointer v_object);
gpointer cubo_genetico_value_get_poblacion (const GValue* value);
GType cubo_genetico_poblacion_get_type (void) G_GNUC_CONST;
CuboGeneticoPoblacion* cubo_genetico_cubo_genetico_iteracion (CuboGeneticoCuboGenetico* self, CuboGeneticoPoblacion* actual);
CuboGeneticoPoblacion* cubo_genetico_poblacion_new (void);
CuboGeneticoPoblacion* cubo_genetico_poblacion_construct (GType object_type);
gint cubo_genetico_poblacion_get_generacion (CuboGeneticoPoblacion* self);
void cubo_genetico_poblacion_set_generacion (CuboGeneticoPoblacion* self, gint value);
gint cubo_genetico_poblacion_getTam (CuboGeneticoPoblacion* self);
GList* cubo_genetico_storneo_selecciona (CuboGeneticoSTorneo* self, CuboGeneticoPoblacion* p);
GList* cubo_genetico_cruza_up_cruza (CuboGeneticoCruzaUP* self, GList* padres);
CuboGeneticoAGeneticoGenotipo* cubo_genetico_mutacion_muta (CuboGeneticoMutacion* self, CuboGeneticoAGeneticoGenotipo* g);
void cubo_genetico_poblacion_agregaIndividuo (CuboGeneticoPoblacion* self, CuboGeneticoIndividuo* ind);
CuboGeneticoIndividuo* cubo_genetico_criador_individuoNuevo (CuboGeneticoCriador* self, CuboGeneticoAGeneticoGenotipo* geno);
static void _cubo_genetico_agenetico_genotipo_unref0_ (gpointer var);
static void _g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (GList* self);
CuboGeneticoIndividuo* cubo_genetico_poblacion_get_mejorInd (CuboGeneticoPoblacion* self);
gdouble cubo_genetico_individuo_get_fitness (CuboGeneticoIndividuo* self);
void cubo_genetico_cubo_genetico_run (CuboGeneticoCuboGenetico* self);
CuboGeneticoPoblacion* cubo_genetico_criador_poblacionNuevaR (CuboGeneticoCriador* self, gint tam);
CuboGeneticoIndividuo* cubo_genetico_cubo_genetico_get_mejor (CuboGeneticoCuboGenetico* self);
static void cubo_genetico_cubo_genetico_finalize (GObject* obj);
static void _vala_cubo_genetico_cubo_genetico_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);


static gpointer _cubo_genetico_storneo_ref0 (gpointer self) {
	return self ? cubo_genetico_storneo_ref (self) : NULL;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


CuboGeneticoCuboGenetico* cubo_genetico_cubo_genetico_construct (GType object_type, CuboGeneticoFFitness* ffitness, CuboGeneticoFenoGeno* fenogeno, CuboGeneticoCorrector* corrector, CuboGeneticoSTorneo* sr, CuboGeneticoCruzaUP* cruza, CuboGeneticoMutacion* mutacion, gint semilla, gint tamp) {
	CuboGeneticoCuboGenetico * self = NULL;
	CuboGeneticoFenoGeno* _tmp0_ = NULL;
	CuboGeneticoFFitness* _tmp1_ = NULL;
	CuboGeneticoCorrector* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	CuboGeneticoCriador* _tmp4_ = NULL;
	CuboGeneticoSTorneo* _tmp5_ = NULL;
	CuboGeneticoSTorneo* _tmp6_ = NULL;
	CuboGeneticoCruzaUP* _tmp7_ = NULL;
	CuboGeneticoCruzaUP* _tmp8_ = NULL;
	CuboGeneticoMutacion* _tmp9_ = NULL;
	CuboGeneticoMutacion* _tmp10_ = NULL;
	gint _tmp11_ = 0;
	g_return_val_if_fail (ffitness != NULL, NULL);
	g_return_val_if_fail (fenogeno != NULL, NULL);
	g_return_val_if_fail (corrector != NULL, NULL);
	g_return_val_if_fail (sr != NULL, NULL);
	g_return_val_if_fail (cruza != NULL, NULL);
	g_return_val_if_fail (mutacion != NULL, NULL);
	self = (CuboGeneticoCuboGenetico*) g_object_new (object_type, NULL);
	_tmp0_ = fenogeno;
	_tmp1_ = ffitness;
	_tmp2_ = corrector;
	_tmp3_ = semilla;
	_tmp4_ = cubo_genetico_criador_new (_tmp0_, _tmp1_, _tmp2_, _tmp3_);
	_cubo_genetico_criador_unref0 (self->priv->criador);
	self->priv->criador = _tmp4_;
	_tmp5_ = sr;
	_tmp6_ = _cubo_genetico_storneo_ref0 (_tmp5_);
	_cubo_genetico_storneo_unref0 (self->priv->sr);
	self->priv->sr = _tmp6_;
	_tmp7_ = cruza;
	_tmp8_ = _g_object_ref0 (_tmp7_);
	_g_object_unref0 (self->priv->cruza);
	self->priv->cruza = _tmp8_;
	_tmp9_ = mutacion;
	_tmp10_ = _g_object_ref0 (_tmp9_);
	_g_object_unref0 (self->priv->mutacion);
	self->priv->mutacion = _tmp10_;
	_tmp11_ = tamp;
	self->priv->tamp = _tmp11_;
	return self;
}


CuboGeneticoCuboGenetico* cubo_genetico_cubo_genetico_new (CuboGeneticoFFitness* ffitness, CuboGeneticoFenoGeno* fenogeno, CuboGeneticoCorrector* corrector, CuboGeneticoSTorneo* sr, CuboGeneticoCruzaUP* cruza, CuboGeneticoMutacion* mutacion, gint semilla, gint tamp) {
	return cubo_genetico_cubo_genetico_construct (CUBO_GENETICO_TYPE_CUBO_GENETICO, ffitness, fenogeno, corrector, sr, cruza, mutacion, semilla, tamp);
}


static gpointer _cubo_genetico_agenetico_genotipo_ref0 (gpointer self) {
	return self ? cubo_genetico_agenetico_genotipo_ref (self) : NULL;
}


static void _cubo_genetico_agenetico_genotipo_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (cubo_genetico_agenetico_genotipo_unref (var), NULL));
}


static void _g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _cubo_genetico_agenetico_genotipo_unref0_, NULL);
	g_list_free (self);
}


CuboGeneticoPoblacion* cubo_genetico_cubo_genetico_iteracion (CuboGeneticoCuboGenetico* self, CuboGeneticoPoblacion* actual) {
	CuboGeneticoPoblacion* result = NULL;
	CuboGeneticoPoblacion* pnueva = NULL;
	CuboGeneticoPoblacion* _tmp0_ = NULL;
	CuboGeneticoPoblacion* _tmp1_ = NULL;
	CuboGeneticoPoblacion* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	CuboGeneticoIndividuo* m = NULL;
	CuboGeneticoPoblacion* _tmp27_ = NULL;
	CuboGeneticoIndividuo* _tmp28_ = NULL;
	CuboGeneticoIndividuo* _tmp29_ = NULL;
	CuboGeneticoIndividuo* _tmp30_ = NULL;
	CuboGeneticoIndividuo* _tmp31_ = NULL;
	gdouble _tmp32_ = 0.0;
	gdouble _tmp33_ = 0.0;
	CuboGeneticoIndividuo* _tmp34_ = NULL;
	gdouble _tmp35_ = 0.0;
	gdouble _tmp36_ = 0.0;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (actual != NULL, NULL);
	_tmp0_ = cubo_genetico_poblacion_new ();
	pnueva = _tmp0_;
	_tmp1_ = pnueva;
	_tmp2_ = actual;
	_tmp3_ = cubo_genetico_poblacion_get_generacion (_tmp2_);
	_tmp4_ = _tmp3_;
	cubo_genetico_poblacion_set_generacion (_tmp1_, _tmp4_ + 1);
	while (TRUE) {
		CuboGeneticoPoblacion* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		CuboGeneticoPoblacion* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		GList* select = NULL;
		CuboGeneticoSTorneo* _tmp9_ = NULL;
		CuboGeneticoPoblacion* _tmp10_ = NULL;
		GList* _tmp11_ = NULL;
		GList* cross = NULL;
		CuboGeneticoCruzaUP* _tmp12_ = NULL;
		GList* _tmp13_ = NULL;
		GList* _tmp14_ = NULL;
		GList* mut = NULL;
		GList* _tmp15_ = NULL;
		GList* _tmp20_ = NULL;
		_tmp5_ = pnueva;
		_tmp6_ = cubo_genetico_poblacion_getTam (_tmp5_);
		_tmp7_ = actual;
		_tmp8_ = cubo_genetico_poblacion_getTam (_tmp7_);
		if (!(_tmp6_ < _tmp8_)) {
			break;
		}
		_tmp9_ = self->priv->sr;
		_tmp10_ = actual;
		_tmp11_ = cubo_genetico_storneo_selecciona (_tmp9_, _tmp10_);
		select = _tmp11_;
		_tmp12_ = self->priv->cruza;
		_tmp13_ = select;
		_tmp14_ = cubo_genetico_cruza_up_cruza (_tmp12_, _tmp13_);
		cross = _tmp14_;
		mut = NULL;
		_tmp15_ = cross;
		{
			GList* g_collection = NULL;
			GList* g_it = NULL;
			g_collection = _tmp15_;
			for (g_it = g_collection; g_it != NULL; g_it = g_it->next) {
				CuboGeneticoAGeneticoGenotipo* _tmp16_ = NULL;
				CuboGeneticoAGeneticoGenotipo* g = NULL;
				_tmp16_ = _cubo_genetico_agenetico_genotipo_ref0 ((CuboGeneticoAGeneticoGenotipo*) g_it->data);
				g = _tmp16_;
				{
					CuboGeneticoMutacion* _tmp17_ = NULL;
					CuboGeneticoAGeneticoGenotipo* _tmp18_ = NULL;
					CuboGeneticoAGeneticoGenotipo* _tmp19_ = NULL;
					_tmp17_ = self->priv->mutacion;
					_tmp18_ = g;
					_tmp19_ = cubo_genetico_mutacion_muta (_tmp17_, _tmp18_);
					mut = g_list_append (mut, _tmp19_);
					_cubo_genetico_agenetico_genotipo_unref0 (g);
				}
			}
		}
		_tmp20_ = mut;
		{
			GList* g_collection = NULL;
			GList* g_it = NULL;
			g_collection = _tmp20_;
			for (g_it = g_collection; g_it != NULL; g_it = g_it->next) {
				CuboGeneticoAGeneticoGenotipo* _tmp21_ = NULL;
				CuboGeneticoAGeneticoGenotipo* g = NULL;
				_tmp21_ = _cubo_genetico_agenetico_genotipo_ref0 ((CuboGeneticoAGeneticoGenotipo*) g_it->data);
				g = _tmp21_;
				{
					CuboGeneticoPoblacion* _tmp22_ = NULL;
					CuboGeneticoCriador* _tmp23_ = NULL;
					CuboGeneticoAGeneticoGenotipo* _tmp24_ = NULL;
					CuboGeneticoIndividuo* _tmp25_ = NULL;
					CuboGeneticoIndividuo* _tmp26_ = NULL;
					_tmp22_ = pnueva;
					_tmp23_ = self->priv->criador;
					_tmp24_ = g;
					_tmp25_ = cubo_genetico_criador_individuoNuevo (_tmp23_, _tmp24_);
					_tmp26_ = _tmp25_;
					cubo_genetico_poblacion_agregaIndividuo (_tmp22_, _tmp26_);
					_g_object_unref0 (_tmp26_);
					_cubo_genetico_agenetico_genotipo_unref0 (g);
				}
			}
		}
		__g_list_free__cubo_genetico_agenetico_genotipo_unref0_0 (mut);
		__g_list_free__cubo_genetico_agenetico_genotipo_unref0_0 (cross);
		__g_list_free__cubo_genetico_agenetico_genotipo_unref0_0 (select);
	}
	_tmp27_ = pnueva;
	_tmp28_ = cubo_genetico_poblacion_get_mejorInd (_tmp27_);
	_tmp29_ = _tmp28_;
	_tmp30_ = _g_object_ref0 (_tmp29_);
	m = _tmp30_;
	_tmp31_ = m;
	_tmp32_ = cubo_genetico_individuo_get_fitness (_tmp31_);
	_tmp33_ = _tmp32_;
	_tmp34_ = self->priv->mejorg;
	_tmp35_ = cubo_genetico_individuo_get_fitness (_tmp34_);
	_tmp36_ = _tmp35_;
	if (_tmp33_ <= _tmp36_) {
		CuboGeneticoIndividuo* _tmp37_ = NULL;
		CuboGeneticoIndividuo* _tmp38_ = NULL;
		_tmp37_ = m;
		_tmp38_ = _g_object_ref0 (_tmp37_);
		_g_object_unref0 (self->priv->mejorg);
		self->priv->mejorg = _tmp38_;
	}
	result = pnueva;
	_g_object_unref0 (m);
	return result;
}


void cubo_genetico_cubo_genetico_run (CuboGeneticoCuboGenetico* self) {
	CuboGeneticoPoblacion* p = NULL;
	CuboGeneticoCriador* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	CuboGeneticoPoblacion* _tmp2_ = NULL;
	CuboGeneticoPoblacion* _tmp3_ = NULL;
	CuboGeneticoIndividuo* _tmp4_ = NULL;
	CuboGeneticoIndividuo* _tmp5_ = NULL;
	CuboGeneticoIndividuo* _tmp6_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->criador;
	_tmp1_ = self->priv->tamp;
	_tmp2_ = cubo_genetico_criador_poblacionNuevaR (_tmp0_, _tmp1_);
	p = _tmp2_;
	_tmp3_ = p;
	_tmp4_ = cubo_genetico_poblacion_get_mejorInd (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = _g_object_ref0 (_tmp5_);
	_g_object_unref0 (self->priv->mejorg);
	self->priv->mejorg = _tmp6_;
	while (TRUE) {
		CuboGeneticoPoblacion* _tmp7_ = NULL;
		gint _tmp8_ = 0;
		gint _tmp9_ = 0;
		CuboGeneticoPoblacion* _tmp10_ = NULL;
		CuboGeneticoPoblacion* _tmp11_ = NULL;
		_tmp7_ = p;
		_tmp8_ = cubo_genetico_poblacion_get_generacion (_tmp7_);
		_tmp9_ = _tmp8_;
		if (!(_tmp9_ <= 1000)) {
			break;
		}
		_tmp10_ = p;
		_tmp11_ = cubo_genetico_cubo_genetico_iteracion (self, _tmp10_);
		_cubo_genetico_poblacion_unref0 (p);
		p = _tmp11_;
	}
	_cubo_genetico_poblacion_unref0 (p);
}


CuboGeneticoIndividuo* cubo_genetico_cubo_genetico_get_mejor (CuboGeneticoCuboGenetico* self) {
	CuboGeneticoIndividuo* result;
	CuboGeneticoIndividuo* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->mejorg;
	result = _tmp0_;
	return result;
}


static void cubo_genetico_cubo_genetico_class_init (CuboGeneticoCuboGeneticoClass * klass) {
	cubo_genetico_cubo_genetico_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoCuboGeneticoPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_cubo_genetico_cubo_genetico_get_property;
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_cubo_genetico_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CUBO_GENETICO_CUBO_GENETICO_MEJOR, g_param_spec_object ("mejor", "mejor", "mejor", CUBO_GENETICO_TYPE_INDIVIDUO, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void cubo_genetico_cubo_genetico_instance_init (CuboGeneticoCuboGenetico * self) {
	self->priv = CUBO_GENETICO_CUBO_GENETICO_GET_PRIVATE (self);
}


static void cubo_genetico_cubo_genetico_finalize (GObject* obj) {
	CuboGeneticoCuboGenetico * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGenetico);
	_cubo_genetico_criador_unref0 (self->priv->criador);
	_cubo_genetico_storneo_unref0 (self->priv->sr);
	_g_object_unref0 (self->priv->cruza);
	_g_object_unref0 (self->priv->mutacion);
	_g_object_unref0 (self->priv->mejorg);
	G_OBJECT_CLASS (cubo_genetico_cubo_genetico_parent_class)->finalize (obj);
}


GType cubo_genetico_cubo_genetico_get_type (void) {
	static volatile gsize cubo_genetico_cubo_genetico_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_cubo_genetico_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoCuboGeneticoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_cubo_genetico_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoCuboGenetico), 0, (GInstanceInitFunc) cubo_genetico_cubo_genetico_instance_init, NULL };
		GType cubo_genetico_cubo_genetico_type_id;
		cubo_genetico_cubo_genetico_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoCuboGenetico", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_cubo_genetico_type_id__volatile, cubo_genetico_cubo_genetico_type_id);
	}
	return cubo_genetico_cubo_genetico_type_id__volatile;
}


static void _vala_cubo_genetico_cubo_genetico_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CuboGeneticoCuboGenetico * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGenetico);
	switch (property_id) {
		case CUBO_GENETICO_CUBO_GENETICO_MEJOR:
		g_value_set_object (value, cubo_genetico_cubo_genetico_get_mejor (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



