/* CuboGenetico.c generated by valac 0.34.8, the Vala compiler
 * generated from CuboGenetico.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define CUBO_GENETICO_TYPE_CUBO_GENETICO (cubo_genetico_cubo_genetico_get_type ())
#define CUBO_GENETICO_CUBO_GENETICO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGenetico))
#define CUBO_GENETICO_CUBO_GENETICO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGeneticoClass))
#define CUBO_GENETICO_IS_CUBO_GENETICO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_CUBO_GENETICO))
#define CUBO_GENETICO_IS_CUBO_GENETICO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_CUBO_GENETICO))
#define CUBO_GENETICO_CUBO_GENETICO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_CUBO_GENETICO, CuboGeneticoCuboGeneticoClass))

typedef struct _CuboGeneticoCuboGenetico CuboGeneticoCuboGenetico;
typedef struct _CuboGeneticoCuboGeneticoClass CuboGeneticoCuboGeneticoClass;
typedef struct _CuboGeneticoCuboGeneticoPrivate CuboGeneticoCuboGeneticoPrivate;

struct _CuboGeneticoCuboGenetico {
	GObject parent_instance;
	CuboGeneticoCuboGeneticoPrivate * priv;
};

struct _CuboGeneticoCuboGeneticoClass {
	GObjectClass parent_class;
};


static gpointer cubo_genetico_cubo_genetico_parent_class = NULL;

GType cubo_genetico_cubo_genetico_get_type (void) G_GNUC_CONST;
enum  {
	CUBO_GENETICO_CUBO_GENETICO_DUMMY_PROPERTY
};
CuboGeneticoCuboGenetico* cubo_genetico_cubo_genetico_new (void);
CuboGeneticoCuboGenetico* cubo_genetico_cubo_genetico_construct (GType object_type);


CuboGeneticoCuboGenetico* cubo_genetico_cubo_genetico_construct (GType object_type) {
	CuboGeneticoCuboGenetico * self = NULL;
	self = (CuboGeneticoCuboGenetico*) g_object_new (object_type, NULL);
	return self;
}


CuboGeneticoCuboGenetico* cubo_genetico_cubo_genetico_new (void) {
	return cubo_genetico_cubo_genetico_construct (CUBO_GENETICO_TYPE_CUBO_GENETICO);
}


static void cubo_genetico_cubo_genetico_class_init (CuboGeneticoCuboGeneticoClass * klass) {
	cubo_genetico_cubo_genetico_parent_class = g_type_class_peek_parent (klass);
}


static void cubo_genetico_cubo_genetico_instance_init (CuboGeneticoCuboGenetico * self) {
}


GType cubo_genetico_cubo_genetico_get_type (void) {
	static volatile gsize cubo_genetico_cubo_genetico_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_cubo_genetico_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoCuboGeneticoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_cubo_genetico_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoCuboGenetico), 0, (GInstanceInitFunc) cubo_genetico_cubo_genetico_instance_init, NULL };
		GType cubo_genetico_cubo_genetico_type_id;
		cubo_genetico_cubo_genetico_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoCuboGenetico", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_cubo_genetico_type_id__volatile, cubo_genetico_cubo_genetico_type_id);
	}
	return cubo_genetico_cubo_genetico_type_id__volatile;
}



