/* FenoGeno.c generated by valac 0.34.8, the Vala compiler
 * generated from FenoGeno.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define CUBO_GENETICO_TYPE_FENO_GENO (cubo_genetico_feno_geno_get_type ())
#define CUBO_GENETICO_FENO_GENO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_FENO_GENO, CuboGeneticoFenoGeno))
#define CUBO_GENETICO_FENO_GENO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_FENO_GENO, CuboGeneticoFenoGenoClass))
#define CUBO_GENETICO_IS_FENO_GENO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_FENO_GENO))
#define CUBO_GENETICO_IS_FENO_GENO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_FENO_GENO))
#define CUBO_GENETICO_FENO_GENO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_FENO_GENO, CuboGeneticoFenoGenoClass))

typedef struct _CuboGeneticoFenoGeno CuboGeneticoFenoGeno;
typedef struct _CuboGeneticoFenoGenoClass CuboGeneticoFenoGenoClass;
typedef struct _CuboGeneticoFenoGenoPrivate CuboGeneticoFenoGenoPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _CuboGeneticoFenoGeno {
	GObject parent_instance;
	CuboGeneticoFenoGenoPrivate * priv;
};

struct _CuboGeneticoFenoGenoClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoFenoGenoPrivate {
	GRand* rand;
};


static gpointer cubo_genetico_feno_geno_parent_class = NULL;

GType cubo_genetico_feno_geno_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_FENO_GENO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_FENO_GENO, CuboGeneticoFenoGenoPrivate))
enum  {
	CUBO_GENETICO_FENO_GENO_DUMMY_PROPERTY
};
CuboGeneticoFenoGeno* cubo_genetico_feno_geno_new (gint semilla);
CuboGeneticoFenoGeno* cubo_genetico_feno_geno_construct (GType object_type, gint semilla);
gint* cubo_genetico_feno_geno_codifica (CuboGeneticoFenoGeno* self, gchar** feno, int feno_length1, int* result_length1);
static gint cubo_genetico_feno_geno_co (CuboGeneticoFenoGeno* self, const gchar* i);
gchar** cubo_genetico_feno_geno_decodifica (CuboGeneticoFenoGeno* self, gint* geno, int geno_length1, int* result_length1);
static gchar* cubo_genetico_feno_geno_dc (CuboGeneticoFenoGeno* self, gint i);
gint* cubo_genetico_feno_geno_genoAleatNuev (CuboGeneticoFenoGeno* self, gint n, int* result_length1);
static void cubo_genetico_feno_geno_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


CuboGeneticoFenoGeno* cubo_genetico_feno_geno_construct (GType object_type, gint semilla) {
	CuboGeneticoFenoGeno * self = NULL;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	self = (CuboGeneticoFenoGeno*) g_object_new (object_type, NULL);
	_tmp0_ = g_rand_new ();
	_g_rand_free0 (self->priv->rand);
	self->priv->rand = _tmp0_;
	_tmp1_ = self->priv->rand;
	_tmp2_ = semilla;
	g_rand_set_seed (_tmp1_, (guint32) _tmp2_);
	return self;
}


CuboGeneticoFenoGeno* cubo_genetico_feno_geno_new (gint semilla) {
	return cubo_genetico_feno_geno_construct (CUBO_GENETICO_TYPE_FENO_GENO, semilla);
}


/**
 *Codifica el fenotipo en un genotipo
 */
gint* cubo_genetico_feno_geno_codifica (CuboGeneticoFenoGeno* self, gchar** feno, int feno_length1, int* result_length1) {
	gint* result = NULL;
	gint* geno = NULL;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint geno_length1 = 0;
	gint _geno_size_ = 0;
	gint* _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = feno;
	_tmp0__length1 = feno_length1;
	_tmp1_ = g_new0 (gint, _tmp0__length1);
	geno = _tmp1_;
	geno_length1 = _tmp0__length1;
	_geno_size_ = geno_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gint _tmp4_ = 0;
				gchar** _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint* _tmp6_ = NULL;
				gint _tmp6__length1 = 0;
				gint _tmp7_ = 0;
				gchar** _tmp8_ = NULL;
				gint _tmp8__length1 = 0;
				gint _tmp9_ = 0;
				const gchar* _tmp10_ = NULL;
				gint _tmp11_ = 0;
				gint _tmp12_ = 0;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = feno;
				_tmp5__length1 = feno_length1;
				if (!(_tmp4_ < _tmp5__length1)) {
					break;
				}
				_tmp6_ = geno;
				_tmp6__length1 = geno_length1;
				_tmp7_ = i;
				_tmp8_ = feno;
				_tmp8__length1 = feno_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_];
				_tmp11_ = cubo_genetico_feno_geno_co (self, _tmp10_);
				_tmp6_[_tmp7_] = _tmp11_;
				_tmp12_ = _tmp6_[_tmp7_];
			}
		}
	}
	_tmp13_ = geno;
	_tmp13__length1 = geno_length1;
	if (result_length1) {
		*result_length1 = _tmp13__length1;
	}
	result = _tmp13_;
	return result;
}


/**
 *Decodifica el genotipo en un fenotipo
 */
gchar** cubo_genetico_feno_geno_decodifica (CuboGeneticoFenoGeno* self, gint* geno, int geno_length1, int* result_length1) {
	gchar** result = NULL;
	gchar** feno = NULL;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gchar** _tmp1_ = NULL;
	gint feno_length1 = 0;
	gint _feno_size_ = 0;
	gchar** _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = geno;
	_tmp0__length1 = geno_length1;
	_tmp1_ = g_new0 (gchar*, _tmp0__length1 + 1);
	feno = _tmp1_;
	feno_length1 = _tmp0__length1;
	_feno_size_ = feno_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gint _tmp4_ = 0;
				gint* _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gchar** _tmp6_ = NULL;
				gint _tmp6__length1 = 0;
				gint _tmp7_ = 0;
				gint* _tmp8_ = NULL;
				gint _tmp8__length1 = 0;
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				gchar* _tmp11_ = NULL;
				gchar* _tmp12_ = NULL;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = geno;
				_tmp5__length1 = geno_length1;
				if (!(_tmp4_ < _tmp5__length1)) {
					break;
				}
				_tmp6_ = feno;
				_tmp6__length1 = feno_length1;
				_tmp7_ = i;
				_tmp8_ = geno;
				_tmp8__length1 = geno_length1;
				_tmp9_ = i;
				_tmp10_ = _tmp8_[_tmp9_];
				_tmp11_ = cubo_genetico_feno_geno_dc (self, _tmp10_);
				_g_free0 (_tmp6_[_tmp7_]);
				_tmp6_[_tmp7_] = _tmp11_;
				_tmp12_ = _tmp6_[_tmp7_];
			}
		}
	}
	_tmp13_ = feno;
	_tmp13__length1 = feno_length1;
	if (result_length1) {
		*result_length1 = _tmp13__length1;
	}
	result = _tmp13_;
	return result;
}


/**
 *Crea y regresa un nuevo genotipo de tamanio n 
 *con valores aleatorios
 */
gint* cubo_genetico_feno_geno_genoAleatNuev (CuboGeneticoFenoGeno* self, gint n, int* result_length1) {
	gint* result = NULL;
	gint* geno = NULL;
	gint _tmp0_ = 0;
	gint* _tmp1_ = NULL;
	gint geno_length1 = 0;
	gint _geno_size_ = 0;
	gint* _tmp11_ = NULL;
	gint _tmp11__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = n;
	_tmp1_ = g_new0 (gint, _tmp0_);
	geno = _tmp1_;
	geno_length1 = _tmp0_;
	_geno_size_ = geno_length1;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				gint _tmp4_ = 0;
				gint _tmp5_ = 0;
				gint* _tmp6_ = NULL;
				gint _tmp6__length1 = 0;
				gint _tmp7_ = 0;
				GRand* _tmp8_ = NULL;
				gint32 _tmp9_ = 0;
				gint _tmp10_ = 0;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = i;
				_tmp5_ = n;
				if (!(_tmp4_ < _tmp5_)) {
					break;
				}
				_tmp6_ = geno;
				_tmp6__length1 = geno_length1;
				_tmp7_ = i;
				_tmp8_ = self->priv->rand;
				_tmp9_ = g_rand_int_range (_tmp8_, (gint32) 1, (gint32) 13);
				_tmp6_[_tmp7_] = (gint) _tmp9_;
				_tmp10_ = _tmp6_[_tmp7_];
			}
		}
	}
	_tmp11_ = geno;
	_tmp11__length1 = geno_length1;
	if (result_length1) {
		*result_length1 = _tmp11__length1;
	}
	result = _tmp11_;
	return result;
}


/**
 * R=1 ,L=3 ,U=5 ,D=7 ,F=9  ,B =11 
 * R'=2,L'=4,U'=6,D'=8,F'=10,B'=12
 */
static gchar* cubo_genetico_feno_geno_dc (CuboGeneticoFenoGeno* self, gint i) {
	gchar* result = NULL;
	gchar* g = NULL;
	gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("");
	g = _tmp0_;
	_tmp1_ = i;
	switch (_tmp1_) {
		case 1:
		{
			gchar* _tmp2_ = NULL;
			_tmp2_ = g_strdup ("R");
			_g_free0 (g);
			g = _tmp2_;
			break;
		}
		case 2:
		{
			gchar* _tmp3_ = NULL;
			_tmp3_ = g_strdup ("R'");
			_g_free0 (g);
			g = _tmp3_;
			break;
		}
		case 3:
		{
			gchar* _tmp4_ = NULL;
			_tmp4_ = g_strdup ("L");
			_g_free0 (g);
			g = _tmp4_;
			break;
		}
		case 4:
		{
			gchar* _tmp5_ = NULL;
			_tmp5_ = g_strdup ("L'");
			_g_free0 (g);
			g = _tmp5_;
			break;
		}
		case 5:
		{
			gchar* _tmp6_ = NULL;
			_tmp6_ = g_strdup ("U");
			_g_free0 (g);
			g = _tmp6_;
			break;
		}
		case 6:
		{
			gchar* _tmp7_ = NULL;
			_tmp7_ = g_strdup ("U'");
			_g_free0 (g);
			g = _tmp7_;
			break;
		}
		case 7:
		{
			gchar* _tmp8_ = NULL;
			_tmp8_ = g_strdup ("D");
			_g_free0 (g);
			g = _tmp8_;
			break;
		}
		case 8:
		{
			gchar* _tmp9_ = NULL;
			_tmp9_ = g_strdup ("D'");
			_g_free0 (g);
			g = _tmp9_;
			break;
		}
		case 9:
		{
			gchar* _tmp10_ = NULL;
			_tmp10_ = g_strdup ("F");
			_g_free0 (g);
			g = _tmp10_;
			break;
		}
		case 10:
		{
			gchar* _tmp11_ = NULL;
			_tmp11_ = g_strdup ("F'");
			_g_free0 (g);
			g = _tmp11_;
			break;
		}
		case 11:
		{
			gchar* _tmp12_ = NULL;
			_tmp12_ = g_strdup ("B");
			_g_free0 (g);
			g = _tmp12_;
			break;
		}
		case 12:
		{
			gchar* _tmp13_ = NULL;
			_tmp13_ = g_strdup ("B'");
			_g_free0 (g);
			g = _tmp13_;
			break;
		}
		default:
		break;
	}
	result = g;
	return result;
}


/**
 * R=1 ,L=3 ,U=5 ,D=7 ,F=9  ,B =11 
 * R'=2,L'=4,U'=6,D'=8,F'=10,B'=12
 */
static gint cubo_genetico_feno_geno_co (CuboGeneticoFenoGeno* self, const gchar* i) {
	gint result = 0;
	gint f = 0;
	const gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	GQuark _tmp3_ = 0U;
	static GQuark _tmp2_label0 = 0;
	static GQuark _tmp2_label1 = 0;
	static GQuark _tmp2_label2 = 0;
	static GQuark _tmp2_label3 = 0;
	static GQuark _tmp2_label4 = 0;
	static GQuark _tmp2_label5 = 0;
	static GQuark _tmp2_label6 = 0;
	static GQuark _tmp2_label7 = 0;
	static GQuark _tmp2_label8 = 0;
	static GQuark _tmp2_label9 = 0;
	static GQuark _tmp2_label10 = 0;
	static GQuark _tmp2_label11 = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (i != NULL, 0);
	f = 0;
	_tmp0_ = i;
	_tmp1_ = _tmp0_;
	_tmp3_ = (NULL == _tmp1_) ? 0 : g_quark_from_string (_tmp1_);
	if (_tmp3_ == ((0 != _tmp2_label0) ? _tmp2_label0 : (_tmp2_label0 = g_quark_from_static_string ("R")))) {
		switch (0) {
			default:
			{
				f = 1;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label1) ? _tmp2_label1 : (_tmp2_label1 = g_quark_from_static_string ("R'")))) {
		switch (0) {
			default:
			{
				f = 2;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label2) ? _tmp2_label2 : (_tmp2_label2 = g_quark_from_static_string ("L")))) {
		switch (0) {
			default:
			{
				f = 3;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label3) ? _tmp2_label3 : (_tmp2_label3 = g_quark_from_static_string ("L'")))) {
		switch (0) {
			default:
			{
				f = 4;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label4) ? _tmp2_label4 : (_tmp2_label4 = g_quark_from_static_string ("U")))) {
		switch (0) {
			default:
			{
				f = 5;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label5) ? _tmp2_label5 : (_tmp2_label5 = g_quark_from_static_string ("U'")))) {
		switch (0) {
			default:
			{
				f = 6;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label6) ? _tmp2_label6 : (_tmp2_label6 = g_quark_from_static_string ("D")))) {
		switch (0) {
			default:
			{
				f = 7;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label7) ? _tmp2_label7 : (_tmp2_label7 = g_quark_from_static_string ("D'")))) {
		switch (0) {
			default:
			{
				f = 8;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label8) ? _tmp2_label8 : (_tmp2_label8 = g_quark_from_static_string ("F")))) {
		switch (0) {
			default:
			{
				f = 9;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label9) ? _tmp2_label9 : (_tmp2_label9 = g_quark_from_static_string ("F'")))) {
		switch (0) {
			default:
			{
				f = 10;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label10) ? _tmp2_label10 : (_tmp2_label10 = g_quark_from_static_string ("B")))) {
		switch (0) {
			default:
			{
				f = 11;
				break;
			}
		}
	} else if (_tmp3_ == ((0 != _tmp2_label11) ? _tmp2_label11 : (_tmp2_label11 = g_quark_from_static_string ("B'")))) {
		switch (0) {
			default:
			{
				f = 12;
				break;
			}
		}
	}
	result = f;
	return result;
}


static void cubo_genetico_feno_geno_class_init (CuboGeneticoFenoGenoClass * klass) {
	cubo_genetico_feno_geno_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoFenoGenoPrivate));
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_feno_geno_finalize;
}


static void cubo_genetico_feno_geno_instance_init (CuboGeneticoFenoGeno * self) {
	self->priv = CUBO_GENETICO_FENO_GENO_GET_PRIVATE (self);
}


static void cubo_genetico_feno_geno_finalize (GObject* obj) {
	CuboGeneticoFenoGeno * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_FENO_GENO, CuboGeneticoFenoGeno);
	_g_rand_free0 (self->priv->rand);
	G_OBJECT_CLASS (cubo_genetico_feno_geno_parent_class)->finalize (obj);
}


GType cubo_genetico_feno_geno_get_type (void) {
	static volatile gsize cubo_genetico_feno_geno_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_feno_geno_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoFenoGenoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_feno_geno_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoFenoGeno), 0, (GInstanceInitFunc) cubo_genetico_feno_geno_instance_init, NULL };
		GType cubo_genetico_feno_geno_type_id;
		cubo_genetico_feno_geno_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoFenoGeno", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_feno_geno_type_id__volatile, cubo_genetico_feno_geno_type_id);
	}
	return cubo_genetico_feno_geno_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



