/* Individuo.c generated by valac 0.34.8, the Vala compiler
 * generated from Individuo.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "agenetico.h"
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define CUBO_GENETICO_TYPE_INDIVIDUO (cubo_genetico_individuo_get_type ())
#define CUBO_GENETICO_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuo))
#define CUBO_GENETICO_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuoClass))
#define CUBO_GENETICO_IS_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_IS_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_INDIVIDUO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuoClass))

typedef struct _CuboGeneticoIndividuo CuboGeneticoIndividuo;
typedef struct _CuboGeneticoIndividuoClass CuboGeneticoIndividuoClass;
typedef struct _CuboGeneticoIndividuoPrivate CuboGeneticoIndividuoPrivate;
#define _cubo_genetico_agenetico_genotipo_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_agenetico_genotipo_unref (var), NULL)))
#define _cubo_genetico_agenetico_fenotipo_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_agenetico_fenotipo_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _CuboGeneticoIndividuo {
	GObject parent_instance;
	CuboGeneticoIndividuoPrivate * priv;
};

struct _CuboGeneticoIndividuoClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoIndividuoPrivate {
	CuboGeneticoAGeneticoGenotipo* _genotipo;
	CuboGeneticoAGeneticoFenotipo* _fenotipo;
	gdouble _fitness;
};


static gpointer cubo_genetico_individuo_parent_class = NULL;

GType cubo_genetico_individuo_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_INDIVIDUO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuoPrivate))
enum  {
	CUBO_GENETICO_INDIVIDUO_DUMMY_PROPERTY,
	CUBO_GENETICO_INDIVIDUO_GENOTIPO,
	CUBO_GENETICO_INDIVIDUO_FENOTIPO,
	CUBO_GENETICO_INDIVIDUO_FITNESS
};
gchar* cubo_genetico_individuo_to_string (CuboGeneticoIndividuo* self);
CuboGeneticoAGeneticoFenotipo* cubo_genetico_individuo_get_fenotipo (CuboGeneticoIndividuo* self);
CuboGeneticoAGeneticoGenotipo* cubo_genetico_individuo_get_genotipo (CuboGeneticoIndividuo* self);
gdouble cubo_genetico_individuo_get_fitness (CuboGeneticoIndividuo* self);
CuboGeneticoIndividuo* cubo_genetico_individuo_new (void);
CuboGeneticoIndividuo* cubo_genetico_individuo_construct (GType object_type);
void cubo_genetico_individuo_set_genotipo (CuboGeneticoIndividuo* self, CuboGeneticoAGeneticoGenotipo* value);
void cubo_genetico_individuo_set_fenotipo (CuboGeneticoIndividuo* self, CuboGeneticoAGeneticoFenotipo* value);
void cubo_genetico_individuo_set_fitness (CuboGeneticoIndividuo* self, gdouble value);
static void cubo_genetico_individuo_finalize (GObject* obj);
static void _vala_cubo_genetico_individuo_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_cubo_genetico_individuo_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


gchar* cubo_genetico_individuo_to_string (CuboGeneticoIndividuo* self) {
	gchar* result = NULL;
	gchar* s = NULL;
	CuboGeneticoAGeneticoFenotipo* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gdouble _tmp10_ = 0.0;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	gchar* _tmp16_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_fenotipo;
	_tmp1_ = cubo_genetico_agenetico_fenotipo_to_string (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = self->priv->_genotipo;
	_tmp4_ = cubo_genetico_agenetico_genotipo_to_string (_tmp3_);
	_tmp5_ = _tmp4_;
	_tmp6_ = g_strconcat (_tmp2_, _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_strconcat (_tmp7_, "Fitness : ", NULL);
	_tmp9_ = _tmp8_;
	_tmp10_ = self->priv->_fitness;
	_tmp11_ = double_to_string (_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = g_strconcat (_tmp9_, _tmp12_, NULL);
	_tmp14_ = _tmp13_;
	_tmp15_ = g_strconcat (_tmp14_, "\n", NULL);
	_tmp16_ = _tmp15_;
	_g_free0 (_tmp14_);
	_g_free0 (_tmp12_);
	_g_free0 (_tmp9_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp5_);
	_g_free0 (_tmp2_);
	s = _tmp16_;
	result = s;
	return result;
}


CuboGeneticoIndividuo* cubo_genetico_individuo_construct (GType object_type) {
	CuboGeneticoIndividuo * self = NULL;
	self = (CuboGeneticoIndividuo*) g_object_new (object_type, NULL);
	return self;
}


CuboGeneticoIndividuo* cubo_genetico_individuo_new (void) {
	return cubo_genetico_individuo_construct (CUBO_GENETICO_TYPE_INDIVIDUO);
}


CuboGeneticoAGeneticoGenotipo* cubo_genetico_individuo_get_genotipo (CuboGeneticoIndividuo* self) {
	CuboGeneticoAGeneticoGenotipo* result;
	CuboGeneticoAGeneticoGenotipo* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_genotipo;
	result = _tmp0_;
	return result;
}


static gpointer _cubo_genetico_agenetico_genotipo_ref0 (gpointer self) {
	return self ? cubo_genetico_agenetico_genotipo_ref (self) : NULL;
}


void cubo_genetico_individuo_set_genotipo (CuboGeneticoIndividuo* self, CuboGeneticoAGeneticoGenotipo* value) {
	CuboGeneticoAGeneticoGenotipo* _tmp0_ = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _cubo_genetico_agenetico_genotipo_ref0 (_tmp0_);
	_cubo_genetico_agenetico_genotipo_unref0 (self->priv->_genotipo);
	self->priv->_genotipo = _tmp1_;
	g_object_notify ((GObject *) self, "genotipo");
}


CuboGeneticoAGeneticoFenotipo* cubo_genetico_individuo_get_fenotipo (CuboGeneticoIndividuo* self) {
	CuboGeneticoAGeneticoFenotipo* result;
	CuboGeneticoAGeneticoFenotipo* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_fenotipo;
	result = _tmp0_;
	return result;
}


static gpointer _cubo_genetico_agenetico_fenotipo_ref0 (gpointer self) {
	return self ? cubo_genetico_agenetico_fenotipo_ref (self) : NULL;
}


void cubo_genetico_individuo_set_fenotipo (CuboGeneticoIndividuo* self, CuboGeneticoAGeneticoFenotipo* value) {
	CuboGeneticoAGeneticoFenotipo* _tmp0_ = NULL;
	CuboGeneticoAGeneticoFenotipo* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _cubo_genetico_agenetico_fenotipo_ref0 (_tmp0_);
	_cubo_genetico_agenetico_fenotipo_unref0 (self->priv->_fenotipo);
	self->priv->_fenotipo = _tmp1_;
	g_object_notify ((GObject *) self, "fenotipo");
}


gdouble cubo_genetico_individuo_get_fitness (CuboGeneticoIndividuo* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_fitness;
	result = _tmp0_;
	return result;
}


void cubo_genetico_individuo_set_fitness (CuboGeneticoIndividuo* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_fitness = _tmp0_;
	g_object_notify ((GObject *) self, "fitness");
}


static void cubo_genetico_individuo_class_init (CuboGeneticoIndividuoClass * klass) {
	cubo_genetico_individuo_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoIndividuoPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_cubo_genetico_individuo_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_cubo_genetico_individuo_set_property;
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_individuo_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CUBO_GENETICO_INDIVIDUO_GENOTIPO, cubo_genetico_agenetico_param_spec_genotipo ("genotipo", "genotipo", "genotipo", CUBO_GENETICO_AGENETICO_TYPE_GENOTIPO, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CUBO_GENETICO_INDIVIDUO_FENOTIPO, cubo_genetico_agenetico_param_spec_fenotipo ("fenotipo", "fenotipo", "fenotipo", CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CUBO_GENETICO_INDIVIDUO_FITNESS, g_param_spec_double ("fitness", "fitness", "fitness", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void cubo_genetico_individuo_instance_init (CuboGeneticoIndividuo * self) {
	self->priv = CUBO_GENETICO_INDIVIDUO_GET_PRIVATE (self);
}


static void cubo_genetico_individuo_finalize (GObject* obj) {
	CuboGeneticoIndividuo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuo);
	_cubo_genetico_agenetico_genotipo_unref0 (self->priv->_genotipo);
	_cubo_genetico_agenetico_fenotipo_unref0 (self->priv->_fenotipo);
	G_OBJECT_CLASS (cubo_genetico_individuo_parent_class)->finalize (obj);
}


GType cubo_genetico_individuo_get_type (void) {
	static volatile gsize cubo_genetico_individuo_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_individuo_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoIndividuoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_individuo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoIndividuo), 0, (GInstanceInitFunc) cubo_genetico_individuo_instance_init, NULL };
		GType cubo_genetico_individuo_type_id;
		cubo_genetico_individuo_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoIndividuo", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_individuo_type_id__volatile, cubo_genetico_individuo_type_id);
	}
	return cubo_genetico_individuo_type_id__volatile;
}


static void _vala_cubo_genetico_individuo_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CuboGeneticoIndividuo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuo);
	switch (property_id) {
		case CUBO_GENETICO_INDIVIDUO_GENOTIPO:
		cubo_genetico_agenetico_value_set_genotipo (value, cubo_genetico_individuo_get_genotipo (self));
		break;
		case CUBO_GENETICO_INDIVIDUO_FENOTIPO:
		cubo_genetico_agenetico_value_set_fenotipo (value, cubo_genetico_individuo_get_fenotipo (self));
		break;
		case CUBO_GENETICO_INDIVIDUO_FITNESS:
		g_value_set_double (value, cubo_genetico_individuo_get_fitness (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_cubo_genetico_individuo_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CuboGeneticoIndividuo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuo);
	switch (property_id) {
		case CUBO_GENETICO_INDIVIDUO_GENOTIPO:
		cubo_genetico_individuo_set_genotipo (self, cubo_genetico_agenetico_value_get_genotipo (value));
		break;
		case CUBO_GENETICO_INDIVIDUO_FENOTIPO:
		cubo_genetico_individuo_set_fenotipo (self, cubo_genetico_agenetico_value_get_fenotipo (value));
		break;
		case CUBO_GENETICO_INDIVIDUO_FITNESS:
		cubo_genetico_individuo_set_fitness (self, g_value_get_double (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



