/* Mutacion.c generated by valac 0.34.8, the Vala compiler
 * generated from Mutacion.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include "agenetico.h"


#define CUBO_GENETICO_TYPE_MUTACION (cubo_genetico_mutacion_get_type ())
#define CUBO_GENETICO_MUTACION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_MUTACION, CuboGeneticoMutacion))
#define CUBO_GENETICO_MUTACION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_MUTACION, CuboGeneticoMutacionClass))
#define CUBO_GENETICO_IS_MUTACION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_MUTACION))
#define CUBO_GENETICO_IS_MUTACION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_MUTACION))
#define CUBO_GENETICO_MUTACION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_MUTACION, CuboGeneticoMutacionClass))

typedef struct _CuboGeneticoMutacion CuboGeneticoMutacion;
typedef struct _CuboGeneticoMutacionClass CuboGeneticoMutacionClass;
typedef struct _CuboGeneticoMutacionPrivate CuboGeneticoMutacionPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))
#define _cubo_genetico_agenetico_genotipo_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_agenetico_genotipo_unref (var), NULL)))

struct _CuboGeneticoMutacion {
	GObject parent_instance;
	CuboGeneticoMutacionPrivate * priv;
};

struct _CuboGeneticoMutacionClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoMutacionPrivate {
	gdouble prop;
	GRand* rand;
};


static gpointer cubo_genetico_mutacion_parent_class = NULL;

GType cubo_genetico_mutacion_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_MUTACION_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_MUTACION, CuboGeneticoMutacionPrivate))
enum  {
	CUBO_GENETICO_MUTACION_DUMMY_PROPERTY
};
CuboGeneticoMutacion* cubo_genetico_mutacion_new (gint semilla, gdouble prop);
CuboGeneticoMutacion* cubo_genetico_mutacion_construct (GType object_type, gint semilla, gdouble prop);
CuboGeneticoAGeneticoGenotipo* cubo_genetico_mutacion_muta (CuboGeneticoMutacion* self, CuboGeneticoAGeneticoGenotipo* g);
static void cubo_genetico_mutacion_finalize (GObject* obj);


CuboGeneticoMutacion* cubo_genetico_mutacion_construct (GType object_type, gint semilla, gdouble prop) {
	CuboGeneticoMutacion * self = NULL;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	gdouble _tmp3_ = 0.0;
	self = (CuboGeneticoMutacion*) g_object_new (object_type, NULL);
	_tmp0_ = g_rand_new ();
	_g_rand_free0 (self->priv->rand);
	self->priv->rand = _tmp0_;
	_tmp1_ = self->priv->rand;
	_tmp2_ = semilla;
	g_rand_set_seed (_tmp1_, (guint32) _tmp2_);
	_tmp3_ = prop;
	self->priv->prop = _tmp3_;
	return self;
}


CuboGeneticoMutacion* cubo_genetico_mutacion_new (gint semilla, gdouble prop) {
	return cubo_genetico_mutacion_construct (CUBO_GENETICO_TYPE_MUTACION, semilla, prop);
}


CuboGeneticoAGeneticoGenotipo* cubo_genetico_mutacion_muta (CuboGeneticoMutacion* self, CuboGeneticoAGeneticoGenotipo* g) {
	CuboGeneticoAGeneticoGenotipo* result = NULL;
	CuboGeneticoAGeneticoGenotipo* nuevo = NULL;
	CuboGeneticoAGeneticoGenotipo* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	CuboGeneticoAGeneticoGenotipo* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (g != NULL, NULL);
	_tmp0_ = g;
	_tmp1_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp0_, &_tmp1__length1);
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	_tmp3_ = cubo_genetico_agenetico_genotipo_new (_tmp2__length1);
	nuevo = _tmp3_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp4_ = FALSE;
			_tmp4_ = TRUE;
			while (TRUE) {
				gint _tmp6_ = 0;
				CuboGeneticoAGeneticoGenotipo* _tmp7_ = NULL;
				gint* _tmp8_ = NULL;
				gint _tmp8__length1 = 0;
				gint* _tmp9_ = NULL;
				gint _tmp9__length1 = 0;
				GRand* _tmp10_ = NULL;
				gdouble _tmp11_ = 0.0;
				gdouble _tmp12_ = 0.0;
				if (!_tmp4_) {
					gint _tmp5_ = 0;
					_tmp5_ = i;
					i = _tmp5_ + 1;
				}
				_tmp4_ = FALSE;
				_tmp6_ = i;
				_tmp7_ = g;
				_tmp8_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp7_, &_tmp8__length1);
				_tmp9_ = _tmp8_;
				_tmp9__length1 = _tmp8__length1;
				if (!(_tmp6_ < _tmp9__length1)) {
					break;
				}
				_tmp10_ = self->priv->rand;
				_tmp11_ = g_rand_double (_tmp10_);
				_tmp12_ = self->priv->prop;
				if (_tmp11_ < _tmp12_) {
					CuboGeneticoAGeneticoGenotipo* _tmp13_ = NULL;
					gint* _tmp14_ = NULL;
					gint _tmp14__length1 = 0;
					gint* _tmp15_ = NULL;
					gint _tmp15__length1 = 0;
					gint _tmp16_ = 0;
					GRand* _tmp17_ = NULL;
					gint32 _tmp18_ = 0;
					gint _tmp19_ = 0;
					_tmp13_ = nuevo;
					_tmp14_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp13_, &_tmp14__length1);
					_tmp15_ = _tmp14_;
					_tmp15__length1 = _tmp14__length1;
					_tmp16_ = i;
					_tmp17_ = self->priv->rand;
					_tmp18_ = g_rand_int_range (_tmp17_, (gint32) 1, (gint32) 13);
					_tmp15_[_tmp16_] = (gint) _tmp18_;
					_tmp19_ = _tmp15_[_tmp16_];
				} else {
					CuboGeneticoAGeneticoGenotipo* _tmp20_ = NULL;
					gint* _tmp21_ = NULL;
					gint _tmp21__length1 = 0;
					gint* _tmp22_ = NULL;
					gint _tmp22__length1 = 0;
					gint _tmp23_ = 0;
					CuboGeneticoAGeneticoGenotipo* _tmp24_ = NULL;
					gint* _tmp25_ = NULL;
					gint _tmp25__length1 = 0;
					gint* _tmp26_ = NULL;
					gint _tmp26__length1 = 0;
					gint _tmp27_ = 0;
					gint _tmp28_ = 0;
					gint _tmp29_ = 0;
					_tmp20_ = nuevo;
					_tmp21_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp20_, &_tmp21__length1);
					_tmp22_ = _tmp21_;
					_tmp22__length1 = _tmp21__length1;
					_tmp23_ = i;
					_tmp24_ = g;
					_tmp25_ = cubo_genetico_agenetico_genotipo_get_genotipo (_tmp24_, &_tmp25__length1);
					_tmp26_ = _tmp25_;
					_tmp26__length1 = _tmp25__length1;
					_tmp27_ = i;
					_tmp28_ = _tmp26_[_tmp27_];
					_tmp22_[_tmp23_] = _tmp28_;
					_tmp29_ = _tmp22_[_tmp23_];
				}
			}
		}
	}
	result = nuevo;
	return result;
}


static void cubo_genetico_mutacion_class_init (CuboGeneticoMutacionClass * klass) {
	cubo_genetico_mutacion_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoMutacionPrivate));
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_mutacion_finalize;
}


static void cubo_genetico_mutacion_instance_init (CuboGeneticoMutacion * self) {
	self->priv = CUBO_GENETICO_MUTACION_GET_PRIVATE (self);
}


static void cubo_genetico_mutacion_finalize (GObject* obj) {
	CuboGeneticoMutacion * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_MUTACION, CuboGeneticoMutacion);
	_g_rand_free0 (self->priv->rand);
	G_OBJECT_CLASS (cubo_genetico_mutacion_parent_class)->finalize (obj);
}


GType cubo_genetico_mutacion_get_type (void) {
	static volatile gsize cubo_genetico_mutacion_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_mutacion_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoMutacionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_mutacion_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoMutacion), 0, (GInstanceInitFunc) cubo_genetico_mutacion_instance_init, NULL };
		GType cubo_genetico_mutacion_type_id;
		cubo_genetico_mutacion_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoMutacion", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_mutacion_type_id__volatile, cubo_genetico_mutacion_type_id);
	}
	return cubo_genetico_mutacion_type_id__volatile;
}



