/* SRuleta.c generated by valac 0.34.8, the Vala compiler
 * generated from SRuleta.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "agenetico.h"
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <gobject/gvaluecollector.h>


#define CUBO_GENETICO_TYPE_SRULETA (cubo_genetico_sruleta_get_type ())
#define CUBO_GENETICO_SRULETA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_SRULETA, CuboGeneticoSRuleta))
#define CUBO_GENETICO_SRULETA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_SRULETA, CuboGeneticoSRuletaClass))
#define CUBO_GENETICO_IS_SRULETA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_SRULETA))
#define CUBO_GENETICO_IS_SRULETA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_SRULETA))
#define CUBO_GENETICO_SRULETA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_SRULETA, CuboGeneticoSRuletaClass))

typedef struct _CuboGeneticoSRuleta CuboGeneticoSRuleta;
typedef struct _CuboGeneticoSRuletaClass CuboGeneticoSRuletaClass;
typedef struct _CuboGeneticoSRuletaPrivate CuboGeneticoSRuletaPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))

#define CUBO_GENETICO_TYPE_POBLACION (cubo_genetico_poblacion_get_type ())
#define CUBO_GENETICO_POBLACION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacion))
#define CUBO_GENETICO_POBLACION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacionClass))
#define CUBO_GENETICO_IS_POBLACION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_POBLACION))
#define CUBO_GENETICO_IS_POBLACION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_POBLACION))
#define CUBO_GENETICO_POBLACION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacionClass))

typedef struct _CuboGeneticoPoblacion CuboGeneticoPoblacion;
typedef struct _CuboGeneticoPoblacionClass CuboGeneticoPoblacionClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __g_list_free__g_object_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_object_unref0_ (var), NULL)))
typedef struct _CuboGeneticoParamSpecSRuleta CuboGeneticoParamSpecSRuleta;

struct _CuboGeneticoSRuleta {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CuboGeneticoSRuletaPrivate * priv;
};

struct _CuboGeneticoSRuletaClass {
	GTypeClass parent_class;
	void (*finalize) (CuboGeneticoSRuleta *self);
};

struct _CuboGeneticoSRuletaPrivate {
	GRand* rand;
};

struct _CuboGeneticoParamSpecSRuleta {
	GParamSpec parent_instance;
};


static gpointer cubo_genetico_sruleta_parent_class = NULL;

gpointer cubo_genetico_sruleta_ref (gpointer instance);
void cubo_genetico_sruleta_unref (gpointer instance);
GParamSpec* cubo_genetico_param_spec_sruleta (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_value_set_sruleta (GValue* value, gpointer v_object);
void cubo_genetico_value_take_sruleta (GValue* value, gpointer v_object);
gpointer cubo_genetico_value_get_sruleta (const GValue* value);
GType cubo_genetico_sruleta_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_SRULETA_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_SRULETA, CuboGeneticoSRuletaPrivate))
enum  {
	CUBO_GENETICO_SRULETA_DUMMY_PROPERTY
};
CuboGeneticoSRuleta* cubo_genetico_sruleta_new (gint semilla);
CuboGeneticoSRuleta* cubo_genetico_sruleta_construct (GType object_type, gint semilla);
gpointer cubo_genetico_poblacion_ref (gpointer instance);
void cubo_genetico_poblacion_unref (gpointer instance);
GParamSpec* cubo_genetico_param_spec_poblacion (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_value_set_poblacion (GValue* value, gpointer v_object);
void cubo_genetico_value_take_poblacion (GValue* value, gpointer v_object);
gpointer cubo_genetico_value_get_poblacion (const GValue* value);
GType cubo_genetico_poblacion_get_type (void) G_GNUC_CONST;
GList* cubo_genetico_sruleta_selecciona (CuboGeneticoSRuleta* self, CuboGeneticoPoblacion* p);
gint cubo_genetico_poblacion_getTam (CuboGeneticoPoblacion* self);
CuboGeneticoAGeneticoIndividuo* cubo_genetico_poblacion_getIndividuo (CuboGeneticoPoblacion* self, gint i);
static void _g_object_unref0_ (gpointer var);
static void _g_list_free__g_object_unref0_ (GList* self);
static void cubo_genetico_sruleta_finalize (CuboGeneticoSRuleta* obj);


CuboGeneticoSRuleta* cubo_genetico_sruleta_construct (GType object_type, gint semilla) {
	CuboGeneticoSRuleta* self = NULL;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	self = (CuboGeneticoSRuleta*) g_type_create_instance (object_type);
	_tmp0_ = g_rand_new ();
	_g_rand_free0 (self->priv->rand);
	self->priv->rand = _tmp0_;
	_tmp1_ = self->priv->rand;
	_tmp2_ = semilla;
	g_rand_set_seed (_tmp1_, (guint32) _tmp2_);
	return self;
}


CuboGeneticoSRuleta* cubo_genetico_sruleta_new (gint semilla) {
	return cubo_genetico_sruleta_construct (CUBO_GENETICO_TYPE_SRULETA, semilla);
}


static void _g_object_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (g_object_unref (var), NULL));
}


static void _g_list_free__g_object_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_object_unref0_, NULL);
	g_list_free (self);
}


GList* cubo_genetico_sruleta_selecciona (CuboGeneticoSRuleta* self, CuboGeneticoPoblacion* p) {
	GList* result = NULL;
	gdouble* rango = NULL;
	CuboGeneticoPoblacion* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gdouble* _tmp2_ = NULL;
	gint rango_length1 = 0;
	gint _rango_size_ = 0;
	gdouble* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	CuboGeneticoPoblacion* _tmp4_ = NULL;
	CuboGeneticoAGeneticoIndividuo* _tmp5_ = NULL;
	CuboGeneticoAGeneticoIndividuo* _tmp6_ = NULL;
	gdouble _tmp7_ = 0.0;
	gdouble _tmp8_ = 0.0;
	gdouble _tmp9_ = 0.0;
	GList* l = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (p != NULL, NULL);
	_tmp0_ = p;
	_tmp1_ = cubo_genetico_poblacion_getTam (_tmp0_);
	_tmp2_ = g_new0 (gdouble, _tmp1_);
	rango = _tmp2_;
	rango_length1 = _tmp1_;
	_rango_size_ = rango_length1;
	_tmp3_ = rango;
	_tmp3__length1 = rango_length1;
	_tmp4_ = p;
	_tmp5_ = cubo_genetico_poblacion_getIndividuo (_tmp4_, 0);
	_tmp6_ = _tmp5_;
	_tmp7_ = cubo_genetico_agenetico_individuo_get_fitness (_tmp6_);
	_tmp8_ = _tmp7_;
	_tmp3_[0] = _tmp8_;
	_tmp9_ = _tmp3_[0];
	_g_object_unref0 (_tmp6_);
	{
		gint i = 0;
		i = 1;
		{
			gboolean _tmp10_ = FALSE;
			_tmp10_ = TRUE;
			while (TRUE) {
				gint _tmp12_ = 0;
				CuboGeneticoPoblacion* _tmp13_ = NULL;
				gint _tmp14_ = 0;
				gdouble m = 0.0;
				gdouble* _tmp15_ = NULL;
				gint _tmp15__length1 = 0;
				gint _tmp16_ = 0;
				gdouble _tmp17_ = 0.0;
				CuboGeneticoPoblacion* _tmp18_ = NULL;
				gint _tmp19_ = 0;
				CuboGeneticoAGeneticoIndividuo* _tmp20_ = NULL;
				CuboGeneticoAGeneticoIndividuo* _tmp21_ = NULL;
				gdouble _tmp22_ = 0.0;
				gdouble _tmp23_ = 0.0;
				gdouble _tmp24_ = 0.0;
				gdouble* _tmp25_ = NULL;
				gint _tmp25__length1 = 0;
				gint _tmp26_ = 0;
				gdouble _tmp27_ = 0.0;
				gdouble* _tmp28_ = NULL;
				gint _tmp28__length1 = 0;
				gint _tmp29_ = 0;
				gdouble _tmp30_ = 0.0;
				gdouble _tmp31_ = 0.0;
				if (!_tmp10_) {
					gint _tmp11_ = 0;
					_tmp11_ = i;
					i = _tmp11_ + 1;
				}
				_tmp10_ = FALSE;
				_tmp12_ = i;
				_tmp13_ = p;
				_tmp14_ = cubo_genetico_poblacion_getTam (_tmp13_);
				if (!(_tmp12_ < _tmp14_)) {
					break;
				}
				_tmp15_ = rango;
				_tmp15__length1 = rango_length1;
				_tmp16_ = i;
				_tmp17_ = _tmp15_[_tmp16_ - 1];
				_tmp18_ = p;
				_tmp19_ = i;
				_tmp20_ = cubo_genetico_poblacion_getIndividuo (_tmp18_, _tmp19_);
				_tmp21_ = _tmp20_;
				_tmp22_ = cubo_genetico_agenetico_individuo_get_fitness (_tmp21_);
				_tmp23_ = _tmp22_;
				_tmp24_ = (_tmp17_ / _tmp23_) * 10;
				_g_object_unref0 (_tmp21_);
				m = _tmp24_;
				_tmp25_ = rango;
				_tmp25__length1 = rango_length1;
				_tmp26_ = i;
				_tmp27_ = m;
				_tmp28_ = rango;
				_tmp28__length1 = rango_length1;
				_tmp29_ = i;
				_tmp30_ = _tmp28_[_tmp29_ - 1];
				_tmp25_[_tmp26_] = _tmp27_ + _tmp30_;
				_tmp31_ = _tmp25_[_tmp26_];
			}
		}
	}
	l = NULL;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp32_ = FALSE;
			_tmp32_ = TRUE;
			while (TRUE) {
				gint _tmp34_ = 0;
				gdouble pestania = 0.0;
				GRand* _tmp35_ = NULL;
				gdouble _tmp36_ = 0.0;
				gdouble* _tmp37_ = NULL;
				gint _tmp37__length1 = 0;
				gdouble* _tmp38_ = NULL;
				gint _tmp38__length1 = 0;
				gdouble _tmp39_ = 0.0;
				gint j = 0;
				CuboGeneticoPoblacion* _tmp50_ = NULL;
				gint _tmp51_ = 0;
				CuboGeneticoAGeneticoIndividuo* _tmp52_ = NULL;
				if (!_tmp32_) {
					gint _tmp33_ = 0;
					_tmp33_ = i;
					i = _tmp33_ + 1;
				}
				_tmp32_ = FALSE;
				_tmp34_ = i;
				if (!(_tmp34_ < 2)) {
					break;
				}
				_tmp35_ = self->priv->rand;
				_tmp36_ = g_rand_double (_tmp35_);
				_tmp37_ = rango;
				_tmp37__length1 = rango_length1;
				_tmp38_ = rango;
				_tmp38__length1 = rango_length1;
				_tmp39_ = _tmp37_[_tmp38__length1 - 1];
				pestania = _tmp36_ * _tmp39_;
				j = 0;
				while (TRUE) {
					gdouble* _tmp40_ = NULL;
					gint _tmp40__length1 = 0;
					gint _tmp41_ = 0;
					gdouble _tmp42_ = 0.0;
					gdouble _tmp43_ = 0.0;
					FILE* _tmp44_ = NULL;
					gdouble _tmp45_ = 0.0;
					gdouble* _tmp46_ = NULL;
					gint _tmp46__length1 = 0;
					gint _tmp47_ = 0;
					gdouble _tmp48_ = 0.0;
					gint _tmp49_ = 0;
					_tmp40_ = rango;
					_tmp40__length1 = rango_length1;
					_tmp41_ = j;
					_tmp42_ = _tmp40_[_tmp41_];
					_tmp43_ = pestania;
					if (!(_tmp42_ <= _tmp43_)) {
						break;
					}
					_tmp44_ = stdout;
					_tmp45_ = pestania;
					_tmp46_ = rango;
					_tmp46__length1 = rango_length1;
					_tmp47_ = j;
					_tmp48_ = _tmp46_[_tmp47_];
					fprintf (_tmp44_, "p = %2.9f , r = %2.9f\n", _tmp45_, _tmp48_);
					_tmp49_ = j;
					j = _tmp49_ + 1;
				}
				_tmp50_ = p;
				_tmp51_ = j;
				_tmp52_ = cubo_genetico_poblacion_getIndividuo (_tmp50_, _tmp51_);
				l = g_list_append (l, _tmp52_);
			}
		}
	}
	result = l;
	rango = (g_free (rango), NULL);
	return result;
}


static void cubo_genetico_value_sruleta_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void cubo_genetico_value_sruleta_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		cubo_genetico_sruleta_unref (value->data[0].v_pointer);
	}
}


static void cubo_genetico_value_sruleta_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = cubo_genetico_sruleta_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer cubo_genetico_value_sruleta_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* cubo_genetico_value_sruleta_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		CuboGeneticoSRuleta* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = cubo_genetico_sruleta_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* cubo_genetico_value_sruleta_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	CuboGeneticoSRuleta** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = cubo_genetico_sruleta_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* cubo_genetico_param_spec_sruleta (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	CuboGeneticoParamSpecSRuleta* spec;
	g_return_val_if_fail (g_type_is_a (object_type, CUBO_GENETICO_TYPE_SRULETA), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer cubo_genetico_value_get_sruleta (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TYPE_SRULETA), NULL);
	return value->data[0].v_pointer;
}


void cubo_genetico_value_set_sruleta (GValue* value, gpointer v_object) {
	CuboGeneticoSRuleta* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TYPE_SRULETA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_TYPE_SRULETA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		cubo_genetico_sruleta_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_sruleta_unref (old);
	}
}


void cubo_genetico_value_take_sruleta (GValue* value, gpointer v_object) {
	CuboGeneticoSRuleta* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TYPE_SRULETA));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_TYPE_SRULETA));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_sruleta_unref (old);
	}
}


static void cubo_genetico_sruleta_class_init (CuboGeneticoSRuletaClass * klass) {
	cubo_genetico_sruleta_parent_class = g_type_class_peek_parent (klass);
	((CuboGeneticoSRuletaClass *) klass)->finalize = cubo_genetico_sruleta_finalize;
	g_type_class_add_private (klass, sizeof (CuboGeneticoSRuletaPrivate));
}


static void cubo_genetico_sruleta_instance_init (CuboGeneticoSRuleta * self) {
	self->priv = CUBO_GENETICO_SRULETA_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void cubo_genetico_sruleta_finalize (CuboGeneticoSRuleta* obj) {
	CuboGeneticoSRuleta * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_SRULETA, CuboGeneticoSRuleta);
	g_signal_handlers_destroy (self);
	_g_rand_free0 (self->priv->rand);
}


GType cubo_genetico_sruleta_get_type (void) {
	static volatile gsize cubo_genetico_sruleta_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_sruleta_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { cubo_genetico_value_sruleta_init, cubo_genetico_value_sruleta_free_value, cubo_genetico_value_sruleta_copy_value, cubo_genetico_value_sruleta_peek_pointer, "p", cubo_genetico_value_sruleta_collect_value, "p", cubo_genetico_value_sruleta_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoSRuletaClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_sruleta_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoSRuleta), 0, (GInstanceInitFunc) cubo_genetico_sruleta_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType cubo_genetico_sruleta_type_id;
		cubo_genetico_sruleta_type_id = g_type_register_fundamental (g_type_fundamental_next (), "CuboGeneticoSRuleta", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&cubo_genetico_sruleta_type_id__volatile, cubo_genetico_sruleta_type_id);
	}
	return cubo_genetico_sruleta_type_id__volatile;
}


gpointer cubo_genetico_sruleta_ref (gpointer instance) {
	CuboGeneticoSRuleta* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void cubo_genetico_sruleta_unref (gpointer instance) {
	CuboGeneticoSRuleta* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		CUBO_GENETICO_SRULETA_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



