/* STorneo.c generated by valac 0.34.8, the Vala compiler
 * generated from STorneo.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "agenetico.h"
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define CUBO_GENETICO_TYPE_STORNEO (cubo_genetico_storneo_get_type ())
#define CUBO_GENETICO_STORNEO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_STORNEO, CuboGeneticoSTorneo))
#define CUBO_GENETICO_STORNEO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_STORNEO, CuboGeneticoSTorneoClass))
#define CUBO_GENETICO_IS_STORNEO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_STORNEO))
#define CUBO_GENETICO_IS_STORNEO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_STORNEO))
#define CUBO_GENETICO_STORNEO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_STORNEO, CuboGeneticoSTorneoClass))

typedef struct _CuboGeneticoSTorneo CuboGeneticoSTorneo;
typedef struct _CuboGeneticoSTorneoClass CuboGeneticoSTorneoClass;
typedef struct _CuboGeneticoSTorneoPrivate CuboGeneticoSTorneoPrivate;
#define _g_rand_free0(var) ((var == NULL) ? NULL : (var = (g_rand_free (var), NULL)))

#define CUBO_GENETICO_TYPE_POBLACION (cubo_genetico_poblacion_get_type ())
#define CUBO_GENETICO_POBLACION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacion))
#define CUBO_GENETICO_POBLACION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacionClass))
#define CUBO_GENETICO_IS_POBLACION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_POBLACION))
#define CUBO_GENETICO_IS_POBLACION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_POBLACION))
#define CUBO_GENETICO_POBLACION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_POBLACION, CuboGeneticoPoblacionClass))

typedef struct _CuboGeneticoPoblacion CuboGeneticoPoblacion;
typedef struct _CuboGeneticoPoblacionClass CuboGeneticoPoblacionClass;

#define CUBO_GENETICO_TYPE_INDIVIDUO (cubo_genetico_individuo_get_type ())
#define CUBO_GENETICO_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuo))
#define CUBO_GENETICO_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuoClass))
#define CUBO_GENETICO_IS_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_IS_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_INDIVIDUO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TYPE_INDIVIDUO, CuboGeneticoIndividuoClass))

typedef struct _CuboGeneticoIndividuo CuboGeneticoIndividuo;
typedef struct _CuboGeneticoIndividuoClass CuboGeneticoIndividuoClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __g_list_free__cubo_genetico_agenetico_genotipo_unref0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (var), NULL)))
typedef struct _CuboGeneticoParamSpecSTorneo CuboGeneticoParamSpecSTorneo;

struct _CuboGeneticoSTorneo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CuboGeneticoSTorneoPrivate * priv;
};

struct _CuboGeneticoSTorneoClass {
	GTypeClass parent_class;
	void (*finalize) (CuboGeneticoSTorneo *self);
};

struct _CuboGeneticoSTorneoPrivate {
	GRand* rand;
};

struct _CuboGeneticoParamSpecSTorneo {
	GParamSpec parent_instance;
};


static gpointer cubo_genetico_storneo_parent_class = NULL;

gpointer cubo_genetico_storneo_ref (gpointer instance);
void cubo_genetico_storneo_unref (gpointer instance);
GParamSpec* cubo_genetico_param_spec_storneo (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_value_set_storneo (GValue* value, gpointer v_object);
void cubo_genetico_value_take_storneo (GValue* value, gpointer v_object);
gpointer cubo_genetico_value_get_storneo (const GValue* value);
GType cubo_genetico_storneo_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_STORNEO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TYPE_STORNEO, CuboGeneticoSTorneoPrivate))
enum  {
	CUBO_GENETICO_STORNEO_DUMMY_PROPERTY
};
CuboGeneticoSTorneo* cubo_genetico_storneo_new (gint semilla);
CuboGeneticoSTorneo* cubo_genetico_storneo_construct (GType object_type, gint semilla);
gpointer cubo_genetico_poblacion_ref (gpointer instance);
void cubo_genetico_poblacion_unref (gpointer instance);
GParamSpec* cubo_genetico_param_spec_poblacion (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_value_set_poblacion (GValue* value, gpointer v_object);
void cubo_genetico_value_take_poblacion (GValue* value, gpointer v_object);
gpointer cubo_genetico_value_get_poblacion (const GValue* value);
GType cubo_genetico_poblacion_get_type (void) G_GNUC_CONST;
GList* cubo_genetico_storneo_selecciona (CuboGeneticoSTorneo* self, CuboGeneticoPoblacion* p);
GType cubo_genetico_individuo_get_type (void) G_GNUC_CONST;
CuboGeneticoIndividuo* cubo_genetico_poblacion_getIndividuo (CuboGeneticoPoblacion* self, gint i);
gint cubo_genetico_poblacion_getTam (CuboGeneticoPoblacion* self);
gdouble cubo_genetico_individuo_get_fitness (CuboGeneticoIndividuo* self);
CuboGeneticoAGeneticoGenotipo* cubo_genetico_individuo_get_genotipo (CuboGeneticoIndividuo* self);
static void _cubo_genetico_agenetico_genotipo_unref0_ (gpointer var);
static void _g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (GList* self);
static void cubo_genetico_storneo_finalize (CuboGeneticoSTorneo* obj);


CuboGeneticoSTorneo* cubo_genetico_storneo_construct (GType object_type, gint semilla) {
	CuboGeneticoSTorneo* self = NULL;
	GRand* _tmp0_ = NULL;
	GRand* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	self = (CuboGeneticoSTorneo*) g_type_create_instance (object_type);
	_tmp0_ = g_rand_new ();
	_g_rand_free0 (self->priv->rand);
	self->priv->rand = _tmp0_;
	_tmp1_ = self->priv->rand;
	_tmp2_ = semilla;
	g_rand_set_seed (_tmp1_, (guint32) _tmp2_);
	return self;
}


CuboGeneticoSTorneo* cubo_genetico_storneo_new (gint semilla) {
	return cubo_genetico_storneo_construct (CUBO_GENETICO_TYPE_STORNEO, semilla);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gpointer _cubo_genetico_agenetico_genotipo_ref0 (gpointer self) {
	return self ? cubo_genetico_agenetico_genotipo_ref (self) : NULL;
}


static void _cubo_genetico_agenetico_genotipo_unref0_ (gpointer var) {
	(var == NULL) ? NULL : (var = (cubo_genetico_agenetico_genotipo_unref (var), NULL));
}


static void _g_list_free__cubo_genetico_agenetico_genotipo_unref0_ (GList* self) {
	g_list_foreach (self, (GFunc) _cubo_genetico_agenetico_genotipo_unref0_, NULL);
	g_list_free (self);
}


GList* cubo_genetico_storneo_selecciona (CuboGeneticoSTorneo* self, CuboGeneticoPoblacion* p) {
	GList* result = NULL;
	GList* l = NULL;
	gint i = 0;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (p != NULL, NULL);
	l = NULL;
	i = 0;
	while (TRUE) {
		gint _tmp0_ = 0;
		CuboGeneticoIndividuo* i1 = NULL;
		CuboGeneticoPoblacion* _tmp1_ = NULL;
		GRand* _tmp2_ = NULL;
		CuboGeneticoPoblacion* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint32 _tmp5_ = 0;
		CuboGeneticoIndividuo* _tmp6_ = NULL;
		CuboGeneticoIndividuo* i2 = NULL;
		CuboGeneticoPoblacion* _tmp7_ = NULL;
		GRand* _tmp8_ = NULL;
		CuboGeneticoPoblacion* _tmp9_ = NULL;
		gint _tmp10_ = 0;
		gint32 _tmp11_ = 0;
		CuboGeneticoIndividuo* _tmp12_ = NULL;
		CuboGeneticoIndividuo* i3 = NULL;
		CuboGeneticoPoblacion* _tmp13_ = NULL;
		GRand* _tmp14_ = NULL;
		CuboGeneticoPoblacion* _tmp15_ = NULL;
		gint _tmp16_ = 0;
		gint32 _tmp17_ = 0;
		CuboGeneticoIndividuo* _tmp18_ = NULL;
		CuboGeneticoIndividuo* i4 = NULL;
		CuboGeneticoPoblacion* _tmp19_ = NULL;
		GRand* _tmp20_ = NULL;
		CuboGeneticoPoblacion* _tmp21_ = NULL;
		gint _tmp22_ = 0;
		gint32 _tmp23_ = 0;
		CuboGeneticoIndividuo* _tmp24_ = NULL;
		CuboGeneticoIndividuo* mejor = NULL;
		CuboGeneticoIndividuo* _tmp25_ = NULL;
		gdouble _tmp26_ = 0.0;
		gdouble _tmp27_ = 0.0;
		CuboGeneticoIndividuo* _tmp28_ = NULL;
		gdouble _tmp29_ = 0.0;
		gdouble _tmp30_ = 0.0;
		CuboGeneticoIndividuo* _tmp35_ = NULL;
		gdouble _tmp36_ = 0.0;
		gdouble _tmp37_ = 0.0;
		CuboGeneticoIndividuo* _tmp38_ = NULL;
		gdouble _tmp39_ = 0.0;
		gdouble _tmp40_ = 0.0;
		CuboGeneticoIndividuo* _tmp43_ = NULL;
		gdouble _tmp44_ = 0.0;
		gdouble _tmp45_ = 0.0;
		CuboGeneticoIndividuo* _tmp46_ = NULL;
		gdouble _tmp47_ = 0.0;
		gdouble _tmp48_ = 0.0;
		CuboGeneticoIndividuo* _tmp51_ = NULL;
		CuboGeneticoAGeneticoGenotipo* _tmp52_ = NULL;
		CuboGeneticoAGeneticoGenotipo* _tmp53_ = NULL;
		CuboGeneticoAGeneticoGenotipo* _tmp54_ = NULL;
		gint _tmp55_ = 0;
		_tmp0_ = i;
		if (!(_tmp0_ < 2)) {
			break;
		}
		_tmp1_ = p;
		_tmp2_ = self->priv->rand;
		_tmp3_ = p;
		_tmp4_ = cubo_genetico_poblacion_getTam (_tmp3_);
		_tmp5_ = g_rand_int_range (_tmp2_, (gint32) 0, (gint32) _tmp4_);
		_tmp6_ = cubo_genetico_poblacion_getIndividuo (_tmp1_, (gint) _tmp5_);
		i1 = _tmp6_;
		_tmp7_ = p;
		_tmp8_ = self->priv->rand;
		_tmp9_ = p;
		_tmp10_ = cubo_genetico_poblacion_getTam (_tmp9_);
		_tmp11_ = g_rand_int_range (_tmp8_, (gint32) 0, (gint32) _tmp10_);
		_tmp12_ = cubo_genetico_poblacion_getIndividuo (_tmp7_, (gint) _tmp11_);
		i2 = _tmp12_;
		_tmp13_ = p;
		_tmp14_ = self->priv->rand;
		_tmp15_ = p;
		_tmp16_ = cubo_genetico_poblacion_getTam (_tmp15_);
		_tmp17_ = g_rand_int_range (_tmp14_, (gint32) 0, (gint32) _tmp16_);
		_tmp18_ = cubo_genetico_poblacion_getIndividuo (_tmp13_, (gint) _tmp17_);
		i3 = _tmp18_;
		_tmp19_ = p;
		_tmp20_ = self->priv->rand;
		_tmp21_ = p;
		_tmp22_ = cubo_genetico_poblacion_getTam (_tmp21_);
		_tmp23_ = g_rand_int_range (_tmp20_, (gint32) 0, (gint32) _tmp22_);
		_tmp24_ = cubo_genetico_poblacion_getIndividuo (_tmp19_, (gint) _tmp23_);
		i4 = _tmp24_;
		mejor = NULL;
		_tmp25_ = i1;
		_tmp26_ = cubo_genetico_individuo_get_fitness (_tmp25_);
		_tmp27_ = _tmp26_;
		_tmp28_ = i2;
		_tmp29_ = cubo_genetico_individuo_get_fitness (_tmp28_);
		_tmp30_ = _tmp29_;
		if (_tmp27_ <= _tmp30_) {
			CuboGeneticoIndividuo* _tmp31_ = NULL;
			CuboGeneticoIndividuo* _tmp32_ = NULL;
			_tmp31_ = i1;
			_tmp32_ = _g_object_ref0 (_tmp31_);
			_g_object_unref0 (mejor);
			mejor = _tmp32_;
		} else {
			CuboGeneticoIndividuo* _tmp33_ = NULL;
			CuboGeneticoIndividuo* _tmp34_ = NULL;
			_tmp33_ = i2;
			_tmp34_ = _g_object_ref0 (_tmp33_);
			_g_object_unref0 (mejor);
			mejor = _tmp34_;
		}
		_tmp35_ = i3;
		_tmp36_ = cubo_genetico_individuo_get_fitness (_tmp35_);
		_tmp37_ = _tmp36_;
		_tmp38_ = mejor;
		_tmp39_ = cubo_genetico_individuo_get_fitness (_tmp38_);
		_tmp40_ = _tmp39_;
		if (_tmp37_ <= _tmp40_) {
			CuboGeneticoIndividuo* _tmp41_ = NULL;
			CuboGeneticoIndividuo* _tmp42_ = NULL;
			_tmp41_ = i3;
			_tmp42_ = _g_object_ref0 (_tmp41_);
			_g_object_unref0 (mejor);
			mejor = _tmp42_;
		}
		_tmp43_ = i4;
		_tmp44_ = cubo_genetico_individuo_get_fitness (_tmp43_);
		_tmp45_ = _tmp44_;
		_tmp46_ = mejor;
		_tmp47_ = cubo_genetico_individuo_get_fitness (_tmp46_);
		_tmp48_ = _tmp47_;
		if (_tmp45_ <= _tmp48_) {
			CuboGeneticoIndividuo* _tmp49_ = NULL;
			CuboGeneticoIndividuo* _tmp50_ = NULL;
			_tmp49_ = i4;
			_tmp50_ = _g_object_ref0 (_tmp49_);
			_g_object_unref0 (mejor);
			mejor = _tmp50_;
		}
		_tmp51_ = mejor;
		_tmp52_ = cubo_genetico_individuo_get_genotipo (_tmp51_);
		_tmp53_ = _tmp52_;
		_tmp54_ = _cubo_genetico_agenetico_genotipo_ref0 (_tmp53_);
		l = g_list_append (l, _tmp54_);
		_tmp55_ = i;
		i = _tmp55_ + 1;
		_g_object_unref0 (mejor);
		_g_object_unref0 (i4);
		_g_object_unref0 (i3);
		_g_object_unref0 (i2);
		_g_object_unref0 (i1);
	}
	result = l;
	return result;
}


static void cubo_genetico_value_storneo_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void cubo_genetico_value_storneo_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		cubo_genetico_storneo_unref (value->data[0].v_pointer);
	}
}


static void cubo_genetico_value_storneo_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = cubo_genetico_storneo_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer cubo_genetico_value_storneo_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* cubo_genetico_value_storneo_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		CuboGeneticoSTorneo* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = cubo_genetico_storneo_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* cubo_genetico_value_storneo_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	CuboGeneticoSTorneo** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = cubo_genetico_storneo_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* cubo_genetico_param_spec_storneo (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	CuboGeneticoParamSpecSTorneo* spec;
	g_return_val_if_fail (g_type_is_a (object_type, CUBO_GENETICO_TYPE_STORNEO), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer cubo_genetico_value_get_storneo (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TYPE_STORNEO), NULL);
	return value->data[0].v_pointer;
}


void cubo_genetico_value_set_storneo (GValue* value, gpointer v_object) {
	CuboGeneticoSTorneo* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TYPE_STORNEO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_TYPE_STORNEO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		cubo_genetico_storneo_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_storneo_unref (old);
	}
}


void cubo_genetico_value_take_storneo (GValue* value, gpointer v_object) {
	CuboGeneticoSTorneo* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TYPE_STORNEO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_TYPE_STORNEO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_storneo_unref (old);
	}
}


static void cubo_genetico_storneo_class_init (CuboGeneticoSTorneoClass * klass) {
	cubo_genetico_storneo_parent_class = g_type_class_peek_parent (klass);
	((CuboGeneticoSTorneoClass *) klass)->finalize = cubo_genetico_storneo_finalize;
	g_type_class_add_private (klass, sizeof (CuboGeneticoSTorneoPrivate));
}


static void cubo_genetico_storneo_instance_init (CuboGeneticoSTorneo * self) {
	self->priv = CUBO_GENETICO_STORNEO_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void cubo_genetico_storneo_finalize (CuboGeneticoSTorneo* obj) {
	CuboGeneticoSTorneo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TYPE_STORNEO, CuboGeneticoSTorneo);
	g_signal_handlers_destroy (self);
	_g_rand_free0 (self->priv->rand);
}


GType cubo_genetico_storneo_get_type (void) {
	static volatile gsize cubo_genetico_storneo_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_storneo_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { cubo_genetico_value_storneo_init, cubo_genetico_value_storneo_free_value, cubo_genetico_value_storneo_copy_value, cubo_genetico_value_storneo_peek_pointer, "p", cubo_genetico_value_storneo_collect_value, "p", cubo_genetico_value_storneo_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoSTorneoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_storneo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoSTorneo), 0, (GInstanceInitFunc) cubo_genetico_storneo_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType cubo_genetico_storneo_type_id;
		cubo_genetico_storneo_type_id = g_type_register_fundamental (g_type_fundamental_next (), "CuboGeneticoSTorneo", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&cubo_genetico_storneo_type_id__volatile, cubo_genetico_storneo_type_id);
	}
	return cubo_genetico_storneo_type_id__volatile;
}


gpointer cubo_genetico_storneo_ref (gpointer instance) {
	CuboGeneticoSTorneo* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void cubo_genetico_storneo_unref (gpointer instance) {
	CuboGeneticoSTorneo* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		CUBO_GENETICO_STORNEO_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



