/* FFitness.c generated by valac 0.34.8, the Vala compiler
 * generated from FFitness.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include "cubo.h"


#define CUBO_GENETICO_FUNCION_TYPE_FFITNESS (cubo_genetico_funcion_ffitness_get_type ())
#define CUBO_GENETICO_FUNCION_FFITNESS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_FUNCION_TYPE_FFITNESS, CuboGeneticoFuncionFFitness))
#define CUBO_GENETICO_FUNCION_FFITNESS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_FUNCION_TYPE_FFITNESS, CuboGeneticoFuncionFFitnessClass))
#define CUBO_GENETICO_FUNCION_IS_FFITNESS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_FUNCION_TYPE_FFITNESS))
#define CUBO_GENETICO_FUNCION_IS_FFITNESS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_FUNCION_TYPE_FFITNESS))
#define CUBO_GENETICO_FUNCION_FFITNESS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_FUNCION_TYPE_FFITNESS, CuboGeneticoFuncionFFitnessClass))

typedef struct _CuboGeneticoFuncionFFitness CuboGeneticoFuncionFFitness;
typedef struct _CuboGeneticoFuncionFFitnessClass CuboGeneticoFuncionFFitnessClass;
typedef struct _CuboGeneticoFuncionFFitnessPrivate CuboGeneticoFuncionFFitnessPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _CuboGeneticoFuncionFFitness {
	GObject parent_instance;
	CuboGeneticoFuncionFFitnessPrivate * priv;
};

struct _CuboGeneticoFuncionFFitnessClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoFuncionFFitnessPrivate {
	CuboGeneticoCuboCubo3x3* _cubo;
};


static gpointer cubo_genetico_funcion_ffitness_parent_class = NULL;

GType cubo_genetico_funcion_ffitness_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_FUNCION_FFITNESS_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_FUNCION_TYPE_FFITNESS, CuboGeneticoFuncionFFitnessPrivate))
enum  {
	CUBO_GENETICO_FUNCION_FFITNESS_DUMMY_PROPERTY,
	CUBO_GENETICO_FUNCION_FFITNESS_CUBO
};
CuboGeneticoFuncionFFitness* cubo_genetico_funcion_ffitness_new (void);
CuboGeneticoFuncionFFitness* cubo_genetico_funcion_ffitness_construct (GType object_type);
CuboGeneticoCuboCubo3x3* cubo_genetico_funcion_ffitness_get_cubo (CuboGeneticoFuncionFFitness* self);
void cubo_genetico_funcion_ffitness_set_cubo (CuboGeneticoFuncionFFitness* self, CuboGeneticoCuboCubo3x3* value);
static void cubo_genetico_funcion_ffitness_finalize (GObject* obj);
static void _vala_cubo_genetico_funcion_ffitness_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_cubo_genetico_funcion_ffitness_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


CuboGeneticoFuncionFFitness* cubo_genetico_funcion_ffitness_construct (GType object_type) {
	CuboGeneticoFuncionFFitness * self = NULL;
	self = (CuboGeneticoFuncionFFitness*) g_object_new (object_type, NULL);
	return self;
}


CuboGeneticoFuncionFFitness* cubo_genetico_funcion_ffitness_new (void) {
	return cubo_genetico_funcion_ffitness_construct (CUBO_GENETICO_FUNCION_TYPE_FFITNESS);
}


CuboGeneticoCuboCubo3x3* cubo_genetico_funcion_ffitness_get_cubo (CuboGeneticoFuncionFFitness* self) {
	CuboGeneticoCuboCubo3x3* result;
	CuboGeneticoCuboCubo3x3* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_cubo;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void cubo_genetico_funcion_ffitness_set_cubo (CuboGeneticoFuncionFFitness* self, CuboGeneticoCuboCubo3x3* value) {
	CuboGeneticoCuboCubo3x3* _tmp0_ = NULL;
	CuboGeneticoCuboCubo3x3* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_cubo);
	self->priv->_cubo = _tmp1_;
	g_object_notify ((GObject *) self, "cubo");
}


static void cubo_genetico_funcion_ffitness_class_init (CuboGeneticoFuncionFFitnessClass * klass) {
	cubo_genetico_funcion_ffitness_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoFuncionFFitnessPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_cubo_genetico_funcion_ffitness_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_cubo_genetico_funcion_ffitness_set_property;
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_funcion_ffitness_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CUBO_GENETICO_FUNCION_FFITNESS_CUBO, g_param_spec_object ("cubo", "cubo", "cubo", CUBO_GENETICO_CUBO_TYPE_CUBO3X3, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void cubo_genetico_funcion_ffitness_instance_init (CuboGeneticoFuncionFFitness * self) {
	self->priv = CUBO_GENETICO_FUNCION_FFITNESS_GET_PRIVATE (self);
}


static void cubo_genetico_funcion_ffitness_finalize (GObject* obj) {
	CuboGeneticoFuncionFFitness * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_FUNCION_TYPE_FFITNESS, CuboGeneticoFuncionFFitness);
	_g_object_unref0 (self->priv->_cubo);
	G_OBJECT_CLASS (cubo_genetico_funcion_ffitness_parent_class)->finalize (obj);
}


GType cubo_genetico_funcion_ffitness_get_type (void) {
	static volatile gsize cubo_genetico_funcion_ffitness_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_funcion_ffitness_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoFuncionFFitnessClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_funcion_ffitness_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoFuncionFFitness), 0, (GInstanceInitFunc) cubo_genetico_funcion_ffitness_instance_init, NULL };
		GType cubo_genetico_funcion_ffitness_type_id;
		cubo_genetico_funcion_ffitness_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoFuncionFFitness", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_funcion_ffitness_type_id__volatile, cubo_genetico_funcion_ffitness_type_id);
	}
	return cubo_genetico_funcion_ffitness_type_id__volatile;
}


static void _vala_cubo_genetico_funcion_ffitness_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CuboGeneticoFuncionFFitness * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CUBO_GENETICO_FUNCION_TYPE_FFITNESS, CuboGeneticoFuncionFFitness);
	switch (property_id) {
		case CUBO_GENETICO_FUNCION_FFITNESS_CUBO:
		g_value_set_object (value, cubo_genetico_funcion_ffitness_get_cubo (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_cubo_genetico_funcion_ffitness_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CuboGeneticoFuncionFFitness * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CUBO_GENETICO_FUNCION_TYPE_FFITNESS, CuboGeneticoFuncionFFitness);
	switch (property_id) {
		case CUBO_GENETICO_FUNCION_FFITNESS_CUBO:
		cubo_genetico_funcion_ffitness_set_cubo (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



