/* test-case.c generated by valac 0.34.8, the Vala compiler
 * generated from test-case.vala, do not modify */

/* test-case.vala
 *
 * Copyright © 2009 Julien Peeters
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.

 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.

 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 *
 * Author:
 *    Julien Peeters <contact@julienpeeters.fr>
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define CUBO_GENETICO_TEST_TYPE_TEST_CASE (cubo_genetico_test_test_case_get_type ())
#define CUBO_GENETICO_TEST_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CASE, CuboGeneticoTestTestCase))
#define CUBO_GENETICO_TEST_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CASE, CuboGeneticoTestTestCaseClass))
#define CUBO_GENETICO_TEST_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CASE))
#define CUBO_GENETICO_TEST_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CASE))
#define CUBO_GENETICO_TEST_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CASE, CuboGeneticoTestTestCaseClass))

typedef struct _CuboGeneticoTestTestCase CuboGeneticoTestTestCase;
typedef struct _CuboGeneticoTestTestCaseClass CuboGeneticoTestTestCaseClass;
typedef struct _CuboGeneticoTestTestCasePrivate CuboGeneticoTestTestCasePrivate;

#define CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR (cubo_genetico_test_test_case_adaptor_get_type ())
#define CUBO_GENETICO_TEST_TEST_CASE_ADAPTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR, CuboGeneticoTestTestCaseAdaptor))
#define CUBO_GENETICO_TEST_TEST_CASE_ADAPTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR, CuboGeneticoTestTestCaseAdaptorClass))
#define CUBO_GENETICO_TEST_TEST_CASE_IS_ADAPTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR))
#define CUBO_GENETICO_TEST_TEST_CASE_IS_ADAPTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR))
#define CUBO_GENETICO_TEST_TEST_CASE_ADAPTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR, CuboGeneticoTestTestCaseAdaptorClass))

typedef struct _CuboGeneticoTestTestCaseAdaptor CuboGeneticoTestTestCaseAdaptor;
typedef struct _CuboGeneticoTestTestCaseAdaptorClass CuboGeneticoTestTestCaseAdaptorClass;
#define _cubo_genetico_test_test_case_adaptor_unref0(var) ((var == NULL) ? NULL : (var = (cubo_genetico_test_test_case_adaptor_unref (var), NULL)))
typedef struct _CuboGeneticoTestTestCaseAdaptorPrivate CuboGeneticoTestTestCaseAdaptorPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _CuboGeneticoTestTestCaseParamSpecAdaptor CuboGeneticoTestTestCaseParamSpecAdaptor;

struct _CuboGeneticoTestTestCase {
	GObject parent_instance;
	CuboGeneticoTestTestCasePrivate * priv;
};

struct _CuboGeneticoTestTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (CuboGeneticoTestTestCase* self);
	void (*tear_down) (CuboGeneticoTestTestCase* self);
};

struct _CuboGeneticoTestTestCasePrivate {
	GTestSuite* suite;
	CuboGeneticoTestTestCaseAdaptor** adaptors;
	gint adaptors_length1;
	gint _adaptors_size_;
};

typedef void (*CuboGeneticoTestTestCaseTestMethod) (void* user_data);
struct _CuboGeneticoTestTestCaseAdaptor {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CuboGeneticoTestTestCaseAdaptorPrivate * priv;
};

struct _CuboGeneticoTestTestCaseAdaptorClass {
	GTypeClass parent_class;
	void (*finalize) (CuboGeneticoTestTestCaseAdaptor *self);
};

struct _CuboGeneticoTestTestCaseAdaptorPrivate {
	gchar* _name;
	CuboGeneticoTestTestCaseTestMethod test;
	gpointer test_target;
	GDestroyNotify test_target_destroy_notify;
	CuboGeneticoTestTestCase* test_case;
};

struct _CuboGeneticoTestTestCaseParamSpecAdaptor {
	GParamSpec parent_instance;
};


static gpointer cubo_genetico_test_test_case_parent_class = NULL;
static gpointer cubo_genetico_test_test_case_adaptor_parent_class = NULL;

GType cubo_genetico_test_test_case_get_type (void) G_GNUC_CONST;
static gpointer cubo_genetico_test_test_case_adaptor_ref (gpointer instance);
static void cubo_genetico_test_test_case_adaptor_unref (gpointer instance);
static GParamSpec* cubo_genetico_test_test_case_param_spec_adaptor (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) G_GNUC_UNUSED;
static void cubo_genetico_test_test_case_value_set_adaptor (GValue* value, gpointer v_object) G_GNUC_UNUSED;
static void cubo_genetico_test_test_case_value_take_adaptor (GValue* value, gpointer v_object) G_GNUC_UNUSED;
static gpointer cubo_genetico_test_test_case_value_get_adaptor (const GValue* value) G_GNUC_UNUSED;
static GType cubo_genetico_test_test_case_adaptor_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
#define CUBO_GENETICO_TEST_TEST_CASE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TEST_TYPE_TEST_CASE, CuboGeneticoTestTestCasePrivate))
enum  {
	CUBO_GENETICO_TEST_TEST_CASE_DUMMY_PROPERTY
};
CuboGeneticoTestTestCase* cubo_genetico_test_test_case_construct (GType object_type, const gchar* name);
void cubo_genetico_test_test_case_add_test (CuboGeneticoTestTestCase* self, const gchar* name, CuboGeneticoTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify);
static CuboGeneticoTestTestCaseAdaptor* cubo_genetico_test_test_case_adaptor_new (const gchar* name, CuboGeneticoTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify, CuboGeneticoTestTestCase* test_case);
static CuboGeneticoTestTestCaseAdaptor* cubo_genetico_test_test_case_adaptor_construct (GType object_type, const gchar* name, CuboGeneticoTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify, CuboGeneticoTestTestCase* test_case);
static void _vala_array_add1 (CuboGeneticoTestTestCaseAdaptor*** array, int* length, int* size, CuboGeneticoTestTestCaseAdaptor* value);
static const gchar* cubo_genetico_test_test_case_adaptor_get_name (CuboGeneticoTestTestCaseAdaptor* self);
static void cubo_genetico_test_test_case_adaptor_set_up (CuboGeneticoTestTestCaseAdaptor* self, void* fixture);
static void _cubo_genetico_test_test_case_adaptor_set_up_gtest_fixture_func (void* fixture, gpointer self);
static void cubo_genetico_test_test_case_adaptor_run (CuboGeneticoTestTestCaseAdaptor* self, void* fixture);
static void _cubo_genetico_test_test_case_adaptor_run_gtest_fixture_func (void* fixture, gpointer self);
static void cubo_genetico_test_test_case_adaptor_tear_down (CuboGeneticoTestTestCaseAdaptor* self, void* fixture);
static void _cubo_genetico_test_test_case_adaptor_tear_down_gtest_fixture_func (void* fixture, gpointer self);
void cubo_genetico_test_test_case_set_up (CuboGeneticoTestTestCase* self);
static void cubo_genetico_test_test_case_real_set_up (CuboGeneticoTestTestCase* self);
void cubo_genetico_test_test_case_tear_down (CuboGeneticoTestTestCase* self);
static void cubo_genetico_test_test_case_real_tear_down (CuboGeneticoTestTestCase* self);
GTestSuite* cubo_genetico_test_test_case_get_suite (CuboGeneticoTestTestCase* self);
#define CUBO_GENETICO_TEST_TEST_CASE_ADAPTOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR, CuboGeneticoTestTestCaseAdaptorPrivate))
enum  {
	CUBO_GENETICO_TEST_TEST_CASE_ADAPTOR_DUMMY_PROPERTY
};
static void cubo_genetico_test_test_case_adaptor_set_name (CuboGeneticoTestTestCaseAdaptor* self, const gchar* value);
static void cubo_genetico_test_test_case_adaptor_finalize (CuboGeneticoTestTestCaseAdaptor* obj);
static void cubo_genetico_test_test_case_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


/**
         * Creates a new test case with a given name.
         * @param name the name of the test case.
         */
CuboGeneticoTestTestCase* cubo_genetico_test_test_case_construct (GType object_type, const gchar* name) {
	CuboGeneticoTestTestCase * self = NULL;
	const gchar* _tmp0_ = NULL;
	GTestSuite* _tmp1_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	self = (CuboGeneticoTestTestCase*) g_object_new (object_type, NULL);
	_tmp0_ = name;
	_tmp1_ = g_test_create_suite (_tmp0_);
	self->priv->suite = _tmp1_;
	return self;
}


/**
         * Add a test with a name.
         * @param name the name of the test.
         * @param test the test method.
         */
static gpointer _cubo_genetico_test_test_case_adaptor_ref0 (gpointer self) {
	return self ? cubo_genetico_test_test_case_adaptor_ref (self) : NULL;
}


static void _vala_array_add1 (CuboGeneticoTestTestCaseAdaptor*** array, int* length, int* size, CuboGeneticoTestTestCaseAdaptor* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (CuboGeneticoTestTestCaseAdaptor*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void _cubo_genetico_test_test_case_adaptor_set_up_gtest_fixture_func (void* fixture, gpointer self) {
	cubo_genetico_test_test_case_adaptor_set_up ((CuboGeneticoTestTestCaseAdaptor*) self, fixture);
}


static void _cubo_genetico_test_test_case_adaptor_run_gtest_fixture_func (void* fixture, gpointer self) {
	cubo_genetico_test_test_case_adaptor_run ((CuboGeneticoTestTestCaseAdaptor*) self, fixture);
}


static void _cubo_genetico_test_test_case_adaptor_tear_down_gtest_fixture_func (void* fixture, gpointer self) {
	cubo_genetico_test_test_case_adaptor_tear_down ((CuboGeneticoTestTestCaseAdaptor*) self, fixture);
}


void cubo_genetico_test_test_case_add_test (CuboGeneticoTestTestCase* self, const gchar* name, CuboGeneticoTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify) {
	CuboGeneticoTestTestCaseAdaptor* adaptor = NULL;
	const gchar* _tmp0_ = NULL;
	CuboGeneticoTestTestCaseTestMethod _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	GDestroyNotify _tmp1__target_destroy_notify = NULL;
	CuboGeneticoTestTestCaseAdaptor* _tmp2_ = NULL;
	CuboGeneticoTestTestCaseAdaptor** _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	CuboGeneticoTestTestCaseAdaptor* _tmp4_ = NULL;
	GTestSuite* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	GTestCase* _tmp8_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = name;
	_tmp1_ = test;
	_tmp1__target = test_target;
	_tmp1__target_destroy_notify = test_target_destroy_notify;
	test = NULL;
	test_target = NULL;
	test_target_destroy_notify = NULL;
	_tmp2_ = cubo_genetico_test_test_case_adaptor_new (_tmp0_, _tmp1_, _tmp1__target, _tmp1__target_destroy_notify, self);
	adaptor = _tmp2_;
	_tmp3_ = self->priv->adaptors;
	_tmp3__length1 = self->priv->adaptors_length1;
	_tmp4_ = _cubo_genetico_test_test_case_adaptor_ref0 (adaptor);
	_vala_array_add1 (&self->priv->adaptors, &self->priv->adaptors_length1, &self->priv->_adaptors_size_, _tmp4_);
	_tmp5_ = self->priv->suite;
	_tmp6_ = cubo_genetico_test_test_case_adaptor_get_name (adaptor);
	_tmp7_ = _tmp6_;
	_tmp8_ = g_test_create_case (_tmp7_, (gsize) 0, adaptor, _cubo_genetico_test_test_case_adaptor_set_up_gtest_fixture_func, _cubo_genetico_test_test_case_adaptor_run_gtest_fixture_func, _cubo_genetico_test_test_case_adaptor_tear_down_gtest_fixture_func);
	g_test_suite_add (_tmp5_, _tmp8_);
	_cubo_genetico_test_test_case_adaptor_unref0 (adaptor);
	(test_target_destroy_notify == NULL) ? NULL : (test_target_destroy_notify (test_target), NULL);
	test = NULL;
	test_target = NULL;
	test_target_destroy_notify = NULL;
}


/**
         * Sets up the test.
         */
static void cubo_genetico_test_test_case_real_set_up (CuboGeneticoTestTestCase* self) {
}


void cubo_genetico_test_test_case_set_up (CuboGeneticoTestTestCase* self) {
	g_return_if_fail (self != NULL);
	CUBO_GENETICO_TEST_TEST_CASE_GET_CLASS (self)->set_up (self);
}


/**
         * Tears down the test.
         */
static void cubo_genetico_test_test_case_real_tear_down (CuboGeneticoTestTestCase* self) {
}


void cubo_genetico_test_test_case_tear_down (CuboGeneticoTestTestCase* self) {
	g_return_if_fail (self != NULL);
	CUBO_GENETICO_TEST_TEST_CASE_GET_CLASS (self)->tear_down (self);
}


/**
         * Returns the test suite.
         * @return the test suite.
         */
GTestSuite* cubo_genetico_test_test_case_get_suite (CuboGeneticoTestTestCase* self) {
	GTestSuite* result = NULL;
	GTestSuite* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->suite;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static CuboGeneticoTestTestCaseAdaptor* cubo_genetico_test_test_case_adaptor_construct (GType object_type, const gchar* name, CuboGeneticoTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify, CuboGeneticoTestTestCase* test_case) {
	CuboGeneticoTestTestCaseAdaptor* self = NULL;
	const gchar* _tmp0_ = NULL;
	CuboGeneticoTestTestCaseTestMethod _tmp1_ = NULL;
	void* _tmp1__target = NULL;
	GDestroyNotify _tmp1__target_destroy_notify = NULL;
	CuboGeneticoTestTestCase* _tmp2_ = NULL;
	CuboGeneticoTestTestCase* _tmp3_ = NULL;
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (test_case != NULL, NULL);
	self = (CuboGeneticoTestTestCaseAdaptor*) g_type_create_instance (object_type);
	_tmp0_ = name;
	cubo_genetico_test_test_case_adaptor_set_name (self, _tmp0_);
	_tmp1_ = test;
	_tmp1__target = test_target;
	_tmp1__target_destroy_notify = test_target_destroy_notify;
	test = NULL;
	test_target = NULL;
	test_target_destroy_notify = NULL;
	(self->priv->test_target_destroy_notify == NULL) ? NULL : (self->priv->test_target_destroy_notify (self->priv->test_target), NULL);
	self->priv->test = NULL;
	self->priv->test_target = NULL;
	self->priv->test_target_destroy_notify = NULL;
	self->priv->test = _tmp1_;
	self->priv->test_target = _tmp1__target;
	self->priv->test_target_destroy_notify = _tmp1__target_destroy_notify;
	_tmp2_ = test_case;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 (self->priv->test_case);
	self->priv->test_case = _tmp3_;
	(test_target_destroy_notify == NULL) ? NULL : (test_target_destroy_notify (test_target), NULL);
	test = NULL;
	test_target = NULL;
	test_target_destroy_notify = NULL;
	return self;
}


static CuboGeneticoTestTestCaseAdaptor* cubo_genetico_test_test_case_adaptor_new (const gchar* name, CuboGeneticoTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify, CuboGeneticoTestTestCase* test_case) {
	return cubo_genetico_test_test_case_adaptor_construct (CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR, name, test, test_target, test_target_destroy_notify, test_case);
}


static void cubo_genetico_test_test_case_adaptor_set_up (CuboGeneticoTestTestCaseAdaptor* self, void* fixture) {
	CuboGeneticoTestTestCase* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->test_case;
	cubo_genetico_test_test_case_set_up (_tmp0_);
}


static void cubo_genetico_test_test_case_adaptor_run (CuboGeneticoTestTestCaseAdaptor* self, void* fixture) {
	CuboGeneticoTestTestCaseTestMethod _tmp0_ = NULL;
	void* _tmp0__target = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->test;
	_tmp0__target = self->priv->test_target;
	_tmp0_ (_tmp0__target);
}


static void cubo_genetico_test_test_case_adaptor_tear_down (CuboGeneticoTestTestCaseAdaptor* self, void* fixture) {
	CuboGeneticoTestTestCase* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->test_case;
	cubo_genetico_test_test_case_tear_down (_tmp0_);
}


static const gchar* cubo_genetico_test_test_case_adaptor_get_name (CuboGeneticoTestTestCaseAdaptor* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


static void cubo_genetico_test_test_case_adaptor_set_name (CuboGeneticoTestTestCaseAdaptor* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
}


static void cubo_genetico_test_test_case_value_adaptor_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void cubo_genetico_test_test_case_value_adaptor_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		cubo_genetico_test_test_case_adaptor_unref (value->data[0].v_pointer);
	}
}


static void cubo_genetico_test_test_case_value_adaptor_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = cubo_genetico_test_test_case_adaptor_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer cubo_genetico_test_test_case_value_adaptor_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* cubo_genetico_test_test_case_value_adaptor_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		CuboGeneticoTestTestCaseAdaptor* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = cubo_genetico_test_test_case_adaptor_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* cubo_genetico_test_test_case_value_adaptor_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	CuboGeneticoTestTestCaseAdaptor** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = cubo_genetico_test_test_case_adaptor_ref (value->data[0].v_pointer);
	}
	return NULL;
}


static GParamSpec* cubo_genetico_test_test_case_param_spec_adaptor (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	CuboGeneticoTestTestCaseParamSpecAdaptor* spec;
	g_return_val_if_fail (g_type_is_a (object_type, CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


static gpointer cubo_genetico_test_test_case_value_get_adaptor (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR), NULL);
	return value->data[0].v_pointer;
}


static void cubo_genetico_test_test_case_value_set_adaptor (GValue* value, gpointer v_object) {
	CuboGeneticoTestTestCaseAdaptor* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		cubo_genetico_test_test_case_adaptor_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_test_test_case_adaptor_unref (old);
	}
}


static void cubo_genetico_test_test_case_value_take_adaptor (GValue* value, gpointer v_object) {
	CuboGeneticoTestTestCaseAdaptor* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_test_test_case_adaptor_unref (old);
	}
}


static void cubo_genetico_test_test_case_adaptor_class_init (CuboGeneticoTestTestCaseAdaptorClass * klass) {
	cubo_genetico_test_test_case_adaptor_parent_class = g_type_class_peek_parent (klass);
	((CuboGeneticoTestTestCaseAdaptorClass *) klass)->finalize = cubo_genetico_test_test_case_adaptor_finalize;
	g_type_class_add_private (klass, sizeof (CuboGeneticoTestTestCaseAdaptorPrivate));
}


static void cubo_genetico_test_test_case_adaptor_instance_init (CuboGeneticoTestTestCaseAdaptor * self) {
	self->priv = CUBO_GENETICO_TEST_TEST_CASE_ADAPTOR_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void cubo_genetico_test_test_case_adaptor_finalize (CuboGeneticoTestTestCaseAdaptor* obj) {
	CuboGeneticoTestTestCaseAdaptor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TEST_TEST_CASE_TYPE_ADAPTOR, CuboGeneticoTestTestCaseAdaptor);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->_name);
	(self->priv->test_target_destroy_notify == NULL) ? NULL : (self->priv->test_target_destroy_notify (self->priv->test_target), NULL);
	self->priv->test = NULL;
	self->priv->test_target = NULL;
	self->priv->test_target_destroy_notify = NULL;
	_g_object_unref0 (self->priv->test_case);
}


static GType cubo_genetico_test_test_case_adaptor_get_type (void) {
	static volatile gsize cubo_genetico_test_test_case_adaptor_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_test_test_case_adaptor_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { cubo_genetico_test_test_case_value_adaptor_init, cubo_genetico_test_test_case_value_adaptor_free_value, cubo_genetico_test_test_case_value_adaptor_copy_value, cubo_genetico_test_test_case_value_adaptor_peek_pointer, "p", cubo_genetico_test_test_case_value_adaptor_collect_value, "p", cubo_genetico_test_test_case_value_adaptor_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoTestTestCaseAdaptorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_test_test_case_adaptor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoTestTestCaseAdaptor), 0, (GInstanceInitFunc) cubo_genetico_test_test_case_adaptor_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType cubo_genetico_test_test_case_adaptor_type_id;
		cubo_genetico_test_test_case_adaptor_type_id = g_type_register_fundamental (g_type_fundamental_next (), "CuboGeneticoTestTestCaseAdaptor", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&cubo_genetico_test_test_case_adaptor_type_id__volatile, cubo_genetico_test_test_case_adaptor_type_id);
	}
	return cubo_genetico_test_test_case_adaptor_type_id__volatile;
}


static gpointer cubo_genetico_test_test_case_adaptor_ref (gpointer instance) {
	CuboGeneticoTestTestCaseAdaptor* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


static void cubo_genetico_test_test_case_adaptor_unref (gpointer instance) {
	CuboGeneticoTestTestCaseAdaptor* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		CUBO_GENETICO_TEST_TEST_CASE_ADAPTOR_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void cubo_genetico_test_test_case_class_init (CuboGeneticoTestTestCaseClass * klass) {
	cubo_genetico_test_test_case_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoTestTestCasePrivate));
	((CuboGeneticoTestTestCaseClass *) klass)->set_up = (void (*)(CuboGeneticoTestTestCase*)) cubo_genetico_test_test_case_real_set_up;
	((CuboGeneticoTestTestCaseClass *) klass)->tear_down = (void (*)(CuboGeneticoTestTestCase*)) cubo_genetico_test_test_case_real_tear_down;
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_test_test_case_finalize;
}


static void cubo_genetico_test_test_case_instance_init (CuboGeneticoTestTestCase * self) {
	CuboGeneticoTestTestCaseAdaptor** _tmp0_ = NULL;
	self->priv = CUBO_GENETICO_TEST_TEST_CASE_GET_PRIVATE (self);
	_tmp0_ = g_new0 (CuboGeneticoTestTestCaseAdaptor*, 0 + 1);
	self->priv->adaptors = _tmp0_;
	self->priv->adaptors_length1 = 0;
	self->priv->_adaptors_size_ = self->priv->adaptors_length1;
}


static void cubo_genetico_test_test_case_finalize (GObject* obj) {
	CuboGeneticoTestTestCase * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_TEST_TYPE_TEST_CASE, CuboGeneticoTestTestCase);
	self->priv->adaptors = (_vala_array_free (self->priv->adaptors, self->priv->adaptors_length1, (GDestroyNotify) cubo_genetico_test_test_case_adaptor_unref), NULL);
	G_OBJECT_CLASS (cubo_genetico_test_test_case_parent_class)->finalize (obj);
}


/**
     * Base class for test cases.
     */
GType cubo_genetico_test_test_case_get_type (void) {
	static volatile gsize cubo_genetico_test_test_case_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_test_test_case_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoTestTestCaseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_test_test_case_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoTestTestCase), 0, (GInstanceInitFunc) cubo_genetico_test_test_case_instance_init, NULL };
		GType cubo_genetico_test_test_case_type_id;
		cubo_genetico_test_test_case_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoTestTestCase", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&cubo_genetico_test_test_case_type_id__volatile, cubo_genetico_test_test_case_type_id);
	}
	return cubo_genetico_test_test_case_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



