/* test.h generated by valac 0.34.7, the Vala compiler, do not modify */


#ifndef __LIB_TEST_TEST_H__
#define __LIB_TEST_TEST_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define AUMBRALES_TEST_TYPE_TEST_CASE (aumbrales_test_test_case_get_type ())
#define AUMBRALES_TEST_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), AUMBRALES_TEST_TYPE_TEST_CASE, AumbralesTestTestCase))
#define AUMBRALES_TEST_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), AUMBRALES_TEST_TYPE_TEST_CASE, AumbralesTestTestCaseClass))
#define AUMBRALES_TEST_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), AUMBRALES_TEST_TYPE_TEST_CASE))
#define AUMBRALES_TEST_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), AUMBRALES_TEST_TYPE_TEST_CASE))
#define AUMBRALES_TEST_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), AUMBRALES_TEST_TYPE_TEST_CASE, AumbralesTestTestCaseClass))

typedef struct _AumbralesTestTestCase AumbralesTestTestCase;
typedef struct _AumbralesTestTestCaseClass AumbralesTestTestCaseClass;
typedef struct _AumbralesTestTestCasePrivate AumbralesTestTestCasePrivate;

struct _AumbralesTestTestCase {
	GObject parent_instance;
	AumbralesTestTestCasePrivate * priv;
};

struct _AumbralesTestTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (AumbralesTestTestCase* self);
	void (*tear_down) (AumbralesTestTestCase* self);
};

typedef void (*AumbralesTestTestCaseTestMethod) (void* user_data);

GType aumbrales_test_test_case_get_type (void) G_GNUC_CONST;
AumbralesTestTestCase* aumbrales_test_test_case_construct (GType object_type, const gchar* name);
void aumbrales_test_test_case_add_test (AumbralesTestTestCase* self, const gchar* name, AumbralesTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify);
void aumbrales_test_test_case_set_up (AumbralesTestTestCase* self);
void aumbrales_test_test_case_tear_down (AumbralesTestTestCase* self);
GTestSuite* aumbrales_test_test_case_get_suite (AumbralesTestTestCase* self);


G_END_DECLS

#endif
