/* test.h generated by valac 0.34.8, the Vala compiler, do not modify */


#ifndef __LIB_TEST_TEST_H__
#define __LIB_TEST_TEST_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define CUBO_GENETICO_TEST_TYPE_TEST_CASE (cubo_genetico_test_test_case_get_type ())
#define CUBO_GENETICO_TEST_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CASE, CuboGeneticoTestTestCase))
#define CUBO_GENETICO_TEST_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CASE, CuboGeneticoTestTestCaseClass))
#define CUBO_GENETICO_TEST_IS_TEST_CASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CASE))
#define CUBO_GENETICO_TEST_IS_TEST_CASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_TEST_TYPE_TEST_CASE))
#define CUBO_GENETICO_TEST_TEST_CASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_TEST_TYPE_TEST_CASE, CuboGeneticoTestTestCaseClass))

typedef struct _CuboGeneticoTestTestCase CuboGeneticoTestTestCase;
typedef struct _CuboGeneticoTestTestCaseClass CuboGeneticoTestTestCaseClass;
typedef struct _CuboGeneticoTestTestCasePrivate CuboGeneticoTestTestCasePrivate;

struct _CuboGeneticoTestTestCase {
	GObject parent_instance;
	CuboGeneticoTestTestCasePrivate * priv;
};

struct _CuboGeneticoTestTestCaseClass {
	GObjectClass parent_class;
	void (*set_up) (CuboGeneticoTestTestCase* self);
	void (*tear_down) (CuboGeneticoTestTestCase* self);
};

typedef void (*CuboGeneticoTestTestCaseTestMethod) (void* user_data);

GType cubo_genetico_test_test_case_get_type (void) G_GNUC_CONST;
CuboGeneticoTestTestCase* cubo_genetico_test_test_case_construct (GType object_type, const gchar* name);
void cubo_genetico_test_test_case_add_test (CuboGeneticoTestTestCase* self, const gchar* name, CuboGeneticoTestTestCaseTestMethod test, void* test_target, GDestroyNotify test_target_destroy_notify);
void cubo_genetico_test_test_case_set_up (CuboGeneticoTestTestCase* self);
void cubo_genetico_test_test_case_tear_down (CuboGeneticoTestTestCase* self);
GTestSuite* cubo_genetico_test_test_case_get_suite (CuboGeneticoTestTestCase* self);


G_END_DECLS

#endif
