/* agenetico.h generated by valac 0.34.8, the Vala compiler, do not modify */


#ifndef __LIB_AGENETICO_AGENETICO_H__
#define __LIB_AGENETICO_AGENETICO_H__

#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS


#define CUBO_GENETICO_AGENETICO_TYPE_CUBO3X3 (cubo_genetico_agenetico_cubo3x3_get_type ())
#define CUBO_GENETICO_AGENETICO_CUBO3X3(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_AGENETICO_TYPE_CUBO3X3, CuboGeneticoAGeneticoCubo3x3))
#define CUBO_GENETICO_AGENETICO_CUBO3X3_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_AGENETICO_TYPE_CUBO3X3, CuboGeneticoAGeneticoCubo3x3Class))
#define CUBO_GENETICO_AGENETICO_IS_CUBO3X3(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_AGENETICO_TYPE_CUBO3X3))
#define CUBO_GENETICO_AGENETICO_IS_CUBO3X3_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_AGENETICO_TYPE_CUBO3X3))
#define CUBO_GENETICO_AGENETICO_CUBO3X3_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_AGENETICO_TYPE_CUBO3X3, CuboGeneticoAGeneticoCubo3x3Class))

typedef struct _CuboGeneticoAGeneticoCubo3x3 CuboGeneticoAGeneticoCubo3x3;
typedef struct _CuboGeneticoAGeneticoCubo3x3Class CuboGeneticoAGeneticoCubo3x3Class;
typedef struct _CuboGeneticoAGeneticoCubo3x3Private CuboGeneticoAGeneticoCubo3x3Private;

#define CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO (cubo_genetico_agenetico_individuo_get_type ())
#define CUBO_GENETICO_AGENETICO_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuo))
#define CUBO_GENETICO_AGENETICO_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuoClass))
#define CUBO_GENETICO_AGENETICO_IS_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_AGENETICO_IS_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_AGENETICO_INDIVIDUO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuoClass))

typedef struct _CuboGeneticoAGeneticoIndividuo CuboGeneticoAGeneticoIndividuo;
typedef struct _CuboGeneticoAGeneticoIndividuoClass CuboGeneticoAGeneticoIndividuoClass;
typedef struct _CuboGeneticoAGeneticoIndividuoPrivate CuboGeneticoAGeneticoIndividuoPrivate;

struct _CuboGeneticoAGeneticoCubo3x3 {
	GObject parent_instance;
	CuboGeneticoAGeneticoCubo3x3Private * priv;
};

struct _CuboGeneticoAGeneticoCubo3x3Class {
	GObjectClass parent_class;
};

struct _CuboGeneticoAGeneticoIndividuo {
	GObject parent_instance;
	CuboGeneticoAGeneticoIndividuoPrivate * priv;
};

struct _CuboGeneticoAGeneticoIndividuoClass {
	GObjectClass parent_class;
};


GType cubo_genetico_agenetico_cubo3x3_get_type (void) G_GNUC_CONST;
CuboGeneticoAGeneticoCubo3x3* cubo_genetico_agenetico_cubo3x3_new (gint* cubo, int cubo_length1, int cubo_length2);
CuboGeneticoAGeneticoCubo3x3* cubo_genetico_agenetico_cubo3x3_construct (GType object_type, gint* cubo, int cubo_length1, int cubo_length2);
gint* cubo_genetico_agenetico_cubo3x3_getActual (CuboGeneticoAGeneticoCubo3x3* self, int* result_length1, int* result_length2);
void cubo_genetico_agenetico_cubo3x3_reset (CuboGeneticoAGeneticoCubo3x3* self);
void cubo_genetico_agenetico_cubo3x3_giraCaras (CuboGeneticoAGeneticoCubo3x3* self, gint* giros, int giros_length1);
void cubo_genetico_agenetico_cubo3x3_giraCara (CuboGeneticoAGeneticoCubo3x3* self, gint i);
void cubo_genetico_agenetico_cubo3x3_to_string (CuboGeneticoAGeneticoCubo3x3* self);
void cubo_genetico_agenetico_cubo3x3_dibuja (CuboGeneticoAGeneticoCubo3x3* self, gdouble fit);
GType cubo_genetico_agenetico_individuo_get_type (void) G_GNUC_CONST;
gchar* cubo_genetico_agenetico_individuo_to_string (CuboGeneticoAGeneticoIndividuo* self);
CuboGeneticoAGeneticoIndividuo* cubo_genetico_agenetico_individuo_new (void);
CuboGeneticoAGeneticoIndividuo* cubo_genetico_agenetico_individuo_construct (GType object_type);
gint* cubo_genetico_agenetico_individuo_get_genotipo (CuboGeneticoAGeneticoIndividuo* self, int* result_length1);
void cubo_genetico_agenetico_individuo_set_genotipo (CuboGeneticoAGeneticoIndividuo* self, gint* value, int value_length1);
gchar** cubo_genetico_agenetico_individuo_get_fenotipo (CuboGeneticoAGeneticoIndividuo* self, int* result_length1);
void cubo_genetico_agenetico_individuo_set_fenotipo (CuboGeneticoAGeneticoIndividuo* self, gchar** value, int value_length1);
gdouble cubo_genetico_agenetico_individuo_get_fitness (CuboGeneticoAGeneticoIndividuo* self);
void cubo_genetico_agenetico_individuo_set_fitness (CuboGeneticoAGeneticoIndividuo* self, gdouble value);


G_END_DECLS

#endif
