/* Fenotipo.c generated by valac 0.34.8, the Vala compiler
 * generated from Fenotipo.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO (cubo_genetico_agenetico_fenotipo_get_type ())
#define CUBO_GENETICO_AGENETICO_FENOTIPO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO, CuboGeneticoAGeneticoFenotipo))
#define CUBO_GENETICO_AGENETICO_FENOTIPO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO, CuboGeneticoAGeneticoFenotipoClass))
#define CUBO_GENETICO_AGENETICO_IS_FENOTIPO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO))
#define CUBO_GENETICO_AGENETICO_IS_FENOTIPO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO))
#define CUBO_GENETICO_AGENETICO_FENOTIPO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO, CuboGeneticoAGeneticoFenotipoClass))

typedef struct _CuboGeneticoAGeneticoFenotipo CuboGeneticoAGeneticoFenotipo;
typedef struct _CuboGeneticoAGeneticoFenotipoClass CuboGeneticoAGeneticoFenotipoClass;
typedef struct _CuboGeneticoAGeneticoFenotipoPrivate CuboGeneticoAGeneticoFenotipoPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _CuboGeneticoAGeneticoParamSpecFenotipo CuboGeneticoAGeneticoParamSpecFenotipo;

struct _CuboGeneticoAGeneticoFenotipo {
	GTypeInstance parent_instance;
	volatile int ref_count;
	CuboGeneticoAGeneticoFenotipoPrivate * priv;
};

struct _CuboGeneticoAGeneticoFenotipoClass {
	GTypeClass parent_class;
	void (*finalize) (CuboGeneticoAGeneticoFenotipo *self);
};

struct _CuboGeneticoAGeneticoFenotipoPrivate {
	gchar** feno;
	gint feno_length1;
	gint _feno_size_;
};

struct _CuboGeneticoAGeneticoParamSpecFenotipo {
	GParamSpec parent_instance;
};


static gpointer cubo_genetico_agenetico_fenotipo_parent_class = NULL;

gpointer cubo_genetico_agenetico_fenotipo_ref (gpointer instance);
void cubo_genetico_agenetico_fenotipo_unref (gpointer instance);
GParamSpec* cubo_genetico_agenetico_param_spec_fenotipo (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void cubo_genetico_agenetico_value_set_fenotipo (GValue* value, gpointer v_object);
void cubo_genetico_agenetico_value_take_fenotipo (GValue* value, gpointer v_object);
gpointer cubo_genetico_agenetico_value_get_fenotipo (const GValue* value);
GType cubo_genetico_agenetico_fenotipo_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_AGENETICO_FENOTIPO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO, CuboGeneticoAGeneticoFenotipoPrivate))
enum  {
	CUBO_GENETICO_AGENETICO_FENOTIPO_DUMMY_PROPERTY
};
CuboGeneticoAGeneticoFenotipo* cubo_genetico_agenetico_fenotipo_new (gint n);
CuboGeneticoAGeneticoFenotipo* cubo_genetico_agenetico_fenotipo_construct (GType object_type, gint n);
gchar* cubo_genetico_agenetico_fenotipo_to_string (CuboGeneticoAGeneticoFenotipo* self);
gchar** cubo_genetico_agenetico_fenotipo_get_fenotipo (CuboGeneticoAGeneticoFenotipo* self, int* result_length1);
static void cubo_genetico_agenetico_fenotipo_finalize (CuboGeneticoAGeneticoFenotipo* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


CuboGeneticoAGeneticoFenotipo* cubo_genetico_agenetico_fenotipo_construct (GType object_type, gint n) {
	CuboGeneticoAGeneticoFenotipo* self = NULL;
	gint _tmp0_ = 0;
	gchar** _tmp1_ = NULL;
	self = (CuboGeneticoAGeneticoFenotipo*) g_type_create_instance (object_type);
	_tmp0_ = n;
	_tmp1_ = g_new0 (gchar*, _tmp0_ + 1);
	self->priv->feno = (_vala_array_free (self->priv->feno, self->priv->feno_length1, (GDestroyNotify) g_free), NULL);
	self->priv->feno = _tmp1_;
	self->priv->feno_length1 = _tmp0_;
	self->priv->_feno_size_ = self->priv->feno_length1;
	return self;
}


CuboGeneticoAGeneticoFenotipo* cubo_genetico_agenetico_fenotipo_new (gint n) {
	return cubo_genetico_agenetico_fenotipo_construct (CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO, n);
}


gchar* cubo_genetico_agenetico_fenotipo_to_string (CuboGeneticoAGeneticoFenotipo* self) {
	gchar* result = NULL;
	gchar* s = NULL;
	gchar* _tmp0_ = NULL;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("Fenotipo: ");
	s = _tmp0_;
	_tmp1_ = self->priv->feno;
	_tmp1__length1 = self->priv->feno_length1;
	{
		gchar** i_collection = NULL;
		gint i_collection_length1 = 0;
		gint _i_collection_size_ = 0;
		gint i_it = 0;
		i_collection = _tmp1_;
		i_collection_length1 = _tmp1__length1;
		for (i_it = 0; i_it < _tmp1__length1; i_it = i_it + 1) {
			gchar* _tmp2_ = NULL;
			gchar* i = NULL;
			_tmp2_ = g_strdup (i_collection[i_it]);
			i = _tmp2_;
			{
				const gchar* _tmp3_ = NULL;
				const gchar* _tmp4_ = NULL;
				gchar* _tmp5_ = NULL;
				gchar* _tmp6_ = NULL;
				gchar* _tmp7_ = NULL;
				_tmp3_ = s;
				_tmp4_ = i;
				_tmp5_ = g_strconcat (_tmp4_, ",", NULL);
				_tmp6_ = _tmp5_;
				_tmp7_ = g_strconcat (_tmp3_, _tmp6_, NULL);
				_g_free0 (s);
				s = _tmp7_;
				_g_free0 (_tmp6_);
				_g_free0 (i);
			}
		}
	}
	_tmp8_ = s;
	_tmp9_ = g_strconcat (_tmp8_, "\n", NULL);
	_g_free0 (s);
	s = _tmp9_;
	result = s;
	return result;
}


gchar** cubo_genetico_agenetico_fenotipo_get_fenotipo (CuboGeneticoAGeneticoFenotipo* self, int* result_length1) {
	gchar** result;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->feno;
	_tmp0__length1 = self->priv->feno_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static void cubo_genetico_agenetico_value_fenotipo_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void cubo_genetico_agenetico_value_fenotipo_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		cubo_genetico_agenetico_fenotipo_unref (value->data[0].v_pointer);
	}
}


static void cubo_genetico_agenetico_value_fenotipo_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = cubo_genetico_agenetico_fenotipo_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer cubo_genetico_agenetico_value_fenotipo_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* cubo_genetico_agenetico_value_fenotipo_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		CuboGeneticoAGeneticoFenotipo* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = cubo_genetico_agenetico_fenotipo_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* cubo_genetico_agenetico_value_fenotipo_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	CuboGeneticoAGeneticoFenotipo** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = cubo_genetico_agenetico_fenotipo_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* cubo_genetico_agenetico_param_spec_fenotipo (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	CuboGeneticoAGeneticoParamSpecFenotipo* spec;
	g_return_val_if_fail (g_type_is_a (object_type, CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer cubo_genetico_agenetico_value_get_fenotipo (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO), NULL);
	return value->data[0].v_pointer;
}


void cubo_genetico_agenetico_value_set_fenotipo (GValue* value, gpointer v_object) {
	CuboGeneticoAGeneticoFenotipo* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		cubo_genetico_agenetico_fenotipo_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_agenetico_fenotipo_unref (old);
	}
}


void cubo_genetico_agenetico_value_take_fenotipo (GValue* value, gpointer v_object) {
	CuboGeneticoAGeneticoFenotipo* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		cubo_genetico_agenetico_fenotipo_unref (old);
	}
}


static void cubo_genetico_agenetico_fenotipo_class_init (CuboGeneticoAGeneticoFenotipoClass * klass) {
	cubo_genetico_agenetico_fenotipo_parent_class = g_type_class_peek_parent (klass);
	((CuboGeneticoAGeneticoFenotipoClass *) klass)->finalize = cubo_genetico_agenetico_fenotipo_finalize;
	g_type_class_add_private (klass, sizeof (CuboGeneticoAGeneticoFenotipoPrivate));
}


static void cubo_genetico_agenetico_fenotipo_instance_init (CuboGeneticoAGeneticoFenotipo * self) {
	self->priv = CUBO_GENETICO_AGENETICO_FENOTIPO_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void cubo_genetico_agenetico_fenotipo_finalize (CuboGeneticoAGeneticoFenotipo* obj) {
	CuboGeneticoAGeneticoFenotipo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_AGENETICO_TYPE_FENOTIPO, CuboGeneticoAGeneticoFenotipo);
	g_signal_handlers_destroy (self);
	self->priv->feno = (_vala_array_free (self->priv->feno, self->priv->feno_length1, (GDestroyNotify) g_free), NULL);
}


GType cubo_genetico_agenetico_fenotipo_get_type (void) {
	static volatile gsize cubo_genetico_agenetico_fenotipo_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_agenetico_fenotipo_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { cubo_genetico_agenetico_value_fenotipo_init, cubo_genetico_agenetico_value_fenotipo_free_value, cubo_genetico_agenetico_value_fenotipo_copy_value, cubo_genetico_agenetico_value_fenotipo_peek_pointer, "p", cubo_genetico_agenetico_value_fenotipo_collect_value, "p", cubo_genetico_agenetico_value_fenotipo_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoAGeneticoFenotipoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_agenetico_fenotipo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoAGeneticoFenotipo), 0, (GInstanceInitFunc) cubo_genetico_agenetico_fenotipo_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType cubo_genetico_agenetico_fenotipo_type_id;
		cubo_genetico_agenetico_fenotipo_type_id = g_type_register_fundamental (g_type_fundamental_next (), "CuboGeneticoAGeneticoFenotipo", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&cubo_genetico_agenetico_fenotipo_type_id__volatile, cubo_genetico_agenetico_fenotipo_type_id);
	}
	return cubo_genetico_agenetico_fenotipo_type_id__volatile;
}


gpointer cubo_genetico_agenetico_fenotipo_ref (gpointer instance) {
	CuboGeneticoAGeneticoFenotipo* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void cubo_genetico_agenetico_fenotipo_unref (gpointer instance) {
	CuboGeneticoAGeneticoFenotipo* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		CUBO_GENETICO_AGENETICO_FENOTIPO_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



