/* Individuo.c generated by valac 0.34.8, the Vala compiler
 * generated from Individuo.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>


#define CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO (cubo_genetico_agenetico_individuo_get_type ())
#define CUBO_GENETICO_AGENETICO_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuo))
#define CUBO_GENETICO_AGENETICO_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuoClass))
#define CUBO_GENETICO_AGENETICO_IS_INDIVIDUO(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_AGENETICO_IS_INDIVIDUO_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO))
#define CUBO_GENETICO_AGENETICO_INDIVIDUO_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuoClass))

typedef struct _CuboGeneticoAGeneticoIndividuo CuboGeneticoAGeneticoIndividuo;
typedef struct _CuboGeneticoAGeneticoIndividuoClass CuboGeneticoAGeneticoIndividuoClass;
typedef struct _CuboGeneticoAGeneticoIndividuoPrivate CuboGeneticoAGeneticoIndividuoPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _CuboGeneticoAGeneticoIndividuo {
	GObject parent_instance;
	CuboGeneticoAGeneticoIndividuoPrivate * priv;
};

struct _CuboGeneticoAGeneticoIndividuoClass {
	GObjectClass parent_class;
};

struct _CuboGeneticoAGeneticoIndividuoPrivate {
	gint* _genotipo;
	gint _genotipo_length1;
	gint __genotipo_size_;
	gchar** _fenotipo;
	gint _fenotipo_length1;
	gint __fenotipo_size_;
	gdouble _fitness;
};


static gpointer cubo_genetico_agenetico_individuo_parent_class = NULL;

GType cubo_genetico_agenetico_individuo_get_type (void) G_GNUC_CONST;
#define CUBO_GENETICO_AGENETICO_INDIVIDUO_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuoPrivate))
enum  {
	CUBO_GENETICO_AGENETICO_INDIVIDUO_DUMMY_PROPERTY,
	CUBO_GENETICO_AGENETICO_INDIVIDUO_FENOTIPO,
	CUBO_GENETICO_AGENETICO_INDIVIDUO_FITNESS
};
gchar* cubo_genetico_agenetico_individuo_to_string (CuboGeneticoAGeneticoIndividuo* self);
gint* cubo_genetico_agenetico_individuo_get_genotipo (CuboGeneticoAGeneticoIndividuo* self, int* result_length1);
gchar** cubo_genetico_agenetico_individuo_get_fenotipo (CuboGeneticoAGeneticoIndividuo* self, int* result_length1);
gdouble cubo_genetico_agenetico_individuo_get_fitness (CuboGeneticoAGeneticoIndividuo* self);
CuboGeneticoAGeneticoIndividuo* cubo_genetico_agenetico_individuo_new (void);
CuboGeneticoAGeneticoIndividuo* cubo_genetico_agenetico_individuo_construct (GType object_type);
void cubo_genetico_agenetico_individuo_set_genotipo (CuboGeneticoAGeneticoIndividuo* self, gint* value, int value_length1);
static gint* _vala_array_dup3 (gint* self, int length);
void cubo_genetico_agenetico_individuo_set_fenotipo (CuboGeneticoAGeneticoIndividuo* self, gchar** value, int value_length1);
static gchar** _vala_array_dup4 (gchar** self, int length);
void cubo_genetico_agenetico_individuo_set_fitness (CuboGeneticoAGeneticoIndividuo* self, gdouble value);
static void cubo_genetico_agenetico_individuo_finalize (GObject* obj);
static void _vala_cubo_genetico_agenetico_individuo_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_cubo_genetico_agenetico_individuo_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static gchar* double_to_string (gdouble self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_ = NULL;
	_tmp0_ = g_new0 (gchar, G_ASCII_DTOSTR_BUF_SIZE);
	_tmp1_ = _tmp0_;
	_tmp1__length1 = G_ASCII_DTOSTR_BUF_SIZE;
	_tmp2_ = g_ascii_dtostr (_tmp1_, G_ASCII_DTOSTR_BUF_SIZE, self);
	_tmp3_ = g_strdup (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp1_ = (g_free (_tmp1_), NULL);
	result = _tmp4_;
	return result;
}


gchar* cubo_genetico_agenetico_individuo_to_string (CuboGeneticoAGeneticoIndividuo* self) {
	gchar* result = NULL;
	gchar* s = NULL;
	gchar* _tmp0_ = NULL;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gint* _tmp2_ = NULL;
	gint _tmp2__length1 = 0;
	const gchar* _tmp10_ = NULL;
	gchar* _tmp11_ = NULL;
	gchar** _tmp12_ = NULL;
	gint _tmp12__length1 = 0;
	gchar** _tmp13_ = NULL;
	gint _tmp13__length1 = 0;
	const gchar* _tmp21_ = NULL;
	gdouble _tmp22_ = 0.0;
	gchar* _tmp23_ = NULL;
	gchar* _tmp24_ = NULL;
	gchar* _tmp25_ = NULL;
	gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup ("Genotipo: ");
	s = _tmp0_;
	_tmp1_ = cubo_genetico_agenetico_individuo_get_genotipo (self, &_tmp1__length1);
	_tmp2_ = _tmp1_;
	_tmp2__length1 = _tmp1__length1;
	{
		gint* i_collection = NULL;
		gint i_collection_length1 = 0;
		gint _i_collection_size_ = 0;
		gint i_it = 0;
		i_collection = _tmp2_;
		i_collection_length1 = _tmp2__length1;
		for (i_it = 0; i_it < _tmp2__length1; i_it = i_it + 1) {
			gint i = 0;
			i = i_collection[i_it];
			{
				const gchar* _tmp3_ = NULL;
				gint _tmp4_ = 0;
				gchar* _tmp5_ = NULL;
				gchar* _tmp6_ = NULL;
				gchar* _tmp7_ = NULL;
				gchar* _tmp8_ = NULL;
				gchar* _tmp9_ = NULL;
				_tmp3_ = s;
				_tmp4_ = i;
				_tmp5_ = g_strdup_printf ("%i", _tmp4_);
				_tmp6_ = _tmp5_;
				_tmp7_ = g_strconcat (_tmp6_, ",", NULL);
				_tmp8_ = _tmp7_;
				_tmp9_ = g_strconcat (_tmp3_, _tmp8_, NULL);
				_g_free0 (s);
				s = _tmp9_;
				_g_free0 (_tmp8_);
				_g_free0 (_tmp6_);
			}
		}
	}
	_tmp10_ = s;
	_tmp11_ = g_strconcat (_tmp10_, "\nFenotipo: ", NULL);
	_g_free0 (s);
	s = _tmp11_;
	_tmp12_ = cubo_genetico_agenetico_individuo_get_fenotipo (self, &_tmp12__length1);
	_tmp13_ = _tmp12_;
	_tmp13__length1 = _tmp12__length1;
	{
		gchar** i_collection = NULL;
		gint i_collection_length1 = 0;
		gint _i_collection_size_ = 0;
		gint i_it = 0;
		i_collection = _tmp13_;
		i_collection_length1 = _tmp13__length1;
		for (i_it = 0; i_it < _tmp13__length1; i_it = i_it + 1) {
			gchar* _tmp14_ = NULL;
			gchar* i = NULL;
			_tmp14_ = g_strdup (i_collection[i_it]);
			i = _tmp14_;
			{
				const gchar* _tmp15_ = NULL;
				const gchar* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				gchar* _tmp18_ = NULL;
				gchar* _tmp19_ = NULL;
				gchar* _tmp20_ = NULL;
				_tmp15_ = s;
				_tmp16_ = i;
				_tmp17_ = string_to_string (_tmp16_);
				_tmp18_ = g_strconcat (_tmp17_, ",", NULL);
				_tmp19_ = _tmp18_;
				_tmp20_ = g_strconcat (_tmp15_, _tmp19_, NULL);
				_g_free0 (s);
				s = _tmp20_;
				_g_free0 (_tmp19_);
				_g_free0 (i);
			}
		}
	}
	_tmp21_ = s;
	_tmp22_ = self->priv->_fitness;
	_tmp23_ = double_to_string (_tmp22_);
	_tmp24_ = _tmp23_;
	_tmp25_ = g_strconcat ("\nFitness: ", _tmp24_, NULL);
	_tmp26_ = _tmp25_;
	_tmp27_ = g_strconcat (_tmp21_, _tmp26_, NULL);
	_g_free0 (s);
	s = _tmp27_;
	_g_free0 (_tmp26_);
	_g_free0 (_tmp24_);
	result = s;
	return result;
}


CuboGeneticoAGeneticoIndividuo* cubo_genetico_agenetico_individuo_construct (GType object_type) {
	CuboGeneticoAGeneticoIndividuo * self = NULL;
	self = (CuboGeneticoAGeneticoIndividuo*) g_object_new (object_type, NULL);
	return self;
}


CuboGeneticoAGeneticoIndividuo* cubo_genetico_agenetico_individuo_new (void) {
	return cubo_genetico_agenetico_individuo_construct (CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO);
}


gint* cubo_genetico_agenetico_individuo_get_genotipo (CuboGeneticoAGeneticoIndividuo* self, int* result_length1) {
	gint* result;
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_genotipo;
	_tmp0__length1 = self->priv->_genotipo_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gint* _vala_array_dup3 (gint* self, int length) {
	return g_memdup (self, length * sizeof (gint));
}


void cubo_genetico_agenetico_individuo_set_genotipo (CuboGeneticoAGeneticoIndividuo* self, gint* value, int value_length1) {
	gint* _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gint* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup3 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_genotipo = (g_free (self->priv->_genotipo), NULL);
	self->priv->_genotipo = _tmp1_;
	self->priv->_genotipo_length1 = _tmp1__length1;
	self->priv->__genotipo_size_ = self->priv->_genotipo_length1;
}


gchar** cubo_genetico_agenetico_individuo_get_fenotipo (CuboGeneticoAGeneticoIndividuo* self, int* result_length1) {
	gchar** result;
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_fenotipo;
	_tmp0__length1 = self->priv->_fenotipo_length1;
	_tmp1_ = _tmp0_;
	_tmp1__length1 = _tmp0__length1;
	if (result_length1) {
		*result_length1 = _tmp1__length1;
	}
	result = _tmp1_;
	return result;
}


static gchar** _vala_array_dup4 (gchar** self, int length) {
	gchar** result;
	int i;
	result = g_new0 (gchar*, length + 1);
	for (i = 0; i < length; i++) {
		gchar* _tmp0_ = NULL;
		_tmp0_ = g_strdup (self[i]);
		result[i] = _tmp0_;
	}
	return result;
}


void cubo_genetico_agenetico_individuo_set_fenotipo (CuboGeneticoAGeneticoIndividuo* self, gchar** value, int value_length1) {
	gchar** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	gchar** _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp0__length1 = value_length1;
	_tmp1_ = (_tmp0_ != NULL) ? _vala_array_dup4 (_tmp0_, _tmp0__length1) : ((gpointer) _tmp0_);
	_tmp1__length1 = _tmp0__length1;
	self->priv->_fenotipo = (_vala_array_free (self->priv->_fenotipo, self->priv->_fenotipo_length1, (GDestroyNotify) g_free), NULL);
	self->priv->_fenotipo = _tmp1_;
	self->priv->_fenotipo_length1 = _tmp1__length1;
	self->priv->__fenotipo_size_ = self->priv->_fenotipo_length1;
	g_object_notify ((GObject *) self, "fenotipo");
}


gdouble cubo_genetico_agenetico_individuo_get_fitness (CuboGeneticoAGeneticoIndividuo* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_fitness;
	result = _tmp0_;
	return result;
}


void cubo_genetico_agenetico_individuo_set_fitness (CuboGeneticoAGeneticoIndividuo* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_fitness = _tmp0_;
	g_object_notify ((GObject *) self, "fitness");
}


static void cubo_genetico_agenetico_individuo_class_init (CuboGeneticoAGeneticoIndividuoClass * klass) {
	cubo_genetico_agenetico_individuo_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (CuboGeneticoAGeneticoIndividuoPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_cubo_genetico_agenetico_individuo_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_cubo_genetico_agenetico_individuo_set_property;
	G_OBJECT_CLASS (klass)->finalize = cubo_genetico_agenetico_individuo_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), CUBO_GENETICO_AGENETICO_INDIVIDUO_FENOTIPO, g_param_spec_boxed ("fenotipo", "fenotipo", "fenotipo", G_TYPE_STRV, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), CUBO_GENETICO_AGENETICO_INDIVIDUO_FITNESS, g_param_spec_double ("fitness", "fitness", "fitness", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void cubo_genetico_agenetico_individuo_instance_init (CuboGeneticoAGeneticoIndividuo * self) {
	self->priv = CUBO_GENETICO_AGENETICO_INDIVIDUO_GET_PRIVATE (self);
}


static void cubo_genetico_agenetico_individuo_finalize (GObject* obj) {
	CuboGeneticoAGeneticoIndividuo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuo);
	self->priv->_genotipo = (g_free (self->priv->_genotipo), NULL);
	self->priv->_fenotipo = (_vala_array_free (self->priv->_fenotipo, self->priv->_fenotipo_length1, (GDestroyNotify) g_free), NULL);
	G_OBJECT_CLASS (cubo_genetico_agenetico_individuo_parent_class)->finalize (obj);
}


GType cubo_genetico_agenetico_individuo_get_type (void) {
	static volatile gsize cubo_genetico_agenetico_individuo_type_id__volatile = 0;
	if (g_once_init_enter (&cubo_genetico_agenetico_individuo_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (CuboGeneticoAGeneticoIndividuoClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) cubo_genetico_agenetico_individuo_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (CuboGeneticoAGeneticoIndividuo), 0, (GInstanceInitFunc) cubo_genetico_agenetico_individuo_instance_init, NULL };
		GType cubo_genetico_agenetico_individuo_type_id;
		cubo_genetico_agenetico_individuo_type_id = g_type_register_static (G_TYPE_OBJECT, "CuboGeneticoAGeneticoIndividuo", &g_define_type_info, 0);
		g_once_init_leave (&cubo_genetico_agenetico_individuo_type_id__volatile, cubo_genetico_agenetico_individuo_type_id);
	}
	return cubo_genetico_agenetico_individuo_type_id__volatile;
}


static void _vala_cubo_genetico_agenetico_individuo_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	CuboGeneticoAGeneticoIndividuo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuo);
	switch (property_id) {
		case CUBO_GENETICO_AGENETICO_INDIVIDUO_FENOTIPO:
		{
			int length;
			g_value_set_boxed (value, cubo_genetico_agenetico_individuo_get_fenotipo (self, &length));
		}
		break;
		case CUBO_GENETICO_AGENETICO_INDIVIDUO_FITNESS:
		g_value_set_double (value, cubo_genetico_agenetico_individuo_get_fitness (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_cubo_genetico_agenetico_individuo_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	CuboGeneticoAGeneticoIndividuo * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, CUBO_GENETICO_AGENETICO_TYPE_INDIVIDUO, CuboGeneticoAGeneticoIndividuo);
	switch (property_id) {
		case CUBO_GENETICO_AGENETICO_INDIVIDUO_FENOTIPO:
		{
			gpointer boxed;
			boxed = g_value_get_boxed (value);
			cubo_genetico_agenetico_individuo_set_fenotipo (self, boxed, (boxed == NULL) ? 0 : g_strv_length (boxed));
		}
		break;
		case CUBO_GENETICO_AGENETICO_INDIVIDUO_FITNESS:
		cubo_genetico_agenetico_individuo_set_fitness (self, g_value_get_double (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



